### ISSUE TITLE
Default Search Engine automaticly changes to visited website (Github, Wikipedia etc.)

### ISSUE THREAD

**Issue by serial-bug** [bromite/bromite#1994] opened 2022-04-18 12:05 UTC
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

100.0.4896.92

### Device architecture

arm64

### Android version

12

### Device model

Pixel 4a

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

with "https://lite.qwant.com" as default Search Engine set, if you visit github or wikipedia, then the default search engine automaticly changes. 
Under the search engine selection then it shows e.g. "Wikipedia" with URL "lite.qwant.com", but it is not possible anymore to search trough lite.qwant.com, every request goes to wikipedia search.
The issue was introduced with Bromite release  "100.0.4896.83".

### Steps to reproduce the bug

1. visit "https://lite.want.com"
2. do a search
3. goto Settings -> Search Engines and select "lite.qwant.com" as default
4. do a search for a wikipedia article trough default search engine (lite.qwant.com at this moment)
5. visit the wikipedia article
6. now, if you try another search trough the default search engine, you will notice that it has changed to wikipedia search
7. under Settings -> Search Engines you will see an Entry "Wikipedia" with the URL "lite.qwant.com"

### Expected behavior

The default search engine (in my case "lite.qwant.com") dont changes automaticly on visit of other websites with OpenSearch.

**Comment by Disqu3-mirOir-qt** [comment] 2022-04-18 16:52
exactly same bug when i set lite.qwant.com

**Comment by csagan5** [comment] 2022-04-18 21:37
I cannot reproduce this issue.
Please run `adb logcat | grep OpenSearch` and report back your lines; you can remove privacy-sensitive information if any.

**Comment by Disqu3-mirOir-qt** [comment] 2022-04-18 22:30
https://user-images.githubusercontent.com/41585567/163887579-32708053-11a0-4fc1-8f9f-5af2955b78b5.mp4


log soon

**Comment by Disqu3-mirOir-qt** [comment] 2022-04-18 22:42
![IMG_20220419_004207.jpg](https://user-images.githubusercontent.com/41585567/163888779-bbb20e4e-d940-4a24-b47b-9d76586d0cea.jpg)


i get only this

**Comment by Disqu3-mirOir-qt** [comment] 2022-04-18 22:44
![IMG_20220419_004419.jpg](https://user-images.githubusercontent.com/41585567/163888995-10bd79a4-5460-4129-9d29-7ede232d9e17.jpg)

**Comment by csagan5** [comment] 2022-04-18 23:25
> recording_20220419_002436.mp4

Now I can reproduce it, thanks. Bug was introduced in version `100.0.4896.57`.

**Comment by Disqu3-mirOir-qt** [comment] 2022-04-18 23:51
perfect , happy help bromite

**Comment by serial-bug** [comment] 2022-04-19 05:55
Thank you very much !

**Comment by csagan5** [comment] 2022-05-28 10:17
Fixed in `102.0.5005.67`.

**Closed by csagan5** 2022-05-28 10:17 UTC
Labels: bug
