### ISSUE TITLE
Support for Autofill in Android 9.0+

### ISSUE THREAD

**Issue by JetSetDoritos** [bromite/bromite#254] opened 2019-02-26 00:14 UTC
**Is your feature request related to privacy?
Only privacy-related feature requests are considered.**

In a way, good password hygine can be considered privacy related.

**Is there a patch available for this feature somewhere?**

Not that I'm aware of.

**Describe the solution you'd like
A clear and concise description of what you want to happen.**

In Android 9.0 Pie Google has opened up their Autofill API to work in browsers, any chance this could get supported in Bromite?

When selecting a password field, the Autofill API would prompt the user to fill the login fields with the password manager of their choice.

 **Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.**

N/A

**Comment by csagan5** [comment] 2019-02-26 05:45
Duplicate of #230

**Closed by csagan5** 2019-02-26 05:45 UTC
