### ISSUE TITLE
Add an option to open links launched from outside the app in an incognito tab

### ISSUE THREAD

**Issue by ghost** [bromite/bromite#728] opened 2020-09-05 00:35 UTC
**Is your feature request related to privacy?:** yes.

**Is there a patch available for this feature somewhere?:** I am not sure.

**Describe the solution you would like:** please may an option be added that'll make Bromite open links that are launched from outside the app in a incognito tab instead of a regular tab. Firefox for Android has this feature and it's called "Open links in private tab".

**Describe alternatives you have considered:** I'm aware of the current option "Open links in incognito tabs always" however this doesn't behave like my suggested option.

**Comment by csagan5** [comment] 2020-09-05 10:30
@UnpilotedRebuilt1 can you provide steps to reproduce the issue?

**Comment by csagan5** [comment] 2020-09-05 10:32
@uazo possibly related: #132 #135

**Comment by csagan5** [comment] 2020-09-05 10:36
Rather than an option I think we should strive to make all links open in incognito when always-incognito is enabled.

**Comment by uazo** [comment] 2020-09-05 10:37
I think he wants to be able to open an incognito link via an external activity.
However, tell me if I'm wrong, it must be the external application asking for the mode using an extra, right?

> Rather than an option I think we should strive to make all links open in incognito when always-incognito is enabled.

it should already be.

**Comment by csagan5** [comment] 2020-09-05 10:38
> However, tell me if I'm wrong, it must be the external application asking for the mode using an extra, right?

Unless I am mistaken, the extra for incognito is added when incognito mode is enabled.

**Comment by uazo** [comment] 2020-09-05 10:44
yes, but I think he would like to choose, when opening a link from another application, whether to open in normal or incognito mode, without activating always incognito.
let's wait what says @UnpilotedRebuilt1

**Comment by UnpilotedRebuilt1** [comment] 2020-09-05 14:17
> Rather than an option I think we should strive to make all links open in incognito when always-incognito is enabled.

My issue with the "Open links in incognito tabs always" is that it just turns the app into incognito only mode. The option I'm trying to suggest however I'm struggling to explain just keeps the app completely regular however links that are opened from outside the app will open in an incognito tab. For example: I am sent a link on WhatsApp and Bromite is my default browser, when my option is enabled in the settings instead of opening the link in a regular tab it'll open it in a incognito one. However it doesn't affect clicking links directly in Bromite.

Firefox for Android has the exact feature I'm trying to describe. Their official documentation describes the feature as "You can set Firefox to always open links from other apps in private browsing".

**Comment by csagan5** [comment] 2020-09-05 15:13
@uazo since the always-incognito page already does that for intents and activities, we could allow it additionally when this setting is enabled?

**Comment by uazo** [comment] 2020-09-06 09:07
I think it should be investigated.
when I fixed the crash on startup with always incognito mode, I noticed that during the startup only one tab is initialized (normal or incognito), if you ask for an incognito navigation in a normal tab, that exception is triggered.

since the startup is before the management of the intent (at least what logic should say, it would ask to an experienced android programmer) it does not know if a url is being opened from the outside or simply the user is opening the browser.
but, for now, I don't have the knowledge to be sure.

maybe we could use the incognito app shortcut because already exist in the code, but I don't know.

**Comment by csagan5** [comment] 2020-09-06 11:14
> it does not know if a url is being opened from the outside or simply the user is opening the browser.
> but, for now, I don't have the knowledge to be sure.

All URLs opened via intent or activity are "from outside", no? The user opening the browser does not correspond to any new navigation activity?

**Comment by uazo** [comment] 2020-09-06 11:30
> All URLs opened via intent or activity are "from outside", no? 

not so obvious, chromium uses intents for internal navigation as well, adding an extra extra in some of them to identify the source (itself).
for example, in the code there is a block for opening incognito navigation from the outside, it is only allowed if that extra is present

> The user opening the browser does not correspond to any new navigation activity?

I don't known.
that is, add the feature might be possible, but it doesn't seem like a simple copy/paste.

**Comment by pixincreate** [comment] 2021-04-01 03:12
I came across this feature flag and it's similar to this issue, but that doesn't seem to work!     
  
**#cct-incognito-available-to-third-party**    
  
![Screenshot_20210401-084002](https://user-images.githubusercontent.com/69745008/113238278-147f5080-92c6-11eb-81df-506fbb98ba16.png)

**Comment by famo** [comment] 2021-08-29 18:22
I'm also looking exactly for this feature. I thought the easiest way would be to add a second intent for bromite, such as "Bromite (incognito)" (which would open links in incognito mode).
This way the user would be prompted by android every time he clicks on a link and could choose the intent / mode...
^^
@csagan5 @uazo

**Comment by csagan5** [comment] 2021-10-10 09:35
Fixed in `93.0.4577.110`.

@pixincreate those flags are enabled by default in Bromite in another patch; `Send tab to self when signed-in` could not possibly work because there is no sign-in in Bromite.

**Closed by csagan5** 2021-10-10 09:35 UTC

**Comment by pixincreate** [comment] 2021-10-11 00:37
Thank you
