### ISSUE TITLE
Cannot enable search suggestions/tap to search

### ISSUE THREAD

**Issue by mthomos** [bromite/bromite#375] opened 2019-09-24 10:07 UTC
**Bromite version**

Version: `77.0.3865.95`
Arch: `arm64`
Android version: `9.0`
Device model: 'Sony Xperia XZ1'

**Is this bug about the SystemWebView?**
No

**Is the bug reproducible with latest version?** 'Yes'

**Can the bug be reproduced with corresponding Chromium version?**
No

**Is the bug a crash?**

No

**Describe the bug**

I don't know if it's intented to work or not. Using latest version and all search engines, suggestions don't work.

**To Reproduce**

1. Tap to omnibox
2. Type text

**Expected behavior**

See suggestions for search

**Comment by csagan5** [comment] 2019-09-25 07:36
The problem here is that the option is disabled by default and the option is no more visible in settings; upstream moved it.

I will have to look into this to possibly restore the menu options also for non-logged-in users.

**Comment by csagan5** [comment] 2019-09-25 08:55
The relevant menu entries have been removed in upstream commit https://github.com/chromium/chromium/commit/c672a0683e89eba3554e2562156b3c8532136f21

**Comment by csagan5** [comment] 2019-09-28 08:13
In `77.0.3865.104` is now possible to enable search suggestions, however "Tap to search" seems to have no effect.

**Comment by nikolowry** [comment] 2019-10-21 17:02
@csagan5 can confirm same results on `78.0.3904.63` -- search suggestions work and enabling "Tap to search" has no effect

**Comment by csagan5** [comment] 2019-10-25 22:55
I have identified them missing code bit; the contextual search toggle will be fixed in next release.

**Comment by csagan5** [comment] 2019-12-01 11:49
@mthomos is this problem still present in latest version? I am afraid that even with the code changes the preference is not working properly.

**Comment by icejr** [comment] 2019-12-01 13:38
It seems like this issues is also fixed (at least for me) on `78.0.3904.119`

**Comment by mthomos** [comment] 2019-12-01 13:51
Tap to search doesn't work.

**Comment by csagan5** [comment] 2019-12-01 18:23
@icejr can you please check that it is not in the tap menu when it's disabled in settings, and viceversa?

**Comment by icejr** [comment] 2019-12-05 10:03
@csagan5 I'm having a strange issue... no matter what option I set (enable/disable) in settings for tap to search, I'm still able to see a 'Web Search' option when selecting a text... but web search/tap to search is working just fine

**Comment by nikolowry** [comment] 2019-12-05 13:40
@csagan5 as of the last two versions, these options have disappeared from my settings' Privacy menu (clean builds). Assumed they were dropped, but now after seeing these latest comments I'd thought it might be worth mentioning

**Comment by csagan5** [comment] 2019-12-05 22:47
@icejr yes, I have verified the same in a test installation. It is some mishap with the preferences but I have not yet been able to figure it out.

@nikolowry which options? Upstream has moved most of them to a menu which is visible only after logging to the services. I have restored only those which are used by Bromite but there are some issues left, as per this issue. The one we are discussing here is called "Tap to search" and is under "Allow custom tab intents".

**Comment by nikolowry** [comment] 2019-12-05 23:43
@csagan5 you can compare the two screenshots of `78.0.3904.119` below.

__ARM64 SDK21 build via bromite.org__:
![Screenshot_20191205-182048_Bromite](https://user-images.githubusercontent.com/597310/70282884-4e514d00-178d-11ea-80d1-092cc167a00b.png)

__ARM64 SDK21 build via bromite-builder (clean build)__:
![Screenshot_20191205-181940_Chromium](https://user-images.githubusercontent.com/597310/70282934-7771dd80-178d-11ea-95bd-6acb0e4ec3c9.png)

---

I'm assuming it's a similar situation to what happened that caused this commit https://github.com/bromite/bromite/commit/532c9c5c8b2c8ab5a32bad0b0c635292dcd4e945 -- I can't find the actual thread were we discussed this, but even though the patch was failing your builds were still successful due to the past compilations available in `out`.

Could be wrong though, they just recently disappeared in the past two versions for me

**Comment by csagan5** [comment] 2019-12-06 07:41
> I can't find the actual thread where we discussed this

It's here: https://github.com/nikolowry/bromite-builder/issues/1#issuecomment-450956669

I assume you build from scratch so that you are unaffected by this problem? It is a sneaky problem happening mostly with generated/resource files. I will have to do a build from scratch but first I will try to selectively invalidate that part to see if I can find a better fix for the build system (this is a build invalidation bug, after all).

**Comment by nikolowry** [comment] 2019-12-06 13:39
@csagan5 correct, I reset Chromium's `src` directory on every release via `git clean` https://github.com/nikolowry/bromite-builder/commit/d45c836cebd91b4ff2dad36ec8fa799b5f9e774a#diff-7b284bdb25f120af7fd4aa7a6e40ff86R117.

My machine builds Chromium from scratch in ~.75-1.5 hours. If you ever need a build from scratch validated just @ me.

**Comment by csagan5** [comment] 2019-12-07 20:37
@nikolowry I have rebuilt it from scratch and the "tap to search" option is there. Perhaps you do not have the right set of patches?

**Comment by nikolowry** [comment] 2019-12-08 15:40
Here's my stdout prior to compilation @csagan5 :
```
./bromite-builder --arch=arm64 --gn-args="use_jumbo_build=true jumbo_file_merge_limit=8" --dark-navbar
Python 2.7.17
Revision now set to 78.0.3904.119
Fetching Bromite Archive
Extracting Bromite Archive
Fetching and Syncing Chromium

[0:01:10] Still working on:
[0:01:10]   src

[0:01:20] Still working on:
[0:01:20]   src
1>Syncing projects:   0% ( 0/ 2) 
[0:01:26] Still working on:
[0:01:26]   src
Syncing projects: 100% (300/300), done.                                                                   
Running hooks:  20% (13/64) binutils              
________ running 'vpython src/third_party/binutils/download.py' in '/home/neeks/Development/android/bromite-builder/build/chromium'
0> Downloading /home/neeks/Development/android/bromite-builder/build/chromium/src/third_party/binutils/Linux_x64/binutils.tar.bz2...
Downloading 1 files took 5.709619 second(s)
Downloading /home/neeks/Development/android/bromite-builder/build/chromium/src/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /home/neeks/Development/android/bromite-builder/build/chromium/src/third_party/binutils/Linux_x64/binutils.tar.bz2
Running hooks:  21% (14/64) clang   
________ running 'vpython src/tools/clang/scripts/update.py' in '/home/neeks/Development/android/bromite-builder/build/chromium'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-371202-8455294f-1.tgz .......... Done.
Running hooks:  35% (23/64) clang_format_linux
________ running 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' in '/home/neeks/Development/android/bromite-builder/build/chromium'
0> Downloading src/buildtools/linux64/clang-format...
Downloading 1 files took 5.386573 second(s)
Running hooks:  51% (33/64) node_linux64        
________ running 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/10.15.3 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' in '/home/neeks/Development/android/bromite-builder/build/chromium'
0> Downloading src/third_party/node/linux/node-linux-x64.tar.gz...
0> Extracting 4540 entries from src/third_party/node/linux/node-linux-x64.tar.gz to src/third_party/node/linux/node-linux-x64
Downloading 1 files took 6.993830 second(s)
Running hooks:  56% (36/64) webui_node_modules
________ running 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs -s src/third_party/node/node_modules.tar.gz.sha1' in '/home/neeks/Development/android/bromite-builder/build/chromium'
0> Downloading src/third_party/node/node_modules.tar.gz...
0> Extracting 6894 entries from src/third_party/node/node_modules.tar.gz to src/third_party/node/node_modules
Downloading 1 files took 6.022023 second(s)
Running hooks:  73% (47/64) doclava                                     
________ running 'vpython src/build/android/download_doclava.py' in '/home/neeks/Development/android/bromite-builder/build/chromium'
0> Downloading src/buildtools/android/doclava.tar.gz...
0> Extracting 7 entries from src/buildtools/android/doclava.tar.gz to src/buildtools/android/doclava
Downloading 1 files took 5.630825 second(s)
Running hooks: 100% (64/64), done.
Applying patch: Disable-third-party-cookies-by-default.patch
Applying patch: Revert-Remove-pre-unified-consent-code-in-sync-and-privacy-directory.patch
Applying patch: Revert-Remove-UnifiedConsent-from-ChromeFeatureList.patch
Applying patch: Restore-classic-new-tab-page.patch
Applying patch: Always-use-new-tab-page-for-default-home-page.patch
Applying patch: Always-allow-partner-customisation.patch
Applying patch: Always-show-home-page-settings.patch
Applying patch: battery_status_service-disable-more-privacy-nightmares.patch
Applying patch: Battery-API-return-nothing.patch
Applying patch: google-cloud-messaging-disable-experiment-status-check.patch
Applying patch: updater-disable-updater-pings.patch
Applying patch: prefs-only-keep-cookies-until-exit.patch
Applying patch: Remove-EV-certificates.patch
Applying patch: promo-disable-Google-promotion-fetching.patch
Applying patch: Disable-omission-of-URL-elements-in-Omnibox.patch
Applying patch: Modify-default-preferences.patch
Applying patch: Disable-contextual-search-by-default.patch
Applying patch: Do-not-store-passwords-by-default.patch
Applying patch: Disable-NTP-remote-suggestions-by-default.patch
Applying patch: Disable-references-to-fonts.googleapis.com.patch
Applying patch: Disable-WebRTC-by-default.patch
Applying patch: Never-send-any-crash-upload-data.patch
Applying patch: Hide-send-reports-checkbox.patch
Applying patch: Never-fetch-popular-sites.patch
Applying patch: ungoogled-chromium-Disable-webRTC-log-uploader.patch
Applying patch: ungoogled-chromium-Disable-untraceable-URLs.patch
Applying patch: ungoogled-chromium-Disable-translate-integration.patch
Applying patch: ungoogled-chromium-Disable-profile-avatar-downloading.patch
Applying patch: ungoogled-chromium-Disable-intranet-redirect-detector.patch
Applying patch: ungoogled-chromium-Disable-Google-host-detection.patch
Applying patch: ungoogled-chromium-Disable-GCM.patch
Applying patch: ungoogled-chromium-Disable-Gaia.patch
Applying patch: ungoogled-chromium-Disable-domain-reliability.patch
Applying patch: ungoogled-chromium-Disable-Network-Time-Tracker.patch
Applying patch: ungoogled-chromium-Always-use-local-DevTools-files-instead-of-remote-files-from-Google.patch
Applying patch: safe_browsing-disable-incident-reporting.patch
Applying patch: safe_browsing-disable-reporting-of-safebrowsing-override.patch
Applying patch: safe_browsing-disable-cookie-transmission.patch
Applying patch: Disable-safe-browsing.patch
Applying patch: Skip-the-first-run-and-metrics.patch
Applying patch: Disable-all-promo-dialogs.patch
Applying patch: Disable-sync-services-menu-entry.patch
Applying patch: Remove-signin-and-data-saver-integrations.patch
Applying patch: Remove-background-sync-and-translate-menu-options.patch
Applying patch: Hide-passwords-manager-link.patch
Applying patch: Disable-Omaha-update-checks.patch
Applying patch: Disable-update-scheduler.patch
Applying patch: Add-StartPage-search-engine.patch
Applying patch: Add-English-only-search-engine.patch
Applying patch: Add-DuckDuckGo-Lite-search-engine.patch
Applying patch: Add-Qwant-search-engine.patch
Applying patch: Fix-crash-when-accessing-page-info-site-settings.patch
Applying patch: openH264-enable-ARM-ARM64-optimizations.patch
Applying patch: Switch-to-fstack-protector-strong.patch
Applying patch: Enable-fwrapv-in-Clang-for-non-UBSan-builds.patch
Applying patch: build-remove-calling-untrusted-hooks.patch
Applying patch: AV1-codec-support.patch
Applying patch: Inject-scripts-for-AMP-tracking-ads-and-video-functionality.patch
Applying patch: Allow-playing-audio-in-background.patch
Applying patch: Add-flag-to-control-video-playback-resume-feature.patch
Applying patch: Open-YouTube-links-in-Bromite.patch
Applying patch: Add-exit-menu-item.patch
Applying patch: Remove-help-menu-item.patch
Applying patch: Add-menu-option-to-toggle-global-Javascript-preference.patch
Applying patch: Add-menu-option-to-toggle-ad-blocker.patch
Applying patch: User-Agent-anonymize.patch
Applying patch: AudioBuffer-AnalyserNode-fingerprinting-mitigations-via-IDL.patch
Applying patch: Multiple-fingerprinting-mitigations-for-canvas-text-and-client-rectangles.patch
Applying patch: Add-flags-to-disable-device-motion-and-orientation-APIs.patch
Applying patch: Punt-the-Widevine-version-string.patch
Applying patch: Disable-metrics-on-all-I-O-threads.patch
Applying patch: Always-respect-async-dns-flag-regardless-of-SDK-version.patch
Applying patch: Add-flag-to-configure-maximum-connections-per-host.patch
Applying patch: Add-site-settings-option-for-session-only-cookies.patch
Applying patch: Add-bookmark-import-export-actions.patch
Applying patch: Disable-promos-displayed-in-bookmarks-manager.patch
Applying patch: Add-an-always-incognito-mode.patch
Applying patch: Add-custom-tab-intents-privacy-option.patch
Applying patch: Add-option-to-not-persist-tabs-across-sessions.patch
Applying patch: Disable-fetching-of-all-field-trials.patch
Applying patch: Disable-seed-based-field-trials.patch
Applying patch: Disable-plugins-enumeration.patch
Applying patch: net-cert-increase-default-key-length-for-newly-generated-RSA-keys.patch
Applying patch: dns-send-IPv6-connectivity-probes-to-RIPE-DNS.patch
Applying patch: profile-resetter-do-not-tick-send-settings-by-default.patch
Applying patch: browser-ui-disable-warning-about-missing-API-keys.patch
Applying patch: autofill-disable-autofill-download-manager.patch
Applying patch: first_run-deactivate-autoupdate-globally.patch
Applying patch: translate-disable-fetching-of-translate-languages-from-server.patch
Applying patch: kill-TOS-and-metrics-opt-out.patch
Applying patch: kill-Translate.patch
Applying patch: kill-Vision.patch
Applying patch: kill-Location-fall-back-to-system.patch
Applying patch: kill-Auth.patch
Applying patch: Remove-dependency-on-com.google.android.gms.auth.patch
Applying patch: kill-GCM.patch
Applying patch: Remove-dependency-on-com.google.android.gcm.patch
Applying patch: Remove-dependency-on-com.google.android.gms.gcm.patch
Applying patch: Remove-dependency-on-com.google.android.play.patch
Applying patch: Remove-dependency-on-com.google.android.gms.vision-com.google.android.gms.clearcut-com.google.android.gms.phenotype.patch
Applying patch: Remove-dependency-on-com.google.android.gms.flags-com.google.android.gms.location.places-com.google.android.gms.stats.patch
Applying patch: Remove-dependency-on-com.google.android.gms.fido-com.google.android.gms.iid-com.google.android.gms.instantapps-com.google.android.gms.location.patch
Applying patch: Remove-dependency-on-com.google.android.gms.cast.patch
Applying patch: Remove-dependency-on-com.google.android.gms.common-auth-signin-dynamic-com.google.android.gms.tasks.patch
Applying patch: Remove-play-dependency-for-module-installer.patch
Applying patch: Remove-SMS-integration.patch
Applying patch: Allow-website-sign-in-without-account-sign-in.patch
Applying patch: Offer-builtin-autocomplete-for-chrome-flags.patch
Applying patch: Do-not-grant-notifications-to-default-search-engine.patch
Applying patch: Add-flag-to-disable-IPv6-probes.patch
Applying patch: Add-a-proxy-configuration-page.patch
Applying patch: Do-not-ignore-download-location-prompt-setting.patch
Applying patch: Disable-previews-by-default.patch
Applying patch: Use-4-tile-rows-never-show-logo.patch
Applying patch: Disable-metrics-collection-for-NTP-tiles.patch
Applying patch: Enable-site-per-process-isolation-for-devices-with-enough-memory.patch
Applying patch: Use-64-bit-WebView-processes.patch
Applying patch: Add-option-to-use-home-page-as-NTP.patch
Applying patch: Enable-night-mode-menu-entry-by-default.patch
Applying patch: Disable-dynamic-module-loading.patch
Applying patch: prefs-disable-signinallowed-by-default.patch
Applying patch: prefs-always-prompt-for-download-directory-by-default.patch
Applying patch: Disable-offline-pages-in-the-downloads-home-to-be-opened-in-CCT-by-default.patch
Applying patch: Enable-changing-default-downloads-storage-location-by-default.patch
Applying patch: Enable-download-rename-option-by-default.patch
Applying patch: disable-payment-support-by-default.patch
Applying patch: disable-background-sync-by-default.patch
Applying patch: disable-sensors-access-site-setting-by-default.patch
Applying patch: Disable-media-router-and-remoting-by-default.patch
Applying patch: Do-not-record-UMA-for-network-errors.patch
Applying patch: Disable-unified-consent-on-Android.patch
Applying patch: Revert-Cleanup-Search-Ready-Omnibox-flag-since-it-has-launched.patch
Applying patch: Disable-search-ready-omnibox-by-default.patch
Applying patch: disable-AdsBlockedInfoBar.patch
Applying patch: Bromite-AdBlockUpdaterService.patch
Applying patch: Revert-Merge-to-M78-Enable-AImageReader-by-default.patch
Applying patch: Replace-DoH-probe-domain-with-RIPE-domain.patch
Applying patch: Increase-number-of-autocomplete-matches-from-5-to-10.patch
Applying patch: Disable-HEAD-requests-for-single-word-Omnibar-searches.patch
Applying patch: Block-all-connection-requests-with-qjz9zk-in-the-domain-name-or-with-a-trk-scheme.patch
Applying patch: Disable-some-signed-exchange-features.patch
Applying patch: Add-flag-to-disable-WebGL.patch
Applying patch: Add-user-setting-for-DNS-over-HTTPS-custom-URL.patch
Applying patch: Dark-Navbar.patch
Done. Made 29150 targets from 1776 files in 6773ms
ninja: Entering directory `out/Default_78.0.3904.119_arm64'
```

I helps I can link you to the apk after it's built.

**Comment by nikolowry** [comment] 2019-12-08 19:25
@csagan5 ignore my last few comments, you were right and everything was building as expected. 

I had previously enabled "Unified Consent" in chrome://flags, switching that back to default they reappear. Sorry for sidetracking the issue.

**Comment by csagan5** [comment] 2019-12-09 11:36
@nikolowry no worries; I didn't think of that setting, it is basically useless in Bromite and was used in the transition to move a bunch of options under the logged-in menu.

**Comment by csagan5** [comment] 2019-12-28 08:24
@icejr @mthomos @nikolowry can this issue be reproduced for you with Chromium 79.0.3945.100?

https://www.bromite.org/chromium

**Comment by csagan5** [comment] 2019-12-28 20:43
I think that "Contextual search" is something different than the "Search" menu. What we are currently seeing in Bromite has always been there, see https://github.com/chromium/chromium/commit/1f1083f8bf08eeda6a0e9a48dc9e16a8dca15b9f

The contextual search is something else that pops up from below when using Chromium; I guess that doesn't popup in Bromite because the functionality requires cloud integrations.

**Comment by csagan5** [comment] 2020-01-09 15:50
Since `79.0.3945.111` there is no more any contextual search option.

**Closed by csagan5** 2020-01-09 15:50 UTC
Labels: bug
