### ISSUE TITLE
Crashes when playing video

### ISSUE THREAD

**Issue by scrubjay55** [bromite/bromite#459] opened 2020-01-06 15:03 UTC
### Bromite version

Version: `79.0.3945.107.`
Arch: `arm64`
Android version: `10`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Is the bug a crash?
Yes

### Describe the bug
Bromite crashes whenever a video is tried to be played.

### Steps to reproduce the bug

1. Try to play a video

**Comment by scrubjay55** [comment] 2020-01-06 15:07
`01-06 17:56:30.688 E/chromium(24043): [ERROR:url_request.cc(599)] Block URL in URLRequest: https://www.95tat1c.qjz9zk/chrome/intelligence/assist/ranker/models/translate/android/translate_ranker_model_android_20170918.pb.bin
01-06 17:56:30.689 E/chromium(24043): [ERROR:trk_protocol_handler.cc(17)] Blocked URL in TrkProtocolHandler: trk:https://www.95tat1c.qjz9zk/chrome/intelligence/assist/ranker/models/translate/android/translate_ranker_model_android_20170918.pb.bin
01-06 17:56:34.202 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Audio configuration specified 1 channels, but FFmpeg thinks the file contains 2 channels"}
01-06 17:56:34.805 E/chromium(27236): [0106/175634.805232:ERROR:socket.cc(181)] incorrect payload size 0
01-06 17:56:35.198 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio decode error"}
01-06 17:56:35.198 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
01-06 17:56:35.280 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
01-06 17:56:35.280 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
01-06 17:56:35.354 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decode error"}
01-06 17:56:35.397 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
01-06 17:56:35.397 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
01-06 17:56:35.421 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: PIPELINE_ERROR PIPELINE_ERROR_DECODE
01-06 17:56:35.820 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Audio configuration specified 1 channels, but FFmpeg thinks the file contains 2 channels"}
01-06 17:56:36.102 E/chromium(27321): [0106/175636.098706:ERROR:socket.cc(181)] incorrect payload size 0
01-06 17:56:36.439 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio decode error"}
01-06 17:56:36.440 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
01-06 17:56:36.554 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
01-06 17:56:36.555 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
01-06 17:56:36.636 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
01-06 17:56:36.637 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio error during playing, status: PIPELINE_ERROR_DECODE"}
01-06 17:56:36.647 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decode error"}
01-06 17:56:36.659 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: PIPELINE_ERROR PIPELINE_ERROR_DECODE
01-06 17:56:37.762 E/chromium(24916): [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"MediaSource endOfStream before demuxer initialization completes (before HAVE_METADATA) is treated as an error. This may also occur as consequence of other MediaSource errors before HAVE_METADATA."}
`
Here is the logcat. Hope it's useful.

**Comment by csagan5** [comment] 2020-01-06 16:04
@scrubjay55 I think this is a duplicate of the pinned #445?

Can you verify?

**Comment by nerrixDE** [comment] 2020-01-06 16:31
Pretty sure as this is the same problem I had (also Android 10, Version ...107 on arm64).
I solved it by uninstalling Bromite and installing the `arm` version.

**Comment by csagan5** [comment] 2020-01-06 18:06
@nerrixDE there is a [workaround mentioned there](https://github.com/bromite/bromite/issues/445#issuecomment-569671082) which does not involve installing the 32bit version and loosing history, bookmarks etc

**Comment by csagan5** [comment] 2020-01-06 18:07
Duplicate of #445

**Closed by csagan5** 2020-01-06 18:07 UTC

**Comment by nerrixDE** [comment] 2020-01-06 18:09
> @nerrixDE there is a [workaround mentioned there](https://github.com/bromite/bromite/issues/445#issuecomment-569671082) which does not involve installing the 32bit version and loosing history, bookmarks etc

I read that and this not(!) works on Android 10 (als one other said too)

**Comment by csagan5** [comment] 2020-01-08 01:26
> I read that and this not(!) works on Android 10 (als one other said too)

No, I have no track of anybody writing that.
