### ISSUE TITLE
Per-site javascript setting in site info page

### ISSUE THREAD

**Issue by Poopooracoocoo** [bromite/bromite#432] opened 2019-12-08 21:02 UTC
### Is your feature request related to privacy?

_Features that are not related to privacy are unlikely to be considered._
Yeah I think this is related to privacy. It's more about making privacy easier though.
### Is there a patch available for this feature somewhere?

_If yes then provide URL and license information._
I'm not sure about a URL and license info but at one point I think Bromite had it.
### Describe the solution you would like

_A clear and concise description of what you want to happen._

_Do not ask "I would like feature X which is available in browser Y"; such issues are closed immediately._
The javascript setting would appear in the site info page just like the adblock setting. Currently you have to go to the menu, settings, site settings, javascript and then add a site exception which is harder than the adblock setting. 
### Describe alternatives you have considered

_A clear and concise description of any alternative solutions or features you have considered._
honestly not sure

**Comment by csagan5** [comment] 2019-12-09 11:25
Duplicate of #133

**Closed by csagan5** 2019-12-09 11:25 UTC
