### ISSUE TITLE
Reset permissions

### ISSUE THREAD

**Issue by Gottarocket** [bromite/bromite#1991] opened 2022-04-17 02:28 UTC
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Not in browsers as I have seen but Android does have this on its app permissions 

### Describe the solution you would like

Reset site settings permission after sometime to prevent js allowing fingerprinting or show ads if it was turned off for a while

### Describe alternatives you have considered

After javascript or Ads are turned off for one time it needs to be reverted. Some may find it annoying to turn it off again and again so its better to have a option to set a time like 3days or a week . So  if those websites ,where its turned off, isnt opened or accessed within that timeframe will revert permissions to what they did set on settings->site settings

**Comment by Bantul-the-great** [comment] 2022-04-17 13:21
Alongwith the over mentioned feature request to "set a timeframe to revert the site settings", it would be much more hardcore if site settings are reset every time we "EXIT". I am eagerly looking forward for such feature inclusion.

**Comment by Bantul-the-great** [comment] 2022-04-17 13:41
Suppose, I visit a site very often which usually works Javascript being 'OFF', but sometimes it breaks while doing something specific. Then I need to turn 'ON' Javascript temporarily, but I don't want to open the site next time with Javascript 'ON' already. What I have to do each time is that I have to check the site settings and reset the permission so that next time it opens freshly without Javascript being 'ON'. It is really a tedious process. If each time when we tap 'EXIT', all the site settings get reset, the browser will match the quality of 'TOR BROWSER' in this perspective, erasing everything with closing a session. 

N.B- I have set Bromite as hardcore private as possible turning the always incognito mode 'ON'.  So, I can expect to erase everything in each session, including the site-specific settings, each time I tap on 'EXIT'.

**Comment by Gottarocket** [comment] 2022-04-17 14:02
This is what I need too but devs need to consider everyone . If thats the case then they need to add whole new option under site settings to customize it . So suggested resets after sometime so it can be middle ground between normal user and hardcore as you mentioned

**Comment by uazo** [comment] 2022-04-17 14:58
> I have set Bromite as hardcore private as possible turning the always incognito mode 'ON'. So, I can expect to erase everything in each session, including the site-specific settings, each time I tap on 'EXIT'.

i think it can be simple solved by putting the changes made in #1496 #1827 under a user flag

**Comment by csagan5** [comment] 2022-04-18 21:41
> If each time when we tap 'EXIT', all the site settings get reset, the browser will match the quality of 'TOR BROWSER' in this perspective, erasing everything with closing a session.

See https://github.com/bromite/bromite#privacy-limitations



> > I have set Bromite as hardcore private as possible turning the always incognito mode 'ON'. So, I can expect to erase everything in each session, including the site-specific settings, each time I tap on 'EXIT'.
> 
> i think it can be simple solved by putting the changes made in #1496 #1827 under a user flag

I think it was working as intended before (site settings never "remembered" when changed in incognito), so this user flag should be disabled by default.

**Comment by uazo** [comment] 2022-04-19 11:15
> I think it was working as intended before (site settings never "remembered" when changed in incognito), so this user flag should be disabled by default.

perfect, do you think it is appropriate to make a submenu for the always incognito options?
I think for example:

from privacy settings, click on Always Incognito, then:
- Always Incognito (on/off)
- Reset site settings on startup (on/off)
- Enable history service (on/off)

**Comment by csagan5** [comment] 2022-04-19 15:37
Sure, but then I suggest that the patches are merged; please assign authorship of that whole patch to you and we can mention the original author in the description.

**Comment by uazo** [comment] 2022-04-20 07:44
ok, do you agree if we do it later with v101?
considering that there is a week left, perhaps it is better to block developments and dedicate ourselves to the rebase?

**Comment by csagan5** [comment] 2022-04-20 21:23
> ok, do you agree if we do it later with v101?

You can do it whenever you like.

> considering that there is a week left, perhaps it is better to block developments and dedicate ourselves to the rebase?

No, you can submit it any time you prefer. I may or may not have already started the rebase, there is not one week left, I do not stick to any deadline or calendar, releases are made on a "best effort" basis.

**Comment by uazo** [comment] 2022-04-21 06:55
> No, you can submit it any time you prefer.

thank you

> I do not stick to any deadline or calendar

Sorry, I understand, I will not bother you on the matter anymore.

**Comment by csagan5** [comment] 2022-04-21 23:06
No worries, it's also important for you: do not feel compelled to stress out and do anything with haste.

**Comment by csagan5** [comment] 2022-05-02 23:06
Fixed in `101.0.4951.53`.

**Closed by csagan5** 2022-05-02 23:06 UTC
Labels: enhancement, needs-triage
