### ISSUE TITLE
Clear Data on quit

### ISSUE THREAD

**Issue by spinoza-dat** [bromite/bromite#611] opened 2020-06-04 09:59 UTC
### Is your feature request related to privacy?

Absolutely.

### Is there a patch available for this feature somewhere?

I don't think so, but there are extensions for this on Chromium Desktop.

### Describe the solution you would like

An option to auto-clear on quit different sets of data, other than cookies, would be really appreciated.

![IMG_20200604_114816](https://user-images.githubusercontent.com/63900993/83742610-ec996f00-a659-11ea-81a7-727bb1af7c7f.jpg)

This is a possible template (sorry for the mess with the translation).

### Describe alternatives you have considered

I know most of these are cleared when in incognito, but there are some cons in incognito like not being able to take screenshots.
Having separated options like "Don't keep history" (which would be maybe even better) and cache autoclear would be nice too.

**Comment by csagan5** [comment] 2020-06-04 17:07
Duplicate of #426

**Closed by csagan5** 2020-06-04 17:07 UTC

**Comment by spinoza-dat** [comment] 2020-06-04 20:53
@csagan5 no. Not a duplicate as I explicitely clarified the necessity of an option other than "All new tabs in incognito".

**Comment by csagan5** [comment] 2020-06-04 22:01
@spinoza-dat I understand this is a variant of #426; see my comment there.

> there are some cons in incognito like not being able to take screenshots.

This is not true, there is a flag for that.

**Comment by spinoza-dat** [comment] 2020-06-04 22:23
> This is not true, there is a flag for that.

@csagan5 could you please share? I can't find it, I've asked in many forums and everybody told me there are no flags for that.

**Comment by csagan5** [comment] 2020-06-04 22:25
They are all mentioned in the README: https://github.com/bromite/bromite/blob/master/README.md#flags

**Comment by spinoza-dat** [comment] 2020-06-05 04:16
@csagan5 indeed, there's no flag for taking screenshots in incognito among the ones in the README.

**Comment by spinoza-dat** [comment] 2020-06-05 04:42
Oh okay there's a new one for this. Thank you, I wouldn't have noticed without your help. And sorry if I bothered you @csagan5.
Thanks!
