### ISSUE TITLE
Abandonment

### ISSUE THREAD

**Issue by ghost** [bromite/bromite#2591] opened 2023-02-27 04:18 UTC
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

No.

### Describe the solution you would like

While I acknowledge that no one here is entitled to an app update or anything else (lets get that out of the way and be clear on it), I do believe that the thousands of users do deserve to know what is going on, and keeping us in the dark is disrespectful and cruel.

App developers, please select one of the below options that best describes the situation:

1. The app has been abandoned, do not expect any more updates, find an alternative.

2. The app will be updated in the near future (within no longer than 1 month).

3. The app is on hold indefinitly and may or may not resume in the future.

Please do not just close this as not planned until an app update is ready, because someone else will no doubt start raising the same issues and asking the same questions.

Regards

### Describe alternatives you have considered

Nil

**Comment by tinkonk** [comment] 2023-02-27 14:06
I think that this issue is disrespectful in and of itself.
Maybe something is going on in the developers' lives? Why is there no option for more than 1 month? Why is an option needed to be chosen at all? Do you pay them a salary to work on this project?
Please be patient.

**Comment by ghost** [comment] 2023-02-27 18:31
If you incorrectly think that anything I said is disrespectful, it's your own subjective right based on your life experience.

I took maximum care not to offend anyone and mention about entitlement's, etc...

I stand by every word I wrote, except to disrecectful and cruel I will also add selfish.

To answer your question, I provided options to save time of those that will be answering, seeing that they seem to be super busy and unable to tell us whats up. Also to avoid asking for any personal details/reasons and to specificly specify that we are after nothing but an ETA and a status.

To avoid this toppic getting out of hand on a sensetive issue for a lot of people, moving forward, lets keep it strictly on the subject and try to avoid "I think/he thinks/I said/you said/may be this/may be that"...

Regards.

**Comment by kontell** [comment] 2023-02-27 18:44
This is a duplicate, look at closed issues.

**Comment by ghost** [comment] 2023-02-27 18:52
The closed one is a duplicate. Auto-closed due to lack of template. This one was done properly with the template followed.

**Comment by tinkonk** [comment] 2023-02-27 19:41
> I stand by every word I wrote, except to disrecectful and cruel I will also add selfish.

Selfish how? It's a project developed in people's free time for 5 years now (at least according to the releases) with little donations (nothing wrong with this), and no commits or comments in a month is selfish?

**Comment by tinkonk** [comment] 2023-02-27 19:49
Also, if you look at #2575, you'll find some answers.

**Comment by Universalizer** [comment] 2023-02-27 20:50
Chromium works around approximately 35 million codes (some past or present 'news source', don't remember),

Now, the old codes instructions set and new upstream codes, should not conflict with each other, more careful with syntax writing and patching for privacy preserving browser,

"Software development or coding" towards right track, must not in wrong flow,

Research might be time consuming; reading relevance, understanding and implementing trial experiments. Obviously ! Focus to think over logics, concentration, patience, etc,

Take a hypothetical scenario :-

'Software A' updates frequently but mostly meaningless or unworthy.
'Software B' updates slow and steadily but effectively or maturely.

**Which one you will prefer ?**
_Software A or B ?_

Again, users will start submitting lots of new issues or problems, endless etc etc etc, it will become headaches for project maintaining and community users also,

Lastly, 
We shouldn't forget that this project is hobbyist in their free time, even time consuming and with limited resources,

Someone's goodness must not be taken for granted, (don't take disadvantage of someone's goodness), Maintain peace and harmony with each other than the environment will be positive and constructive.

One additional info :-
Android mono chrome apk, major version 110, Require SDK : minimum is 24, targeting maximum is 33.

<hr>

https://github.com/bromite/bromite/discussions/1810#discussion-3889149
> We as a community should support the open source projects and not ask the developers for any ETA's for new releases.

**Comment by DKB-91** [comment] 2023-02-27 20:57
Just wait for the devs to bd ready and use another (privacy focused if possible) browser and let the developers handle their own issues.

Compartmentalization is another key factor to privacy, and while on desktop you can use profiles, you're stuck to downloading multiple browsers on android to do so anyway. 

Putting your eggs in one basket is always an insecure practice.

You can download Uazo's beta version of Bromite or download Brave (crypto shit is annoying but what else is there?) if you want another browser for privacy related browsing with adblocking that is more up to date. (Hell I use Vivaldi for logging in sites and that is not privacy focused at all)

I doubt opening up issues after issues and discussion after discussion is going to help the devs or the people waiting anyway. 
Also they already responded nobody has quit, so as others said, just wait.

**Comment by ghost** [comment] 2023-02-27 21:26
> > I stand by every word I wrote, except to disrecectful and cruel I will also add selfish.
> 
> Selfish how? It's a project developed in people's free time for 5 years now (at least according to the releases) with little donations (nothing wrong with this), and no commits or comments in a month is selfish?

You seem to be missing the point here, all while blindly attacking anything I say.

For those that struggle to understand plain english I will chew over:

Forget the lack of app update in 3 months or the reasons for it - not once have I made an issue of it or said anything negative. Selfishness is in the fact that it only takes a minute to inform your user base about what is going on. For example:

"I will be away for the next 5 months and development will recommence around x-date".

That way users know what to expect.

The alternative is what we have now.

**Comment by ghost** [comment] 2023-02-27 21:33
> You can download Uazo's beta version of Bromite or download Brave (crypto shit is annoying but what else is there?) if you want another browser for privacy related browsing with adblocking that is more up to date. (Hell I use Vivaldi for logging in sites and that is not privacy focused at all)

A little off topic, but yeah, Uazo's version is great, except bitwarden does not work with it. Says something along the lines of "no entry found for org.chromium....."

As for Brave - you said it yourself. It's hard to downgrade to something worse.

**Comment by Poopooracoocoo** [comment] 2023-02-27 21:42
Duplicate of #2583 and #2575

**Comment by ghost** [comment] 2023-02-27 21:48
> Duplicate of #2583 and #2575

No. Please read and comprehend the full content before making such conclusions.

Far from a duplicate.

**Comment by DKB-91** [comment] 2023-02-27 21:49
> A little off topic, but yeah, Uazo's version is great, except bitwarden does not work with it. Says something along the lines of "no entry found for org.chromium....."
>

Because you saved those password to work only for Bromite and not Chromium/Uazo's beta.
Wouldn't know how to make it global/change the setting to Chromium.
I've long since abandoned Bitwarden for KeepassDX, so can't help you there.
It does the same thing to me too, when I save a password used by an app, so it mayne has to do with urls (rather than site urls it saved that password with an app url, dunno if Bitwarden Android does the same)

As for Brave, it is indeed worse, but it's updated frequently and sadly, no other Chromium browsers can hope to compare to Bromite (or Uazo's beta), so it's (sadly) the next best thing. (I just use vivaldi for logins since logging in already throws away every privacy security out of the window, and fuck Chrome)
There is Mull, but good-bye sandboxing, hello security nightmares.

**Comment by tinkonk** [comment] 2023-02-27 21:57
> "I will be away for the next 5 months and development will recommence around x-date".

I already mentioned issue #2575 and that you might find answers there. csagan has replied in that issue that nobody has quit anything.

**Comment by Universalizer** [comment] 2023-02-27 22:04
Patience is tolerant resistance, worthy, meaningful,

Patience is deed of mighty hero and bright wisdom,

Patience needs maturity,

Have peace and harmony.

**Comment by ghost** [comment] 2023-02-27 22:04
> > A little off topic, but yeah, Uazo's version is great, except bitwarden does not work with it. Says something along the lines of "no entry found for org.chromium....."
> 
> Because you saved those password to work only for Bromite and not Chromium/Uazo's beta. Wouldn't know how to make it global/change the setting to Chromium. I've long since abandoned Bitwarden for KeepassDX, so can't help you there. It does the same thing to me too, when I save a password used by an app, so it mayne has to do with urls (rather than site urls it saved that password with an app url, dunno if Bitwarden Android does the same)
> 
> As for Brave, it is indeed worse, but it's updated frequently and sadly, no other Chromium browsers can hope to compare to Bromite (or Uazo's beta), so it's (sadly) the next best thing. (I just use vivaldi for logins since logging in already throws away every privacy security out of the window, and fuck Chrome) There is Mull, but good-bye sandboxing, hello security nightmares.

Thanks for good advice, I appreciate it.

**Closed as completed** 2023-02-28 21:18 UTC
Labels: enhancement, new-account, needs-triage

**Comment by schichtnudelauflauf** [comment] 2023-03-01 17:28
So regardless of all the emotional stuff.
So is @csagan5 reachable, awol?
I want to make up my mind if its reasonable to fork and update myself or not.

Any life-shit going on where I could help?

**Comment by Universalizer** [comment] 2023-03-02 03:19
> I want to make up my mind if its reasonable to fork and update myself or not.

@AngryLasagna,

Here, this is 'general discussion only from my side', don't take it personally,

These may requires ability of software binary engineering, coding, compiling, build releases for 32-bit (armeabi-v7a) and or 64-bit (armeabi-v8a), etc

Myself, 'advanced computer user only and advanced smartphone user only' but i myself personally lack software engineering skills or talent.

**Comment by Universalizer** [comment] 2023-03-02 03:57
Software developing or engineering is depth of work, It requires 'team work' of more than three person ; that will accelerate and accomplish it easily and fast.

csagan5 and uazo here are praiseworthy, they alone do these mighty work and never complain or criticize anybody anymore.

Respect and salute to their patience and kindness. #gratitude.

**Comment by schichtnudelauflauf** [comment] 2023-03-02 04:55
My assumption was that csagan5 owns the CI and the rest of the contributors used PRs mainly.
I won't hallucinate properly maintaing a chromium mod alone.
But if the main person was somehow lost, which happens, it may need a social impulse to start working around that.

Von: Universaliser ***@***.***>
An: bromite/bromite ***@***.***>
Kopie: Angry Lasagna ***@***.***>; Mention ***@***.***>
Datum: 02.03.2023 04:58:01
Betreff: Re: [bromite/bromite] Abandonment (Issue #2591)
