### ISSUE TITLE
Color scheme shifting

### ISSUE THREAD

**Issue by AzureB1te** [bromite/bromite#851] opened 2020-12-12 11:05 UTC
Yes

### Bromite version

Version: `87.0.4280.106`
Arch: arm64
Android version: 10
Device model: (example: HD1903

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version? 
Yes

### Can the bug be reproduced with corresponding Chromium version?
 I have not encountered it,in the latest chromium version.

### Is the bug a crash?
No

### Describe the bug

Bromite randomly shifts my devices color profile. While using it,my screen is colder,and flickers between the real one,and the random coldet one.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Set an outstanding (very warm) color mode on your phone. 
2. Open Bromite and search for something,open sone websites with images. The pictures,and other website elements should look volder and flatter.

### Expected behavior

The display color configuration isn't overwritten by bromite.

### Screenshots

Here's the "proof I havel",altough it isn't the nicest representation of the issue.![Screenshot_20201212-130247__01.jpg](https://user-images.githubusercontent.com/68877792/101982153-08936280-3cc6-11eb-9368-07276f8d053a.jpg)![Screenshot_20201212-130254__01.jpg](https://user-images.githubusercontent.com/68877792/101982155-0a5d2600-3cc6-11eb-9732-0d359826c273.jpg)

**Comment by anonymix007** [comment] 2020-12-13 03:52
I think that [this](https://github.com/bromite/bromite/issues/817#issuecomment-731578149) would help.
Could you try?

**Comment by csagan5** [comment] 2020-12-13 11:43
Duplicate of #848

**Closed by csagan5** 2020-12-13 11:43 UTC
