### ISSUE TITLE
Release 83 keeps crashing

### ISSUE THREAD

**Issue by 0xAhmad** [bromite/bromite#574] opened 2020-05-14 23:49 UTC
Hi there,
I have the latest release of Bromite 83. It worked for a day then now it crashes immediately after I open it. It's downloaded from F-Droid. I have a Galaxy S8 Avtive with Android Pie, no root. I wish if there's a log file I can send but I'm not sure if there's any.

![Screenshot_20200514-194241_One UI Home](https://user-images.githubusercontent.com/32523610/81996546-4d192b80-961b-11ea-9dc3-fe262e6d3600.jpg)

**Comment by ezist** [comment] 2020-05-15 03:13
Same issue here, on a Samsung A10e with Android Pie; no root installed.

**Comment by csagan5** [comment] 2020-05-15 06:51
Duplicate of #565

**Closed by csagan5** 2020-05-15 06:51 UTC
Labels: missing-issue-template
