### ISSUE TITLE
Add flags for desktop and mobile UA strings.

### ISSUE THREAD

**Issue by DI555** [bromite/bromite#340] opened 2019-07-19 17:53 UTC
**Is your feature request related to privacy?**
Features that are not related to privacy are unlikely to be considered.
Yes. Feature to set your ua to any what you need - takes privacy! But mostly it's related to security!!!
**Is there a patch available for this feature somewhere?**
... unfortunately, no(.

**Describe the solution you'd like**
Add two flags for strings for desktop and mobile UA modes.
So, will be possible to copy-past between them to use for example desktop string ua as default (in a mobile one flag wich is defalt one).
Or place there any ua what you wish. (In security reason!!!)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you have considered.
Now browser always skips to mobile ua, but very uncomfortable always switching to desktop ua if it's common ua.

**Comment by csagan5** [comment] 2019-07-20 07:34
This is a duplicate of #337 

Re-submitting issues like this will simply make you enter the blocked users list.

**Closed by csagan5** 2019-07-20 07:34 UTC
