### ISSUE TITLE
Videos don't work

### ISSUE THREAD

**Issue by luisnogueira** [bromite/bromite#448] opened 2019-12-22 18:42 UTC
### Bromite version

Version: `79.0...`
Arch: arm64
Android version: (example: `10`)
Device model

### Is this bug about the SystemWebView?
No

No support for SystemWebView installations is provided.

### Is the bug a crash?

If yes then individuate and post the logcat dump (remove privacy sensitive information, if any), otherwise remove this section.

### Describe the bug
Video player broken on some websites.

Example:
https://abola.vsports.pt/vod/56001/m/593943/abola/f36145ebd37c494267930280c81a7f51 (start and immediately stop)

https://www.rtp.pt/play/direto/rtp1

**Comment by csagan5** [comment] 2019-12-22 20:02
Duplicate of #445

**Closed by csagan5** 2019-12-22 20:02 UTC
