### ISSUE TITLE
[Feature Request] Add an option to clear browsing data on exit

### ISSUE THREAD

**Issue by TuxKruger** [bromite/bromite#815] opened 2020-11-20 07:03 UTC
###### Description
As the title of the issue itself suggests, I am requesting for a feature to clear browsing data on exit.

###### Has any other browser implemented this feature?
Well yeah. I found this feature on Firefox Nightly( https://github.com/mozilla-mobile/fenix ) and its fork Iceraven( https://github.com/fork-maintainers/iceraven-browser ). I know that they are not chromium based browsers but they are browsers atleast.

It would be nice to see this feature (or something similar) in Bromite.

**Comment by csagan5** [comment] 2020-11-20 23:02
Please search the issue tracker before creating new issues.

Duplicate of #426

**Closed by csagan5** 2020-11-20 23:02 UTC
