### ISSUE TITLE
Permission request to access Google account on every system start

### ISSUE THREAD

**Issue by lowtrucks** [bromite/bromite#11] opened 2017-11-05 04:05 UTC
starting from version 63.0.3239.10, Bromite asks for permission to access Google account on every system start, even if Google sync is disabled in settings.

**Comment by csagan5** [comment] 2017-11-07 18:57
This needs to be confirmed with version 63.0.3239.38.

Any logs from your device? e.g. with logcat, grep for bromite-specific entries that might explain this

**Comment by csagan5** [comment] 2017-11-07 22:20
@lowtrucks can you try with the built apk here? https://github.com/bromite/bromite/releases/tag/untagged-ac1e91c0e2e4c2eb0db1

It is the next official version, but not yet available for all architectures (so if you do not have a compatible android/arch, we need to wait longer to test it)

**Comment by lowtrucks** [comment] 2017-11-15 11:00
sorry for late reply.

i just tested **63.0.3239.46**, and the problem with unneeded permission to access Google account on every start of a system is still there.

i have two phones - Android 5.1.1 and Android 7.1. this problem occurs only on Android 5.1.1.

**Comment by csagan5** [comment] 2017-11-23 08:15
@lowtrucks yes I confirm, I have also seen this. I have however no idea why...

**Comment by westsibe** [comment] 2017-11-28 12:48
In new versions of Bromite Browser impossible join to mail.google.com on Android 4.4.2, MTK6582

**Comment by JoeTvx** [comment] 2017-12-03 06:57
Seeing this on 64.0.3278.0 on Android 8.0.0 as well.

**Comment by csagan5** [comment] 2017-12-03 23:21
Perhaps it's not saving the setting.

@JoeTvx there is no such version 64.0.3278.0 of Bromite

@lowtrucks does it still happen with latest 63.0.3239.78? I made some changes regarding the first run settings.

**Comment by JoeTvx** [comment] 2017-12-06 02:47
@csagan5 screenshot attached with the version info
https://s8.postimg.org/axb1zvz6d/Screenshot_20171205-184314.png

**Comment by csagan5** [comment] 2017-12-06 07:21
@JoeTvx thanks for reporting; it is a separate bug. Apparently when no version is specified during build, it shows Chrome's version somehow. I will fix it in next release

**Comment by lowtrucks** [comment] 2018-01-27 06:48
i just updated LineageOS from **lineage-14.1-20180117-nightly-i9300-signed** to **lineage-14.1-20180124-nightly-i9300-signed** (https://download.lineageos.org/i9300), both are 7.1.

and that problem has gone (as it's non-existent my 5.1.1 device).

**Comment by csagan5** [comment] 2018-02-12 20:07
This issue might be fixed altogether when issue #31 is fixed.

**Comment by lowtrucks** [comment] 2018-02-13 00:32
i just tested **64.0.3282.149**, and permission request is still there.

**Comment by csagan5** [comment] 2018-02-13 08:08
@lowtrucks nothing changed so it's still expected to be there

**Comment by csagan5** [comment] 2018-02-18 18:37
This is fixed in v64.0.3282.168

**Comment by lowtrucks** [comment] 2018-02-19 01:49
i just tried it with **64.0.3282.168**.

sorry to report that, but permission request on every system start is still there. :(

**Comment by csagan5** [comment] 2018-02-19 19:31
@lowtrucks I cannot reproduce this. It never asks for permissions to me. What Android version and CPU type?

**Comment by lowtrucks** [comment] 2018-02-19 23:50
@csagan5,

i have two phones - Android 5.1.1 and Android 7.1.2. this problem occurs only on Android 7.1.2.

model: Samsung Galaxy S III (i9300)
CPU: 1.4 GHz quad-core Cortex-A9
OS: Android 7.1.2

**Comment by bj0rky** [comment] 2018-03-23 18:23
Account permission request nag
Bromite: 64.0.3282.204 
Android 8.1.0
CPU: Quad-core 2.3 GHz Krait 400 (arm)

**Comment by p4nci** [comment] 2018-03-26 09:12
can confirm this, BUT only in arm (32-Bit) architecture:
- Nexus 5 (arm): permanent account permission request nag
- Nexus 5X (arm64): works as expected
Both devices with LineageOS 7.1.2

**Comment by megabugman** [comment] 2018-04-05 10:40
the issue is reproducible with 65.0.3325.204 running RR 5.8.5 (Android 7.1.2).

[04-05 12:17:04.157 864:904 W/PackageManager]
Permission org.bromite.bromite.permission.DEBUG from package org.bromite.bromite in an unknown group android.permission-group.DEVELOPMENT_TOOLS

[04-05 12:17:04.572 864:864 W/PackageManager]
Not granting permission android.permission.ACCESS_COARSE_LOCATION to package org.bromite.bromite because it was previously installed without

[04-05 12:17:04.572 864:864 W/PackageManager]
Not granting permission android.permission.ACCESS_FINE_LOCATION to package org.bromite.bromite because it was previously installed without

[04-05 12:17:04.572 864:864 W/PackageManager]
Not granting permission android.permission.CAMERA to package org.bromite.bromite because it was previously installed without

[04-05 12:17:04.572 864:864 W/PackageManager]
Not granting permission android.permission.GET_ACCOUNTS to package org.bromite.bromite because it was previously installed without

[04-05 12:17:04.572 864:864 W/PackageManager]
Not granting permission android.permission.READ_EXTERNAL_STORAGE to package org.bromite.bromite because it was previously installed without

[04-05 12:17:04.572 864:864 W/PackageManager]
Not granting permission android.permission.RECORD_AUDIO to package org.bromite.bromite because it was previously installed without

[04-05 12:17:04.572 864:864 W/PackageManager]
Not granting permission android.permission.WRITE_EXTERNAL_STORAGE to package org.bromite.bromite because it was previously installed without

[04-05 12:17:04.573 864:864 W/PackageManager]
Unknown permission com.chrome.permission.DEVICE_EXTRAS in package org.bromite.bromite

[04-05 12:17:04.573 864:864 W/PackageManager]
Unknown permission com.google.android.apps.now.CURRENT_ACCOUNT_ACCESS in package org.bromite.bromite

[04-05 12:17:06.733 864:944 W/PackageManager]
Not granting permission android.permission.ACCESS_COARSE_LOCATION to package org.bromite.bromite because it was previously installed without

[04-05 12:17:06.733 864:944 W/PackageManager]
Not granting permission android.permission.ACCESS_FINE_LOCATION to package org.bromite.bromite because it was previously installed without

[04-05 12:17:06.733 864:944 W/PackageManager]
Not granting permission android.permission.CAMERA to package org.bromite.bromite because it was previously installed without

[04-05 12:17:06.733 864:944 W/PackageManager]
Not granting permission android.permission.GET_ACCOUNTS to package org.bromite.bromite because it was previously installed without

[04-05 12:17:06.733 864:944 W/PackageManager]
Not granting permission android.permission.READ_EXTERNAL_STORAGE to package org.bromite.bromite because it was previously installed without

[04-05 12:17:06.733 864:944 W/PackageManager]
Not granting permission android.permission.RECORD_AUDIO to package org.bromite.bromite because it was previously installed without

[04-05 12:17:06.733 864:944 W/PackageManager]
Not granting permission android.permission.WRITE_EXTERNAL_STORAGE to package org.bromite.bromite because it was previously installed without

[04-05 12:17:06.734 864:944 W/PackageManager]
Unknown permission com.chrome.permission.DEVICE_EXTRAS in package org.bromite.bromite

[04-05 12:17:06.734 864:944 W/PackageManager]
Unknown permission com.google.android.apps.now.CURRENT_ACCOUNT_ACCESS in package org.bromite.bromite

[04-05 12:17:19.498 409:409 W/cutils]
Expected path /data/data/org.bromite.bromite with mode 700 but found 751

[04-05 12:17:21.159 864:864 W/SyncManager]
Access to Account {name=yourname@gmail.com, type=com.google} denied for package org.bromite.bromite in UID 10089

[04-05 12:17:21.329 864:864 W/AppOps]
Bad call: specified package org.bromite.bromite under uid 1000 but it is really 10089
java.lang.RuntimeException: here
	at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1452)
	at com.android.server.AppOpsService.noteOperationUnchecked(AppOpsService.java:1116)
	at com.android.server.AppOpsService.noteOperation(AppOpsService.java:1108)
	at android.app.AppOpsManager.noteOpNoThrow(AppOpsManager.java:2061)
	at com.android.server.notification.NotificationManagerService.noteNotificationOp(NotificationManagerService.java:474)
	at com.android.server.notification.NotificationManagerService.-wrap5(NotificationManagerService.java)
	at com.android.server.notification.NotificationManagerService$EnqueueNotificationRunnable.run(NotificationManagerService.java:2880)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at com.android.server.SystemServer.run(SystemServer.java:388)
	at com.android.server.SystemServer.main(SystemServer.java:242)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

[04-05 12:17:21.329 864:864 V/NotificationService]
notifications are disabled by AppOps for org.bromite.bromite

**Comment by csagan5** [comment] 2018-04-17 07:52
Next release will contain the patch mentioned in [this XDA post](https://forum.xda-developers.com/showpost.php?p=76242418&postcount=652) and this problem should finally be fixed.

**Comment by csagan5** [comment] 2018-04-21 20:46
65.0.3325.230 fixes this issue

**Closed by csagan5** 2018-04-21 20:46 UTC
Labels: bug, help wanted
