### ISSUE TITLE
Cannot install any UserScripts. "Add script" results in crash. Opening from Downloads results in the error "Cannot open script source"

### ISSUE THREAD

**Issue by firepacket** [bromite/bromite#1928] opened 2022-03-27 07:15 UTC
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

99.0.4844.77

### Device architecture

arm64-v8a

### Android version

10

### Device model

Oneplus 7 Pro

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

2. Yes, I have attached the crash report dump that I downloaded from chrome://crashes with Bromite version 99.0.4844.77

[2671f3d2-e5d5-4622-a231-674acecb13f2.zip](https://github.com/bromite/bromite/files/8357068/2671f3d2-e5d5-4622-a231-674acecb13f2.zip)

### Describe the bug

1.  When I try to add a userscript by going into "Settings -> Userscripts -> Add script" the application crashes and I have attached the log of this crash.

2. When I try to add a userscript by opening a user.js file from Downloads I get the error in a toast: "Cannot open script source" but the application does not crash. **The download IS downloaded and I can find the download in my Download folder**

### Steps to reproduce the bug

I simply downloaded and installed the Bromite apk from this website and attempted to install ANY userscript by both methods I described above which resulted in either a crash or an error toast message.

The script is downloaded and present in my Download directory when I execute it from Downloads in Bromite and receive an error. There is no chance for me to even select a script before Bromite crashes when clicking "Add script".

### Expected behavior

I should be able to install new user.js userscripts by using the "Add script" button or executing it from the Downloads page.

### Screenshots

Trying to Install script from Downloads:

![1](https://user-images.githubusercontent.com/3860274/160270903-7c114c53-ed0a-4906-9942-71ccc28e867e.jpg)

![2](https://user-images.githubusercontent.com/3860274/160270906-99ded602-ea2e-4bfb-bcc3-82dc888ad933.jpg)

Trying to Install script with 'Add Script':

![3](https://user-images.githubusercontent.com/3860274/160270913-ed7f23a4-00a2-490d-8685-96e4a8378027.jpg)

**Comment by JustAnUserLol** [comment] 2022-03-28 14:44
I am not able to reproduce this.

**Comment by csagan5** [comment] 2022-03-28 15:10
Duplicate of #1926.

@firepacket please see comments on the other issue

**Closed by csagan5** 2022-03-28 15:10 UTC
Labels: bug, needs-triage
