### ISSUE TITLE
Scrolling stutter

### ISSUE THREAD

**Issue by 0rlaf** [bromite/bromite#209] opened 2018-12-30 13:21 UTC
Bromite version

Version: 71.0.3578.110
Arch: arm64
Android version: Pie

Is the bug reproducible with latest version?
- Yes

Can the bug be reproduced with corresponding Chromium version?
- No

Is the bug a crash?
- No

Describe the bug:

- Stuttering during page scrolling

- Go to any site. 
- Start to scroll page up and down. 
- Sometimes tiny freeze (stutter) happen. 

Expected behavior
- Expected a constant framerate.

**Comment by csagan5** [comment] 2018-12-30 14:57
Duplicate of #203

**Closed by csagan5** 2018-12-30 14:57 UTC
Labels: duplicate
