### ISSUE TITLE
Help to generate adblock_entries.h

### ISSUE THREAD

**Issue by pceiley** [bromite/bromite#114] opened 2018-08-25 04:44 UTC
**Is your feature request related to privacy?**
Indirectly

**Is there a patch available for this feature somewhere?**
No

**Describe the solution you'd like**
Are you able to share scripts or code in order to generate the adblock_entries.h file?

**Describe alternatives you've considered**
I'm toying with a project at the moment using your adblock engine - but I'd like to adapt it with a different set of filters.  It would save me some time if you could share your code/method to generate the file?

**Comment by csagan5** [comment] 2018-08-25 12:50
@pceiley this repository is about Bromite and I do not support building-related issues/questions.

The code to parse the adblock entries will be released with #2, sorry I am not publishing it until that.

**Closed by csagan5** 2018-08-25 12:50 UTC

**Comment by nikolowry** [comment] 2018-12-15 22:30
> I do not support building-related issues/questions.

Why @csagan5? 

I do respect the narrow scope you keep with the project, but it be nice to have a little guidance (read any documentation or bash examples) on applying your patch set, filters and GN flags.

Some of us want to make modifications outside of your scope, but also want to respect your rules on reporting issues -- having some build related docs/examples could potentially thwart what you see as issue spam.

I'm one of these people too, I do my own builds for the sole purpose of killing the white nav bar since the MD refresh

**Comment by csagan5** [comment] 2018-12-16 10:42
@nikolowry if one publishes docs/examples about building, then he/she has to support users trying to use them. My time is limited and I cannot do that, sorry.

Also you can easily imagine that the support would be 99% about building Chromium for the majority of users trying this, that is why I decided against this; building Chromium is unfortunately not a piece of cake (and probably will never be, given the target audience).

I keep releasing everything as open source via GNU GPL license v3 so that if there are improvements hopefully they will be contributed back (never happened so far), and for the longevity of the project itself.

The original GN flags I used (11 months ago now) is here: https://github.com/bromite/bromite/blob/for-fdroid/fdroid/GN_ARGS

I will consider publishing the GN flags. As for the adblock entries generation, I hope to cover soon this with the release of the whole code for #2 (it's a work in progress).

> having some build related docs/examples could potentially thwart what you see as issue spam.

Issue spam is there simply because users want a finely tailored browser, including UI and non-privacy-related features; this project is really not about that. They should probably ask to Brave developers to bring that to them (might be more on topic); Brave is also open source and the build process better documented (and maybe even supported on their forums?), I doubt people submitting issue spam even know about Brave or Chromium; having just-registered users that post issues without much thought is a more general issue of Github and probably cannot be solved by moving to Gitlab (although the issue template problem on mobile would be).

> I do my own builds for the sole purpose of killing the white nav bar since the MD refresh

Sorry, what are the white nav bar and the MD refresh? Are these bugs in Chromium/Bromite?

**Comment by nikolowry** [comment] 2018-12-17 19:18
@csagan5 appreciate it the fast answer. Adding that explanation to the README would be beneficial for users like myself -- I literally was opening every issue (opened/closed) to find one with appropriate comments to reply to.

I'm patching the white navigation bar that was originally introduced in the new Material Design refresh. The issue has an open ticket at [797527 - White Android navigation bar is too distractive on dark-themed sites](https://bugs.chromium.org/p/chromium/issues/detail?id=797527&q=white%20nav%20bar&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).

Here's an image from that issue, the left is pre-MD refresh and what my patch reverts the UI to and the right is the current UI:
![white-nav-bar-example](https://user-images.githubusercontent.com/597310/50109426-c84b9780-0205-11e9-8d4e-c8b2e71053d7.jpeg)

I hadn't planned on making a pull request per [Can you add dark mode/some cool themes](https://github.com/bromite/bromite/blob/master/README.md#can-you-add-dark-modesome-cool-themes).   I could argue the patch is not just UI related, but performance related for users with an AMOLED screen -- but I understood from that section of the README is that you are only interested in privacy and ad-block related patches, so I wasn't even going to bother

**Comment by csagan5** [comment] 2018-12-17 20:11
> @csagan5 appreciate it the fast answer. Adding that explanation to the README would be beneficial for users like myself -- I literally was opening every issue (opened/closed) to find one with appropriate comments to reply to.

I am sorry for the struggle; this is the current build section of the README: https://github.com/bromite/bromite#how-to-build

> # How to build
> 
> The [Bromite main repository](https://github.com/bromite/bromite) contains tags for each corresponding Chromium release (see https://chromium.googlesource.com/chromium/src.git).
> 
> Please refer to [official Chromium build documentation](https://www.chromium.org/developers/how-tos/get-the-code) to get started on how to build Chromium; if you can build Chromium for Android, you can build Bromite.
> 

How would you change it? You can also make a PR and I will adjust it as needed. I will mention the GN flags after starting to publish them.

> Here's an image from that issue, the left is pre-MD refresh and what my patch reverts the UI to and the right is the current UI:
>

I had noticed this change but I thought it was an Android change; I have read on the upstream issue that you have tried to dig more into it. It indeed looks ugly (and Matt Damon in there as well, but I digress).

> I hadn't planned on making a pull request per [Can you add dark mode/some cool themes](https://github.com/bromite/bromite/blob/master/README.md#can-you-add-dark-modesome-cool-themes). I could argue the patch is not just UI related, but performance related for users with an AMOLED screen -- but what I understood from that section of the README is that you are only interested in privacy and ad-block related patches, so I wasn't even going to bother

That F.A.Q. is to (try to) avoid the off-topic feature requests, but generally I have said in the past (XDA forums, reddit) that the biggest problem with non-privacy patches is that I would not have interest/commitment to maintain them.

If you can submit a patch that builds against v71 and does not cause issues I will be glad to integrate it; I will even try to port it to v72 when the time comes and then eventually notify you if it does not.

Now we have officially gone off-topic for this issue :blush: please open a separate issue and/or PR if you wish to proceed with the submission; the part about improving the README we can keep discussing here.

**Comment by nikolowry** [comment] 2018-12-17 20:57
@csagan5 how about this: 

**Building Documentation**
The next time I do a build (this week, latest this weekend) I will convert my local bash scripts to a personal repo named `bromite-builder`, document the steps I took in creating it and retrofit those documented steps to a generic "Building Bromite from source".

I'll then submit a PR towards the README or Wiki and you can decide then if you think it will be useful enough to accept. In the PR, I'll also link to my newly created `bromite-builder` repo for you to review with it.

I'll preface the build documentation with a note/disclaimer stating: "Building from source is not explicting supported, the following should only be used as a guide when building Bromite from source. Do note that APK's from custom builds will retain the Chromium branding and Chromium namespacing".

**Nav Bar Patch**
I'll use the next build to verify the patch is still working as intended and create a seperate PR for it.

---

Thanks for taking the time for having this aside with me!

**Comment by csagan5** [comment] 2018-12-17 21:07
> **Building Documentation**
> The next time I do a build (this week, latest this weekend) I will convert my local bash scripts to a personal repo named `bromite-builder`, document the steps I took in creating it and retrofit those documented steps to a generic "Building Bromite from source".
> 
> I'll then submit a PR towards the README or Wiki and you can decide then if you think it will be useful enough to accept. In the PR, I'll also link to my newly created `bromite-builder` repo for you to review with it.
> 
> I'll preface the build documentation with a note/disclaimer stating: "Building from source is not explicting supported, the following should only be used as a guide when building Bromite from source. Do note that APK's from custom builds will retain the Chromium branding and Chromium namespacing".

I am sorry, this still would not work; but free free to host that repository on your user's Github. I am still waiting for somebody to submit a working Chromium variant to F-Droid and I kinda stopped my contributions for an automated build there (read #4 and the related Gitlab issues for more information). For the foreseeable future I have no interest to support users trying to build Chromium/Bromite; I can only guarantee that the patches - applied in order - will apply correctly, as that is the bulk of the maintenance work I do every time there is a major Chromium release.

> **Nav Bar Patch**
> I'll use the next build to verify the patch is still working as intended and create a separate PR for it.
> 
> Thanks for taking the time for having this aside with me!

You're welcome; the GN args will be published with next release of Bromite but I gave a look to [those in use for Brave](https://github.com/brave/browser-android-tabs/tree/master/scripts/gn) and they are not much different (nothing secret as well).

**Comment by nikolowry** [comment] 2018-12-17 21:22
@csagan5 sounds good!

**Comment by csagan5** [comment] 2018-12-19 08:36
@nikolowry with latest release the GN flags have been published: https://github.com/bromite/bromite/blob/master/GN_ARGS
