### ISSUE TITLE
Crash when attempting to login into Twitter

### ISSUE THREAD

**Issue by 2052001** [bromite/bromite#1902] opened 2022-03-19 10:17 UTC
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

99.0.4844.58

### Device architecture

armeabi-v7a

### Android version

10

### Device model

RMX2185

### Changed flags

No flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

Yes , its a crash but , app not showing , its automatically force stops at that point. Neither any notification popups saying about any crashlogs

### Describe the bug

Bromite crashes or force stops automatically when i try to sign in twitter website. 

Also one issue I'm facing it is that , its shows wrong info in about section. My device is RMX2185 but its showing it as a samsung device

### Steps to reproduce the bug

1. Go to Twitter.com
2. Selecting sign up (already has a account)
3. Entering the details
4. Pressing sign up then crashes Bromite

### Expected behavior

It should log my account in Twitter.com

### Screenshots

![Screenshot_2022-03-19-15-46-25-65_ed7821ed99ee442dec4ede205e7971d6](https://user-images.githubusercontent.com/93777145/159117078-aa9dcd32-f688-4e5d-873a-e9b642ac0bd3.jpg)

**Comment by 2052001** [comment] 2022-03-19 10:18
My Device Name is RMX2185 , but it shows it as a Samsung Device. 
Before updating to latest version everything was working fine along with info tab also.

**Comment by csagan5** [comment] 2022-03-19 10:47
If it is a crash then please attach the crash log; when submitting an issue you have 3 options:
> ## Is the issue a crash?
1. No.
2. Yes, I have attached the crash report dump that I downloaded from chrome://crashes
3. Yes, I have copy/pasted the crash dump
> Drag the crash report dump here to attach it or paste the logcat dump individuated with `adb logcat | grep chromium`.

**Comment by 2052001** [comment] 2022-03-19 11:52
> If it is a crash then please attach the crash log; when submitting an issue you have 3 options:
> 
> > ## Is the issue a crash?
> 
> 1. No.
> 2. Yes, I have attached the crash report dump that I downloaded from chrome://crashes
> 3. Yes, I have copy/pasted the crash dump
> 
> > Drag the crash report dump here to attach it or paste the logcat dump individuated with `adb logcat | grep chromium`.

"Well this is what i got when i visited chrome://crashes"

[a3144008-f092-46e4-a27c-b19255904f13.zip](https://github.com/bromite/bromite/files/8309121/a3144008-f092-46e4-a27c-b19255904f13.zip)

**Comment by csagan5** [comment] 2022-03-19 16:22
@2052001 please reproduce it with latest version and attach the crash generated with that version.

**Comment by csagan5** [comment] 2022-03-19 20:02
This seems to be caused by the missing `AutoSigninFirstRunDialog` class.

**Comment by 2052001** [comment] 2022-03-20 06:31
> @2052001 please reproduce it with latest version and attach the crash generated with that version.

Tried on the latest version v99.0.4844.77
Again the results are same , and about info is also showing wrong.

I tried to login both through google account as well as through username-password. but results are still the same , it redirects again on login page.

Also My device is RMX2185 not , Samsung

Video Recording of login through google account is attached below 

https://user-images.githubusercontent.com/93777145/159150980-7ac4fc21-35d1-4cdb-9063-04aa550f27e8.mp4

**Comment by csagan5** [comment] 2022-03-24 08:39
> Tried on the latest version v99.0.4844.77
> Again the results are same

Please attach the crash dump generated with latest version.

**Comment by 2052001** [comment] 2022-03-26 06:59
> > Tried on the latest version v99.0.4844.77
> > Again the results are same
> 
> Please attach the crash dump generated with latest version.

Eventually it shows 0 crash report , in chrome://crashes on the latest version , Though the problem is still the same , when trying to login in twitter, it just refresh the page when credentials are filled or login through google  , just like in previous recording i have shared
![Screenshot_2022-03-26-12-29-10-07_ed7821ed99ee442dec4ede205e7971d6](https://user-images.githubusercontent.com/93777145/160228707-9d1122c3-7521-4734-91cd-6589e041529e.jpg)

![Screenshot_2022-03-26-12-26-10-55_ed7821ed99ee442dec4ede205e7971d6](https://user-images.githubusercontent.com/93777145/160228679-d578eb6d-86ea-482b-aa53-0d81fd5f33db.jpg)

**Comment by csagan5** [comment] 2022-03-26 15:47
> Eventually it shows 0 crash report , in chrome://crashes on the latest version

In this case then please submit log lines you can see with `adb logcat` which are relevant to the crash.

**Comment by csagan5** [comment] 2022-03-29 21:38
Fixed in `100.0.4896.57`.

**Closed by csagan5** 2022-03-29 21:38 UTC
Labels: bug, needs-triage
