### ISSUE TITLE
All connections blocked (AdBlock filters problem)

### ISSUE THREAD

**Issue by cdysthe** [bromite/bromite#26] opened 2018-01-11 18:23 UTC
v63.0.3239.129 will not load pages on my Moto G5 Plus running Android 7. The previous build runs without problems. With the latest build I just get connection error asking me to check the network connection.

**Comment by andrin55** [comment] 2018-01-12 07:20
I'm running 65.0.3310.0 on Android 8 Oreo on OnePlus5 and I have the exact same issue. I get Connection Refused on every webpage except when I do a Google Search via the searchbar. The normal Google Chrome works without any issues on the same phone. All other Apps seem to have Internet Access too.

**Comment by csagan5** [comment] 2018-01-15 15:03
I have individuated this problem, as explained in [this comment](https://github.com/bromite/bromite/issues/4#issuecomment-357524931) it was due to an invalid adblock filter found in the EasyPrivacy list. I have added a test for this now and in upcoming 63.0.3239.144 the problem is fixed.

**Comment by csagan5** [comment] 2018-01-17 19:23
It is fixed in 63.0.3239.144, already released.

**Closed by csagan5** 2018-01-17 19:23 UTC
Labels: bug
