### ISSUE TITLE
Shortcut to Clear all Data

### ISSUE THREAD

**Issue by tothecorr** [bromite/bromite#321] opened 2019-06-16 21:36 UTC
**Is your feature request related to privacy?**
Yes, this feature would ease the process of cleaning all personal data off of the browser which would prevent others from snooping on your browsing data

**Is there a patch available for this feature somewhere?**
Both the DuckDuckGo browser and Firefox Focus have this feature. In fact this feature already exists in Bromite/Chromium, it is just hidden behind three menus. 

**Describe the solution you'd like**
I would like some kind of shortcut to the "Clear all data" button that is within Settings > Privacy > Clear browsing data > Clear Data. This shortcut could sit in the 3-dot menu as it should be easily accessible to promote constant purging of personal data.

**Describe alternatives you've considered**
I cannot think of any alternatives as this feature is already in chromium I am just looking for a convinent shortcut.

Thank you for amazing app you have created.

**Comment by csagan5** [comment] 2019-06-18 06:15
> This shortcut could sit in the 3-dot menu as it should be easily accessible to promote constant purging of personal data.

Why would Bromite want to promote this "constant purging of personal data"? The correct way to defend your privacy is to not store history in first place. You can enable always-incognito mode.

It has been discussed a bit in #224, I can see that some users would want to have history until they close the browser, however on Android there is no "closing" of an app unless you force-terminate it.

Duplicate of #224.

**Closed by csagan5** 2019-06-18 06:15 UTC
