### ISSUE TITLE
Tab crashing when play hd mp4 videos

### ISSUE THREAD

**Issue by sahilneal** [bromite/bromite#489] opened 2020-02-13 20:24 UTC
### Bromite version

Version: 79.0.3945.139
Arch: arm64
Android version: 10
Device model: TA

Dear Dev every time its failed to play mp4 in youtube its crashed nd youtube shows error code even browser shows crashing pop ups to close the browser or app info link nd that error showing in google search also where some youtube videos showing on search results when those embedded video on google search try to play for preview. Facing this problem since 79.0.3945.139 to 80.* only in android 10 Q but work flawlessly in other android version like 9, 8, 7
Kindly fix it asap

### Is this bug about the SystemWebView?
No

No support for SystemWebView installations is provided.

### Is the bug reproducible with latest version?

Do not report bugs which are not reproducible with latest version

### Can the bug be reproduced with corresponding Chromium version?

Please pick the same version of Chromium as Bromite from here: https://github.com/bromite/chromium/releases
If the bug is reproducible then it might be a configuration issue or an upstream bug. Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first.

### Is the bug a crash?

If yes then individuate and post the logcat dump (remove privacy sensitive information, if any), otherwise remove this section.

### Describe the bug

Write here a clear and concise description of the bug.

### Screenshots

If applicable, add screenshots to help explain your problem. Otherwise remove this section.

**Comment by csagan5** [comment] 2020-02-13 20:29
Duplicate of #445

**Closed by csagan5** 2020-02-13 20:29 UTC

**Comment by csagan5** [comment] 2020-02-13 21:27
@sahilneal the issue you submitted is a duplicate of #445 which is pinned, you can see it on top of all issues before submitting new ones. The workaround is to enable the chrome flag `#disable-accelerated-video-decode`.
