### ISSUE TITLE
DoH not working

### ISSUE THREAD

**Issue by Techguyprivate** [bromite/bromite#139] opened 2018-09-26 16:36 UTC
**Bromite version**

Version: `69.0.3497.109
Arch: `arm` and `arm64` 
Android version: Lollipop, Oreo

**Is the bug reproducible with latest version?**
 Yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No. Chromium hasn't a DoH option.

**Is the bug a crash?**
No.

**Describe the bug**
Dns over HTTPS is not working . Checked on at least three different Phone model,network.

**To Reproduce**
1. Go to any dnstest website. For example, dnsleaktest.com
2. Click on  Standard test.
3. Check the results.

**Expected behavior**
The dnsleak result should show either cloudflare or google according to settings.

**Comment by csagan5** [comment] 2018-09-26 18:44
`69.0.3497.91` also affected.

**Comment by csagan5** [comment] 2018-09-28 23:53
I verified that it has been broken since release `69.0.3497.73`.

**Comment by iamrohanbro** [comment] 2018-09-30 13:54
@csagan5 I've tested on dnsleaktest.com and the result is, its showing only "cloudflare" like the expected behavior when using 69.0.3497.91. Now only updated to 113. But I use cloudflare DNS & DNScrypt proxy 2 magisk module. Is that the reason I'm not facing the issue?

**Comment by csagan5** [comment] 2018-09-30 19:16
@iamrohanbro yes

**Comment by fitittome** [comment] 2018-10-01 18:48
Can confirm same issue on LineageOS 15.1.

**Comment by csagan5** [comment] 2018-10-17 16:39
Fixed in `70.0.3538.67`.

**Closed by csagan5** 2018-10-17 16:39 UTC
Labels: bug

**Comment by Techguyprivate** [comment] 2018-10-17 17:46
Working  on version 70, confirmed.  Awesome.Thank you. You seem to quite good at what are you doing.Will you join me on some project. There will be handsome salary.

**Comment by Techguyprivate** [comment] 2018-10-17 17:52
Logo changed?
