### ISSUE TITLE
Initial page chrome://blank is an invalid url

### ISSUE THREAD

**Issue by arnauvp** [bromite/bromite#517] opened 2020-04-02 13:32 UTC
### Bromite version

Version: `81.0.4044.83`
Arch: `arm64`
Android version: (`8.1` and `6.1`)
Device model: (`SM-G960F` and others)

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?
No, it seems to come from a patch in Bromite

### Is the bug a crash?
No

### Describe the bug

Default home page URL seems to be invalid.

### Steps to reproduce the bug

1. Install Bromite from F-Droid
2. Open Bromite
3. See the error: "This site can't be reached"

I understand this is too obvious and the fact that nobody reports this is because I am missing something...

### Expected behavior
Initial page could be `UrlConstants.NTP_NON_NATIVE_URL` as it is in [Chromium](https://chromium.googlesource.com/chromium/src/+/refs/tags/82.0.4085.1/chrome/android/java/src/org/chromium/chrome/browser/partnercustomizations/HomepageManager.java#140), but [some patch ](https://github.com/bromite/bromite/blob/master/build/patches/Add-option-to-use-home-page-as-NTP.patch#L58) seems to override that value.

**Full disclaimer:** I work for the /e/ Foundation. We would provide a PR with the change we think fixes the problem but since we don't have the whole context for the patch above we open the ticket as a request for clarification. We see this problem in stock Android as well.

### Screenshots

![bromite_blank](https://user-images.githubusercontent.com/1090103/78254439-35b43200-74f6-11ea-815d-ecbb6bebbe4e.png)

**Comment by csagan5** [comment] 2020-04-02 21:10
> Steps to reproduce the behavior:

I cannot reproduce this issue using an `x86` device. It is reproducible with `arm64` for some reason. `chrome://blank` also fails as an URL on Chromium `arm64`, while on `x86` it acts as `about:blank` (both for Bromite and Chromium).

To reproduce it without a fresh installation (for Bromite or Chromium) it is sufficient to enable the home page and make sure the URL is `chrome://blank/`; it is not needed to enable the flag to use the home page for the new tab page. I can see another UI glitch happening with this setup: it's not possible to press back on Settings and return to the tabs view as the UI seems to freeze.

Since same issues happen when setting the URL to `chrome://blank/` in Chromium I conclude that it is an upstream problem, feel free to report it there.

As a workaround you could use `about:blank` instead of `chrome://blank/` but it will not solve the frozen UI issue when returning from Settings.

**Comment by arnauvp** [comment] 2020-04-03 10:21
Hi Carl,

thanks for looking into this. I don't see `chrome://blank/` in `chrome://chrome-urls/`, hence I think it is (no longer?) a valid URL. Which would explain why setting it in Chromium also "causes the issue". But that project doesn't set that value by default, the patch I pointed to in Bromite does. So I think a safer value for the Homepage should be set in Bromite. I would suggest it's `UrlConstants.NTP_NON_NATIVE_URL` as it is in Chromium, but I don't know if that breaks whatever the patch is trying to achieve.

**Comment by csagan5** [comment] 2020-04-03 13:59
> Which would explain why setting it in Chromium also "causes the issue".

Except on x86, where it shows a blank page; however I suspect it is failing there as well, just without showing the error.

`chrome://blank/` seems a remnant and it's used only in tests.

The other UI issues might all be due to that part of the patch; it was introduced to allow people using a blank page without NTP icons as home page. It can be safely removed and `about:blank` can be typed in as needed.

The reason it's there is because without it even if you disable "set NTP as homepage" it would still show the new tab page with that default.

I think the whole patch can be removed.

**Comment by arnauvp** [comment] 2020-04-03 17:31
OK I will try that next week and let you know!

**Comment by csagan5** [comment] 2020-04-08 07:58
Fixed in `81.0.4044.97`.

**Comment by arnauvp** [comment] 2020-04-08 15:25
Unfortunately, same problem on that version. I saw the changelog entry in the commit but [no patch removed](https://github.com/bromite/bromite/commit/3c9c050df0306435f06bd928ec18a407a5972436#diff-89bd815a2b83d29ab52328e5565d7d6bL4342).

On my side, I did a [test build](https://gitlab.e.foundation/e/apps/browser/-/commit/592996d63c6b810074d09e4fe5f9cb02cb098f65) removing the `Add-option-to-use-home-page-as-NTP.patch` from
`build/bromite_patches_list.txt` and it seemed to work. I could not reproduce the freeze even after entering the invalid URL manually. I wanted to do some more checks with users before reporting but saw that you had closed the issue.

**Comment by csagan5** [comment] 2020-04-08 18:14
It was left in by mistake; it will be removed in next release.

**Comment by csagan5** [comment] 2020-04-16 07:10
Fixed in `81.0.4044.106`.

**Closed by csagan5** 2020-04-16 07:10 UTC

**Comment by csagan5** [comment] 2021-11-07 10:54
We might re-introduce the patch to allow #1519.
