### ISSUE TITLE
Minimum TLS version is not enforced

### ISSUE THREAD

**Issue by Michalko589** [bromite/bromite#645] opened 2020-07-16 22:39 UTC
### Bromite version

Version: 84.0.4147.90
Arch: arm64
Android version: 9.0
Device model: Galaxy S8

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

Chromium 84 should enforce TLS 1.2 as the minimum TLS version supported. It works correctly on Chrome for Android, however it's not enforced on Bromite. It doesn't even work with legacy-tls-enforced flag enabled.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to https://tls-v1-0.badssl.com:1010/
2. Site is loaded

### Expected behavior

There should be a fullscreen security warning.

**Comment by csagan5** [comment] 2020-07-17 07:26
> ### Can the bug be reproduced with corresponding Chromium version?
> No

Chromium shows the same behavior.

> It works correctly on Chrome for Android

As explained in the issue template, you need to refer to the corresponding Chromium version.

All v84 I have tried show the same behavior. Is it possible that your `LegacyTLSEnforced` feature is enabled because of some experiment flag?

**Comment by Michalko589** [comment] 2020-07-17 09:45
Yeah, sorry, at first I tested Chrome for Android instead of the Chromium build. 

I did some more testing. On my phone, in Chrome, TLS 1.0 && TLS 1.1 won't load, even with default settings. I also tested a different phone and TLS 1.0 did load. I'm thinking staged rollout. So it's not Bromite bug as I suspected but perhaps Bromite should enforce it?

However, there is a bug in upstream for sure. Enabling legacy-tls-enforced does work as it should in Chrome for Android, however, enabling legacy-tls-enforced in Chromium/Bromite has no effect.

**Comment by csagan5** [comment] 2020-07-17 10:36
See last comments in https://bugs.chromium.org/p/chromium/issues/detail?id=896013

They probably enabled a field trial for you; with my tests nothing happens on Chrome/Chromium for Android.

Feature flags have no effect on all Chromium variants and that's an upstream bug (or possibly intended behavior).

I will check what can be done in Bromite but from my tests I conclude it's impossible to see those warnings unless you have been assigned the right field trials.

**Comment by csagan5** [comment] 2020-07-17 11:04
From what I understand the warnings seem to be limited to a list of sites, I will disable this in Bromite in next release.

**Comment by csagan5** [comment] 2020-07-17 14:09
Fixed in `84.0.4147.95`.

**Closed by csagan5** 2020-07-17 14:09 UTC
Labels: upstream
