### ISSUE TITLE
sometimes it shows https is not supported on some sites, but the site support https

### ISSUE THREAD

**Issue by JustAnUserLol** [bromite/bromite#1648] opened 2021-12-12 09:54 UTC
Have you read the README? 
Yes

Have you searched the issue tracker?
Yes

Are you sure this is not a Chromium bug? 
Yes

Are you using the latest version of Bromite?
Yes

### Bromite version
Version: `96.0.4664.54`
Arch: `arm`
Android version: `8.1`
Device model: `Samsung Galaxy J2 Core J260G`

### Flags

These are the flags changed under `chrome://flags`: offline-indicator-v2, disallow-doc-written-script-loads, cross-origin-embedder-policy-credentialless, cleartext-permitted

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is this bug happening in an incognito tab?
Yes

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?
No

### Describe the bug
*sometimes it shows https is not supported on some sites, but the site support https, i face this bug on mostly m.youtube.com and sometimes on search.albony.xyz*

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to m.youtube.com and search.albony.xyz
2. See error

### Expected behavior
There should be not error like “this site doesn't support https” because m.youtube.com and search.albony.xyz support https

### Screenshots
![Screenshot_20211212-150925](https://user-images.githubusercontent.com/95953932/145707767-461e2016-830b-4b00-b7c2-3e0ffa23d23d.jpg)

**Comment by coxackie** [comment] 2021-12-13 09:12
I can confirm that I see this message relatively often. Usually, upon refresh of the page, it disappears and the page loads normally. Not sure how helpful this info may be.

**Comment by sgr28** [comment] 2021-12-14 18:55
I can confirm the issue as well as the fix mentioned by coxackie. However, I once had to disable "Always use secure connections" settings to access deviceinfo.me website. As an extra info, I use NextDNS as a system wide private DNS provider.

**Comment by TheAnonymous88** [comment] 2021-12-15 05:59
I only faced this bug in 96.0.4664.54

**Comment by uazo** [comment] 2021-12-15 07:35
I think it's an upstream bug, I found the same behavior in chromium vanilla.

**Comment by TheAnonymous88** [comment] 2021-12-15 08:06
> I think it's an upstream bug, I found the same behavior in chromium vanilla.

i can't reproduce it in Chromium, on my device

**Comment by uazo** [comment] 2021-12-15 08:10
can you indicate the url?

**Comment by TheAnonymous88** [comment] 2021-12-15 08:49
> can you indicate the url?

m.youtube.com and sometimes on search.albony.xyz

**Comment by uazo** [comment] 2021-12-16 08:10
> I think it's an upstream bug, I found the same behavior in chromium vanilla.

ok, you are right, it is not.

can i ask you if you have javascript disabled?
can you try with javascript enabled?

**Comment by TheAnonymous88** [comment] 2021-12-16 08:38
> > I think it's an upstream bug, I found the same behavior in chromium vanilla.
> 
> ok, you are right, it is not.
> 
> can i ask you if you have javascript disabled? can you try with javascript enabled?

i dont disable javascript

**Comment by uazo** [comment] 2021-12-16 08:43
> worked after enabling javascript

perfect, I have no idea why, I'll investigate

**Comment by TheAnonymous88** [comment] 2021-12-16 08:55
> perfect, I have no idea why, I'll investigate
Thx

**Comment by TheAnonymous88** [comment] 2021-12-16 08:56
> > worked after enabling javascript
> 
> perfect, I have no idea why, I'll investigate

Thx

**Comment by TheAnonymous88** [comment] 2021-12-16 08:58
> > worked after enabling javascript
> 
> perfect, I have no idea why, I'll investigate

there is also an bug related to this, if i try disabling javascript then go to m.youtube.com, and click on continute to site, it shows “ERR_TOO_MANY_REDIRECTS”

**Comment by uazo** [comment] 2021-12-16 09:52
> perfect, I have no idea why, I'll investigate

@csagan5 it's because of the Inject-scripts-for-AMP-tracking-ads-and-video.patch
injects javascript even if it is not enabled.

what do we do, remove it in favor of userscript? do I fix it?

> there is also an bug related to this, if i try disabling javascript then go to m.youtube.com, and click on continute to site, it shows “ERR_TOO_MANY_REDIRECTS”

that's a chromium bug, the same thing happens there too

**Comment by TheAnonymous88** [comment] 2021-12-16 10:00
> @csagan5 it's because of the Inject-scripts-for-AMP-tracking-ads-and-video.patch injects javascript even if it is not enabled.
> 
> I think User Script is better

**Comment by TheAnonymous88** [comment] 2021-12-16 10:01
> > perfect, I have no idea why, I'll investigate
> 
> @csagan5 it's because of the Inject-scripts-for-AMP-tracking-ads-and-video.patch injects javascript even if it is not enabled.


I Think UserScript would be better

**Comment by TheAnonymous88** [comment] 2021-12-19 12:57
i can confirm that i'm seeing “this site is not secure” even if i enable javascript

**Comment by coxackie** [comment] 2021-12-19 13:42
I also do not recall having javascript disabled at any point, so it must be enabled. I still see “this site is not secure”.

**Comment by uazo** [comment] 2021-12-19 14:14
>  I still see “this site is not secure”

as already written, it is an upstream bug. try the same thing in chromium.

**Comment by TheAnonymous88** [comment] 2021-12-19 14:55
> 

i ne

> > I still see “this site is not secure”
> 
> as already written, it is an upstream bug. try the same thing in chromium.

i never faced this bug in chrome (i know chromium is different but still chromium is engine for chrome).

**Comment by uazo** [comment] 2021-12-19 15:01
> i never faced this bug in chrome

this is chromium:
![1](https://user-images.githubusercontent.com/29201891/146679667-d39c25f9-b991-4d23-8fae-0ac4f6fd0aac.gif)

**Comment by TheAnonymous88** [comment] 2021-12-19 16:17
> > i never faced this bug in chrome
> 
> this is chromium: ![1](https://user-images.githubusercontent.com/29201891/146679667-d39c25f9-b991-4d23-8fae-0ac4f6fd0aac.gif)

I didn't faced it though :^, how to report chromium bugs.

**Comment by uazo** [comment] 2021-12-19 16:20
> how to report chromium bugs.

you can use https://bugs.chromium.org/p/chromium/issues/list

**Comment by csagan5** [comment] 2021-12-21 18:49
> it's because of the Inject-scripts-for-AMP-tracking-ads-and-video.patch injects javascript even if it is not enabled.
> 
> what do we do, remove it in favor of userscript? do I fix it?

It might take some work to convert it to an user script; is it still doing anything useful? There is still #732 open and AMP should start to disappear in next year. Alternative is to not inject it if Javascript is disabled; same for the other injected scripts.

**Comment by TheAnonymous88** [comment] 2021-12-23 18:42
> > how to report chromium bugs.
> 
> you can use https://bugs.chromium.org/p/chromium/issues/list

reported the bug to upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1282375#makechanges

**Comment by ASTechnical** [comment] 2022-01-07 20:33
@uazo @csagan5 the needs-triage label should be removed, because it's reproducable.

**Comment by csagan5** [comment] 2022-01-29 08:52
> @csagan5 it's because of the Inject-scripts-for-AMP-tracking-ads-and-video.patch
> injects javascript even if it is not enabled.

@uazo how does it practically cause the failure? If Javascript is not enabled then the `<script>` tags would be ignored?

**Comment by uazo** [comment] 2022-01-29 09:11
as they indicated [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1282375#c24), that is the effect of another bug

> If Javascript is not enabled then the <script> tags would be ignored?

no, it doesn't seem like it. we simply shouldn't inject it if javascript is not enabled.
we can try to minimize it that way, but the bug remains.

**Comment by csagan5** [comment] 2022-01-29 23:22
> as they indicated [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1282375#c24), that is the effect of another bug
> 
> > If Javascript is not enabled then the <script> tags would be ignored?
> 
> no, it doesn't seem like it. we simply shouldn't inject it if javascript is not enabled. we can try to minimize it that way, but the bug remains.

I see no evidence whatsoever that not injecting the `<script>` would change the behavior of this bug. How would it minimize the bug expression?

**Comment by uazo** [comment] 2022-01-30 11:00
> I see no evidence whatsoever that not injecting the <script> would change the behavior of this bug.

no, you are right. I simply deleted the code and tried.

> How would it minimize the bug expression?

I have to say honestly, I don't remember, but that error no longer appeared

**Comment by csagan5** [comment] 2022-03-06 17:31
I am closing this as there are related upstream issues; if we can pinpoint the bug to something specific in Bromite I would be happy to re-open it and fix it.

**Closed by csagan5** 2022-03-06 17:31 UTC
Labels: bug, upstream, new-account

**Comment by uazo** [comment] 2022-03-07 07:49
> if we can pinpoint the bug to something specific in Bromite I would be happy to re-open it and fix it.

>> I see no evidence whatsoever that not injecting the <script> would change the behavior of this bug.
>
> no, you are right. I simply deleted the code and tried.

maybe check this ^
