### ISSUE TITLE
Crash after enabling DoH

### ISSUE THREAD

**Issue by gorillap** [bromite/bromite#433] opened 2019-12-09 09:12 UTC
### Bromite version

Version: 78.0.3904.119
Arch: ARM64
Android version: 10.0
Device model: OnePlus 7 Pro (GM1917)

### Can the bug be reproduced with corresponding Chromium version?

Please pick the same version of Chromium as Bromite from here: https://github.com/bromite/chromium/releases
If the bug is reproducible then it might be a configuration issue or an upstream bug. Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first.

### Is the bug a crash?

If yes then individuate and post the logcat dump (remove privacy sensitive information, if any), otherwise remove this section.

### Describe the bug

App crashes after enabling DoH and attempting to access any website. Attempted to clear cache and still crashes. Had to clear all data before I could access the browser again, which deleted bookmarks and saved passwords.

### Steps to reproduce the bug

Go to Settings>Privacy>Secure DNS> Toggle On> exit to go to any webpage

### Expected behavior
App crashes and will continue to crash until all app data wiped.
[alogcat.2019-12-09-04-06-18-0500.txt](https://github.com/bromite/bromite/files/3938785/alogcat.2019-12-09-04-06-18-0500.txt)

**Comment by csagan5** [comment] 2019-12-09 11:09
Duplicate of #430

**Comment by csagan5** [comment] 2019-12-09 11:10
@gorillap which URL did you specify?

Regardless, please try with latest version.

**Closed by csagan5** 2019-12-09 11:10 UTC
