### ISSUE TITLE
No option to open links in new tabs when "Open links in incognito tabs always" is enabled

### ISSUE THREAD

**Issue by Elaborendum** [bromite/bromite#1159] opened 2021-05-23 15:35 UTC
### Bromite version

Version: `91.0.4472.50`
Arch: `arm64`
Android version: `10`
Device model: `SM-A205G`

### Flags

These are the flags changed under `chrome://flags`: Reader Mode triggering

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?
Yes

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?

No

### Describe the bug

When "Open links in incognito tabs always" is enabled, there's no option to open links in new tabs when long pressing on a link.

Disabling it makes it appear in incognito mode.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Activate "Open links in incognito tabs always" in settings.
2. Open a page (like this very repo)
3. Long press a link

### Expected behavior

An option to open the link in a new tab is available.

### Screenshots

I don't really know how to enable screenshots in incognito mode in Bromite, so I can't provide any.

**Comment by csagan5** [comment] 2021-05-24 08:45
Duplicate of #1154

**Closed by csagan5** 2021-05-24 08:45 UTC
Labels: bug, needs-triage
