### ISSUE TITLE
Add Button to Toggle JavaScript

### ISSUE THREAD

**Issue by h4waii** [bromite/bromite#494] opened 2020-02-18 11:08 UTC
### Is your feature request related to privacy?
Yes-ish.

### Is there a patch available for this feature somewhere?

Not that I am aware of.

### Describe the solution you would like

The option to toggle running JavaScript on a site without having to delve deep in to Settings to do so. This button would simply toggle the same setting, but be exposed to the user in a more accessible fashion (perhaps on the quick toolbar or in the overflow menu).

### Describe alternatives you have considered

Alternative would be the existing method of toggling JavaScript by entering Overflow => Settings => Site Settings.

**Comment by csagan5** [comment] 2020-02-18 22:48
Duplicate of #486

**Closed by csagan5** 2020-02-18 22:48 UTC

**Comment by LukeOwlclaw** [comment] 2020-08-20 05:25
Issue again request with https://github.com/bromite/bromite/issues/562
