### ISSUE TITLE
Menu items are not properly displayed with tab overflow menu regroup flag

### ISSUE THREAD

**Issue by frankjrp** [bromite/bromite#963] opened 2021-03-02 05:30 UTC
### Bromite version

Version: `88.0.4324.207`
Arch: `arm` 
Android version: `5.1`
Device model: `Moto G1 - XT1033`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No

### Is the bug a crash?
Yes

### Describe the bug
When opening the menu its header is empty, the view source icon is broken and the bookmark all tabs menu item is missing.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Install the latest Bromite version (88.0.4324.207);
2. Open the menu;
3. See that the `menu header` is empty, the `View source icon` is broken and the `bookmark all tabs menu item` is missing.

### Expected behavior
When opening the menu all the menu items are displayed properly, as seen in the previous Bromite version.

__Question: What was wrong with the `exit and view source menu items icons`? Apparently they were working fine for me.__

_PS: I know this phone is very old, its my backup device, but everything was working fine in the previous version._

### Screenshots
![1](https://user-images.githubusercontent.com/33721770/109601415-94669f00-7afd-11eb-8f8e-914f2dad326d.jpg)

![2](https://user-images.githubusercontent.com/33721770/109601426-9d577080-7afd-11eb-8a07-42484faf0026.jpg)

**Comment by SumatraPeter** [comment] 2021-03-02 06:09
I'm using the same version via F-Droid on a tablet with even older Android I.e. 5.0.1, and I see no blank menu header (topmost item is New tab), plus the Bookmark all tabs menu is visible (and works). The View source icon is the same as in your screenshot, but I don't remember what it looked like before, so cannot say for certain whether it is broken or not (as a document-type icon it looked fine to me).

**Comment by chromer030** [comment] 2021-03-02 06:35
I'm using same version, no issue. but perhaps this occurs in locales other than English.

**Comment by frankjrp** [comment] 2021-03-02 08:08
I found out what's going on.

If I disable the flag `#tabbed-app-overflow-menu-regroup` I can see all the menu items correctly. **But in the old menu layout.**

If I enable this flag, the menu is broken as described above.

About the View source icon: I think @csagan5 changed this menu item icon. But the other one was prettier.

@SumatraPeter and @chromer030 can you guys please check if that flag is enabled and you're using the new menu layout? <br><br>

Old menu layout:
![3](https://user-images.githubusercontent.com/33721770/109616388-d8fd3500-7b13-11eb-8bd3-5ea8c2ea555c.jpg)

**Comment by chromer030** [comment] 2021-03-02 09:05
I'm using old menu by default.

**Comment by csagan5** [comment] 2021-03-02 18:58
@frankjrp can you provide steps to reproduce it, starting from a clean installation?

**Comment by SumatraPeter** [comment] 2021-03-02 20:05
> I'm using old menu by default.

Same here, flag disabled or default gives me the same old menu. New menu must be for newer Android versions only.

**Comment by frankjrp** [comment] 2021-03-03 00:48
> can you provide steps to reproduce it, starting from a clean installation?

@csagan5  Ok, I did a clean installation.

1. When opening Bromite menu after this clean installation, it shows the __old layout__ with all the items correctly arranged. The flag `#tabbed-app-overflow-menu-regroup` is set to Default.

2. When setting this flag to Enabled, the menu shows the new layout, but the items are not properly displayed as described above.

It seems that it's working only when this flag is not enabled.

**Comment by hbarsaiyan** [comment] 2021-03-04 10:15
I also have the same problem. The icons are not displaying for some items. I am on LineageOS 16.
![Screenshot_20210304-153615_Bromite_1](https://user-images.githubusercontent.com/37732050/109948746-9f3d5180-7d00-11eb-8a28-b4b8f87a02f5.png)

**Comment by frankjrp** [comment] 2021-03-04 12:54
@hbarsaiyan was it working on the previous version?

**Comment by hbarsaiyan** [comment] 2021-03-04 12:56
> @hbarsaiyan was it working on the previous version?

No the old menu was showing in default and when i enable the flag it shows like this.

**Comment by csagan5** [comment] 2021-03-08 23:05
> 2\. When setting this flag to Enabled

I cannot reproduce this issue. Are you setting it just to Enabled or one of the other options?

**Comment by frankjrp** [comment] 2021-03-09 01:18
> I cannot reproduce this issue. Are you setting it just to Enabled or one of the other options?

Yes! I'm setting just to Enabled.

But it's important to follow these steps:

1. Enable the flag;
2. Relaunch the browser;
3. Close the browser;
4. Open Bromite again;
5. Open the menu and see the error.

**Comment by hbarsaiyan** [comment] 2021-03-12 21:15
It is fixed now for me. Thank you.

**Comment by csagan5** [comment] 2021-03-13 07:57
> It is fixed now for me. Thank you.

Nothing has been fixed; you might have changed the flags.

**Comment by csagan5** [comment] 2021-03-13 18:00
Fixed in `89.0.4389.92`.

**Comment by hbarsaiyan** [comment] 2021-03-13 20:49
@csagan5 don't we have an arm64 release this time? Just asking.

**Comment by Nemris** [comment] 2021-03-14 14:07
@csagan5 Doesn't seem to be solved on Bromite 89.0.4389.92 - setting `#tabbed-app-overflow-menu-regroup` and restarting Bromite two to three times still yields an empty top row in the overflow menu.

**Comment by uazo** [comment] 2021-03-14 16:13
this is what i expect:
![image](https://user-images.githubusercontent.com/29201891/111075467-55b2ea80-84e8-11eb-969c-6b001e8d4667.png)
what am I doing wrong?

**Comment by Nemris** [comment] 2021-03-14 16:55
@uazo In my case, the top button row above `New tab` is empty when enabling the abovementioned flag. The row itself is still present, but without buttons.

I'm on stock Magisk rooted Android 10, One UI 2.0 on a SM-A405FN.

**Comment by uazo** [comment] 2021-03-14 16:57
I checked, it seems that @csagan5  in 89.0.4389.92 has removed (perhaps by mistake) my changes.

in the meantime I've found a bug in Remove-help-menu-item.patch
https://github.com/bromite/bromite/blob/master/build/patches/Remove-help-menu-item.patch#L22

**Comment by csagan5** [comment] 2021-03-14 21:05
@uazo not by mistake, I did not add the extra icon from your patch. Is that needed to fix the blank row?

**Comment by uazo** [comment] 2021-03-15 07:00
yes, the fix is right there! :)

adding a sixth button in the header of the app menu (you did after https://github.com/bromite/bromite/issues/943), a sixth icon have to be added in the row layout used to display, otherwise the switch does not lead to anything and the row is empty (see https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/ui/android/appmenu/internal/java/src/org/chromium/chrome/browser/ui/appmenu/AppMenuAdapter.java;l=174;drc=40f5195e60a82e940f4ef149e55944da9c8bf1f0;bpv=1;bpt=1)

for the same reason I increased the width of the menu by the size of an icon (the other part you removed)

**Comment by csagan5** [comment] 2021-03-15 19:40
> adding a sixth button in the header of the app menu (you did after #943), a sixth icon have to be added in the row layout used to display, otherwise the switch does not lead to anything and the row is empty

I do not understand how this is related to the patch to bookmark all tabs :thinking:

**Comment by uazo** [comment] 2021-03-16 16:36
> I do not understand how this is related to the patch to bookmark all tabs

uhm... let's see if I can explain it.. 
do you see these changes?
![image](https://user-images.githubusercontent.com/29201891/111344914-179aff80-867d-11eb-8ec9-4dc909526db4.png)

From here:
![image](https://user-images.githubusercontent.com/29201891/111344346-95124000-867c-11eb-8f1a-73454eec882c.png)

since the menu is developed in a sort of mvc pattern, the xml is not really the view but it is the model. the view is generated by `AppMenuAdapter` in the switch:

![image](https://user-images.githubusercontent.com/29201891/111345481-9f810980-867d-11eb-9fb8-e5d7f70075fa.png)

since the icons are no longer 5 but 6, the corresponding call `createMenuItemRow` is missing, so no view is created and the row is empty

**Comment by csagan5** [comment] 2021-03-16 21:55
This explanation could have been in the commit message :)

There is a mistake in the text associated to the button, it should have been left as before; I will fix it on next release.

When the flag is disabled or default: both menus have the 'Bookmark all tabs' menu entry
When the flag is enabled: the entry is not present in the tab hover menu and the white bar issue manifests.

Since there are other menu entries in the menu which are not on the top bar, how to fix the behaviour so that it is always like when flag is disabled?

**Comment by uazo** [comment] 2021-03-17 07:39
> This explanation could have been in the commit message :)

sorry, I thought it was clear with the changes. I'll be more wordy next time :)

> When the flag is disabled or default: both menus have the 'Bookmark all tabs' menu entry

what do you mean by both? header row and menu item?
if so, my changes are needed + must be added
https://github.com/bromite/bromite/blob/167f96019a71f15ab2fade77225a3584dd8a1be8/build/patches/Add-menu-item-to-bookmark-all-tabs.patch#L46-L48 in `main_menu_regroup.xml`

**Comment by csagan5** [comment] 2021-03-17 07:41
> what do you mean by both? header row and menu item?

No, the regular 3-dots menu and the one after tapping on the tabs counter.

> Since there are other menu entries in the menu which are not on the top bar, how to fix the behaviour so that it is always like when flag is disabled?

See my other question ^

**Comment by uazo** [comment] 2021-03-17 07:44
do you mean here?
![image](https://user-images.githubusercontent.com/29201891/111432125-e95d0480-86fc-11eb-9a09-c30f39c8c009.png)

**Comment by frankjrp** [comment] 2021-03-17 12:27
> do you mean here?

I think @csagan5 is talking about the menu entries as shown below (when the flag is disabled or default):

![1](https://user-images.githubusercontent.com/33721770/111466525-2d063d00-8702-11eb-9abd-5184a6654e17.jpg)

![2](https://user-images.githubusercontent.com/33721770/111466546-32fc1e00-8702-11eb-9f49-d9abd5186be1.jpg)

PS: Since you guys are fixing the menu issues, there is a missing icon after tapping on the tabs counter then the menu.

**Comment by Nemris** [comment] 2021-03-18 13:58
Can reproduce the missing `Exit` icon too.

**Comment by csagan5** [comment] 2021-03-18 22:22
> do you mean here?

@uazo regardless of the overflow menu regroup flag, the feature should work like this:
* one menu entry with text and icon on the regular three-dots menu (e.g. like `History`)
* one menu entry with text and icon on the three-dots menu when accessing the tabs hover menu (e.g. like `New Incognito Tab`)

As @frankjrp shows in the screenshots.

> there is a missing icon after tapping on the tabs counter then the menu.

You mean the exit menu icon, right?

**Comment by frankjrp** [comment] 2021-03-18 23:40
> You mean the exit menu icon, right?

Exactly.

**Comment by uazo** [comment] 2021-03-19 08:25
> @uazo regardless of the overflow menu regroup flag, the feature should work like this:
one menu entry with text and icon on the regular three-dots menu (e.g. like History)
one menu entry with text and icon on the three-dots menu when accessing the tabs hover menu (e.g. like New Incognito Tab)

removing this icon? (note: I only have it because I applied my patch)

![image](https://user-images.githubusercontent.com/29201891/111751655-0b898a80-8895-11eb-8019-e6fd00366406.png)

**Comment by csagan5** [comment] 2021-03-19 13:04
> removing this icon?

That is not sufficient. If the icon is removed, then the behavior is not the same regardless of the flag. The menu entry would be missing.

Here I mean the icon on the left of the text. No changes to the icon-only bar above.
> regardless of the overflow menu regroup flag, the feature should work like this:
> 
> * one menu entry with text and icon on the regular three-dots menu (e.g. like `History`)
> * one menu entry with text and icon on the three-dots menu when accessing the tabs hover menu (e.g. like `New Incognito Tab`)

**Comment by csagan5** [comment] 2021-03-25 10:37
@uazo shall I assign this to you? Otherwise I can try fixing it

**Comment by uazo** [comment] 2021-03-26 06:14
sure, I'll take care of it

**Comment by csagan5** [comment] 2021-04-03 14:12
@frankjrp is the exit menu missing icon fixed already?

**Comment by frankjrp** [comment] 2021-04-03 15:37
> is the exit menu missing icon fixed already?

@csagan5 yes, it's fixed!

**Comment by csagan5** [comment] 2021-04-06 21:01
I made a fix for the menu items; will be fixed on next release.

**Comment by csagan5** [comment] 2021-04-07 12:14
Fixed in `90.0.4430.59`.

**Comment by csagan5** [comment] 2021-04-23 17:42
I still see the blank empty item on top.

**Comment by frankjrp** [comment] 2021-04-25 02:09
Interesting! For me it's ok since the version `90.0.4430.59`

**Comment by uazo** [comment] 2021-11-16 12:05
@csagan5 I think it can be closed, can you confirm?

**Comment by frankjrp** [comment] 2021-11-16 16:38
> @csagan5 I think it can be closed, can you confirm?

Yes, everything is working fine.

**Comment by csagan5** [comment] 2021-11-16 22:47
Fixed in `90.0.4430.59`.

**Closed by csagan5** 2021-11-16 22:47 UTC
Labels: bug, user-interface
