### ISSUE TITLE
Granular control of Javascript

### ISSUE THREAD

**Issue by Thewisem** [bromite/bromite#1416] opened 2021-09-26 02:49 UTC
### Is your feature request related to privacy?

Yes
### Is there a patch available for this feature somewhere?

No. Not that I know of
### Describe the solution you would like

I would like to have granular control of the javascript being run in website like noscriptjs built into bromite
### Describe alternatives you have considered

Include the noscriptjs add on built in

**Comment by csagan5** [comment] 2021-09-26 09:24
Duplicate of #1360

**Closed by csagan5** 2021-09-26 09:24 UTC
Labels: enhancement, needs-triage
