### ISSUE TITLE
Google Play Services authorization prompt in v74

### ISSUE THREAD

**Issue by dadosch** [bromite/bromite#281] opened 2019-04-13 16:40 UTC
**Bromite version**

Version: `74.0.3729.80`
Arch: `arm64` 
Android version: `7.1.2`

**Is the bug reproducible with latest version?**
Already using latest version available from F-Droid Repo.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
Not tested, but Chromium doesn't claim to be privacy-enhanced.

**Is the bug a crash?**
no

**Describe the bug**
A notification appears after the latest update saying that Bromite needs Google Play Services. (see screenshot)

**Expected behavior**
Bromite should not depend on Google Play Services

**Screenshots**
![Screenshot_20190413-162835](https://user-images.githubusercontent.com/12801390/56082644-be7c1e80-5e0a-11e9-969f-9c1bf9b40be2.png)

**Comment by csagan5** [comment] 2019-04-14 07:32
This is likely due to new code in v74 using Play integrations; unfortunately the patches that I am using to evict this functionality are orphaned, so I would have now to do some work to find out why it's happening.

**Comment by ouzowtf** [comment] 2019-04-14 08:02
I haven't seen this notification yet. When does it show up?

**Comment by csagan5** [comment] 2019-04-14 08:38
This could be a regression (reference: https://forum.xda-developers.com/showpost.php?p=76242418&postcount=652)

@ouzowtf you need to terminate the app or reboot to see it.

**Comment by csagan5** [comment] 2019-04-15 06:36
Fixed in `74.0.3729.86`.

@dadosch please report back if it is not fixed.

**Comment by BugReporterGit** [comment] 2019-04-18 17:22
> Fixed in `74.0.3729.86`.

@csagan5

It has not been fixed to the `74.0.3729.86` version. I am experiencing the same problem in the latest version.

**Comment by dadosch** [comment] 2019-04-18 18:07
I can confirm that it isn't fixed in  74.0.3729.86.

**Comment by csagan5** [comment] 2019-04-21 05:37
Ok, thanks for reporting; something must have changed in the code or in the manifest that makes this prompt happen again. No idea about what though.

**Comment by hadig** [comment] 2019-04-25 08:44
You can disable this notification in bromite's notification settings

**Comment by csagan5** [comment] 2019-04-28 18:22
Is this problem still present with `74.0.3729.122`?

**Comment by AlternativeZero** [comment] 2019-04-29 07:55
@csagan5 I still seem to have login issues on `74.0.3729.122`, I brought it up in the [microg](https://github.com/microg/android_packages_apps_GmsCore/issues/770) issues cause I thought it was an issue on their end but read on xda it's an issue with v74.

I have a logcat there if it's any use.

**Comment by BugReporter2** [comment] 2019-05-05 07:46
> Is this problem still present with `74.0.3729.122`?

Yes.

@csagan5

**Comment by AlternativeZero** [comment] 2019-05-07 01:05
Just tested 74.0.3729.141 and login still isn't working.

**Comment by csagan5** [comment] 2019-05-07 06:22
@AlternativeZero that should be discussed in a separate issue. This issue here is "Google Play Services authorization prompt in v74"

**Comment by csagan5** [comment] 2019-05-18 10:58
I cannot reproduce this issue; can somebody please verify with `74.0.3729.162`?

**Comment by BugReporter2** [comment] 2019-05-18 17:05
> I cannot reproduce this issue; can somebody please verify with `74.0.3729.162`?

The issue still exists in the latest version, `74.0.3729.162`.

**Comment by csagan5** [comment] 2019-05-18 20:09
@BugReporter2 you are experiencing this issue with the Bromite browser, not the SystemWebView, correct?

What are the steps to trigger it?

**Comment by BugReporter2** [comment] 2019-05-19 05:41
> @BugReporter2 you are experiencing this issue with the Bromite browser, not the SystemWebView, correct?

Yes, with the Bromite browser.

> What are the steps to trigger it?

Just normal browsing. There is no special step to trigger it. Start browsing websites, so that prompt will come in a certain amount of time. Sometimes the prompt comes almost immediately when you open Bromite and start browsing and sometimes it can take several minutes.

**Comment by whour** [comment] 2019-05-22 09:42
`75.0.3770.50` still  have problems.
Just browse m.youtube.com, click a video,you will see the problem.

**Comment by allenluce** [comment] 2019-05-23 20:58
> This is likely due to new code in v74 using Play integrations; unfortunately the patches that I am using to evict this functionality are orphaned, so I would have now to do some work to find out why it's happening.

Hi @csagan5, can you supply a reference to those patches?

**Comment by csagan5** [comment] 2019-05-24 03:18
@allenluce the patches have been included for about a year now, they come from this abandoned project: https://gitlab.com/thermatk/Unobtainium

You can find them under https://github.com/bromite/bromite/tree/master/build/patches as `kill-Auth.patch` and `kill-GCM.patch`; the Chromium build from Arch Linux has similar patches.

This new authorization request is due to some new code from upstream and it's not easy to find out where it is; I also cannot reproduce it.

**Comment by thestinger** [comment] 2019-06-12 20:55
Try visiting https://www.tomshardware.com/.

**Comment by csagan5** [comment] 2019-06-18 06:16
@thestinger I am still unable to reproduce this with real devices. Can this be reproduced with the Android Virtual Device or it is related to running a specific ROM?

**Comment by thestinger** [comment] 2019-06-18 21:52
It occurs for me on AOSP on any of the officially supported devices. I think there's a good chance you could reproduce it in the emulator.

**Comment by thestinger** [comment] 2019-06-18 21:53
Also, worth noting that this does also occur in Brave too: https://github.com/brave/browser-android-tabs/issues/1639.

**Comment by thestinger** [comment] 2019-06-18 21:54
Also, worth noting that this does also occur in Brave too: brave/browser-android-tabs#1639, so the idea of getting a fix from there isn't viable.

**Comment by expobar** [comment] 2019-06-20 11:05
Another page which quickly triggers this issue is 1.1.1.1/help

**Comment by csagan5** [comment] 2019-06-24 05:51
@thestinger I think it does not appear on my physical devices because it might have been granted in the past already.

Thanks for the explanation and reference, it makes sense. So it's an upstream bug and there appears to be little incentive from upstream to fix it in a timely manner.

**Comment by csagan5** [comment] 2019-06-24 06:54
Has anybody found/created the upstream issue in Chromium issue tracker? I suggest addressing it upstream, they might find more easily where this comes from.

This would be addressed radically if no play services were used in Bromite, but it's not currently being worked on.

Closing it as the fix will come from upstream (if ever).

**Comment by thestinger** [comment] 2019-06-24 19:26
I don't think there's an issue open yet. I wanted to identify the reason for the issue before filing it. They're likely to fix it very quickly if they're pointed towards the right place, but otherwise I expect they will treat it as a very low priority unless they can quickly identify the problem. Since https://1.1.1.1/help can trigger it without needing much code, someone should work on narrowing down the specific issue and then it should be fairly easy to find the right place to fix this.

**Comment by thestinger** [comment] 2019-07-06 09:48
I resolved this with https://github.com/GrapheneOS/Vanadium/blob/9bb898ebcee8102fd60da961ee17c458eaf3ec7f/0021-disable-media-router-by-default.patch, but I also added https://github.com/GrapheneOS/Vanadium/blob/9bb898ebcee8102fd60da961ee17c458eaf3ec7f/0020-disable-media-router-media-remoting-by-default.patch for good measure.

**Comment by csagan5** [comment] 2019-07-11 07:16
Will be fixed in next release `75.0.3770.139` thanks to @thestinger's patches.

**Comment by csagan5** [comment] 2019-07-13 05:08
Can someone please test whether this problem is resolved with latest version `75.0.3770.139` or not?

**Comment by expobar** [comment] 2019-07-13 05:36
Fixed on my side. I can't seem to trigger it on sites that usually triggers this. Thanks guys.

**Closed** 2019-07-13 06:46 UTC
Labels: bug, upstream
