### ISSUE TITLE
"Get Google Play Services"

### ISSUE THREAD

**Issue by hyphenrf** [bromite/bromite#327] opened 2019-06-25 15:46 UTC
**Bromite version**

Version: `75.0.3770.109`
Arch: `arm`
Android version: `nougat 7.1.2`, ungoogled.

**Is the bug a crash?**
No. App continues working as expected.

**Describe the bug**
After using Bromite for a while, the message in this issue's title appears. It warns me that bromite will not be able to run without the services, but proceeds to run just fine.
It is true that I don't have any google app on my phone, including the play services. I run Lineage 14.1 without GApps. I was just wondering why would Bromite have a dependency check on play services when it's not supposed to be Google. It's a chromium fork not a Chrome one.

**Screenshots**
![Screenshot_20190625-172837_1](https://user-images.githubusercontent.com/26802762/60112974-1ae7ac80-9771-11e9-8945-b638400c508e.png)

**Comment by csagan5** [comment] 2019-06-26 07:45
Duplicate of #281

**Closed by csagan5** 2019-06-26 07:45 UTC
