### ISSUE TITLE
Crash on Settings > Homepage

### ISSUE THREAD

**Issue by subhinay** [bromite/bromite#484] opened 2020-02-07 09:35 UTC
### Bromite version

Version: `80.0.3987.78`
Arch: `arm`
Android version: `8.1.0`
Device model: `Moto G5S+ (XT1804`)

### Is the bug reproducible with latest version?
It is.

### Can the bug be reproduced with corresponding Chromium version?
Not this one. However, Chromium build crashes on Settings > Privacy

### Is the bug a crash?
Yes. Will see the process of how to get a log dump and update.

### Describe the bug
Navigate to Settings > Homepage. `Bromite has stopped` or `Bromite keeps stopping` pops up.

### Steps to reproduce the bug

1. Go to the menu (the vertical 3 dot thing at the top right corner)
2. Click on Settings
3. Scroll down to Homepage

### Expected behavior
To see Homepage options.

### Screenshots
Will update.

**Comment by alissonlauffer** [comment] 2020-02-07 11:43
Same here on the "About Bromite" section.

**Comment by jrjordao** [comment] 2020-02-07 12:57
> Same here on the "Home page" and "About Bromite" sections.

Same here

**Comment by norbertc** [comment] 2020-02-09 17:19
logcat on the home page crash:

02-10 01:15:21.446 27700 27700 E ResourcesCompat: Failed to find font-family tag
02-10 01:15:21.450 27700 27700 D AndroidRuntime: Shutting down VM
02-10 01:15:21.450 27700 27700 E AndroidRuntime: FATAL EXCEPTION: main
02-10 01:15:21.450 27700 27700 E AndroidRuntime: Process: org.bromite.bromite, PID: 27700
02-10 01:15:21.450 27700 27700 E AndroidRuntime: android.view.InflateException: Binary XML file line #9: Error inflating class (not found)org.chromium.chrome.browser.preferences.ChromeSwitchPreference
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at vc.a(PG:49)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at vc.a(PG:75)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at vc.a(PG:8)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at nc.g(PG:8)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at Hp0.a(PG:2)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at org.chromium.chrome.browser.settings.HomepagePreferences.a(PG:3)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at nc.b(PG:10)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at R2.a(PG:289)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at d3.a(PG:232)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at d3.a(PG:11)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at R2.a(PG:649)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at R2.b(PG:36)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at R2.m(PG:14)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at R2.b(PG:42)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at R2.f(PG:13)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at v2.onStart(PG:6)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at G8.onStart(PG:1)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7848)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
02-10 01:15:21.450 27700 27700 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.preferences.ChromeSwitchPreference" on path: DexPathList[[zip file "/data/app/org.bromite.bromite-qPilzFUrXC1Gwzx7rgU9Rg==/base.apk"],nativeLibraryDirectories=[/data/app/org.bromite.bromite-qPilzFUrXC1Gwzx7rgU9Rg==/lib/arm64, /data/app/org.bromite.bromite-qPilzFUrXC1Gwzx7rgU9Rg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at vc.a(PG:29)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        at vc.a(PG:43)
02-10 01:15:21.450 27700 27700 E AndroidRuntime:        ... 30 more
02-10 01:15:21.494 28296 28296 W chromium: [0210/011521.493610:WARNING:exception_snapshot_linux.cc(261)] fpsimd not found
02-10 01:15:21.494 28296 28296 W chromium: [0210/011521.494050:WARNING:exception_snapshot_linux.cc(427)] Unhandled signal -1
02-10 01:15:21.500  1302 28297 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
02-10 01:15:21.501  1302  4267 W ActivityTaskManager:   Force finishing activity org.bromite.bromite/org.chromium.chrome.browser.settings.SettingsActivity
02-10 01:15:21.510  1302  4267 W ActivityTaskManager:   Force finishing activity org.bromite.bromite/org.chromium.chrome.browser.settings.SettingsActivity

same issue on about screen:

02-10 01:16:20.580 28306 28306 D AndroidRuntime: Shutting down VM
02-10 01:16:20.580 28306 28306 E AndroidRuntime: FATAL EXCEPTION: main
02-10 01:16:20.580 28306 28306 E AndroidRuntime: Process: org.bromite.bromite, PID: 28306
02-10 01:16:20.580 28306 28306 E AndroidRuntime: android.view.InflateException: Binary XML file line #14: Error inflating class (not found)org.chromium.chrome.browser.preferences.HyperlinkPreference
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at vc.a(PG:49)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at vc.a(PG:75)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at vc.a(PG:8)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at nc.g(PG:8)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at Hp0.a(PG:2)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at org.chromium.chrome.browser.settings.about.AboutChromeSettings.a(PG:2)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at nc.b(PG:10)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at R2.a(PG:289)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at d3.a(PG:232)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at d3.a(PG:11)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at R2.a(PG:649)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at R2.b(PG:36)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at R2.m(PG:14)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at R2.b(PG:42)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at R2.f(PG:13)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at v2.onStart(PG:6)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at G8.onStart(PG:1)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7848)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
02-10 01:16:20.580 28306 28306 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.preferences.HyperlinkPreference" on path: DexPathList[[zip file "/data/app/org.bromite.bromite-qPilzFUrXC1Gwzx7rgU9Rg==/base.apk"],nativeLibraryDirectories=[/data/app/org.bromite.bromite-qPilzFUrXC1Gwzx7rgU9Rg==/lib/arm64, /data/app/org.bromite.bromite-qPilzFUrXC1Gwzx7rgU9Rg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at vc.a(PG:29)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        at vc.a(PG:43)
02-10 01:16:20.580 28306 28306 E AndroidRuntime:        ... 30 more
02-10 01:16:20.626 28751 28751 W chromium: [0210/011620.625806:WARNING:exception_snapshot_linux.cc(261)] fpsimd not found
02-10 01:16:20.626 28751 28751 W chromium: [0210/011620.626232:WARNING:exception_snapshot_linux.cc(427)] Unhandled signal -1
02-10 01:16:20.632  1302 28752 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
02-10 01:16:20.633  1302  9488 W ActivityTaskManager:   Force finishing activity org.bromite.bromite/org.chromium.chrome.browser.settings.SettingsActivity
02-10 01:16:20.642  1302  9488 W ActivityTaskManager:   Force finishing activity org.bromite.bromite/org.chromium.chrome.browser.settings.SettingsActivity

**Comment by Phantop** [comment] 2020-02-09 17:21
Same here
arch: arm64
version 80.0.3987.78
android version: 9
device: Google Pixel 1

**Comment by cs-nero** [comment] 2020-02-09 18:10
Same.
Android 7.1.2

**Comment by sonnyxq** [comment] 2020-02-11 00:43
Same here!

Arch: arm64
Version: 80.0.3987.78
Android Version: 10 with February update
Device: Google Pixel 2

The app crash too, if I go and open Google, typing in Search just 'GIFs' and then the tab above just show me 'Pictures' and scroll down for 2-5 sec... App shows me:

Bromite keeps stopping

as endless Pop-ups.

The only solution for me is to install again the Bromite v79.0.3945.111
The only stable release for me without this issue. 
I did test it with every release since this version and it keeps crashing and other websites as well.

**Comment by sviluppoSoftware** [comment] 2020-02-11 13:46
> Same here on the "Home page" and "About Bromite" sections.

same either for me

**Comment by draxaris1010** [comment] 2020-02-11 17:24
I have the same issue with my Moto G5 running Android 8.1.0

**Comment by xmiseggs** [comment] 2020-02-12 07:32
It's the same with my OnePlus 5T, I go back to the previous version of Bromite

**Comment by bat999** [comment] 2020-02-13 18:02
Can the bug be reproduced with corresponding Chromium version?
Not this one. However, Chromium build crashes on Settings > Privacy

Hi
Same as @subhinay above.
I have this problem too with Chromium from F-droid.
Settings > Privacy
"Chromium has stopped"

But when I installed Chrome-Beta from PlayStore there is no problem.

Maybe chromium has fixed it with a commit somewhere between...
Chromium v80.0.3987.**78**
and
Chrome-Beta v80.0.3987.**99**

My phone is Xiaomi Redmi go
OS is Android-go v8.1.0

**Comment by csagan5** [comment] 2020-02-13 22:52
Fixed in `80.0.3987.95`.

**Closed by csagan5** 2020-02-13 22:52 UTC
Labels: bug

**Comment by subhinay** [comment] 2020-02-18 08:42
Thank you @csagan5 for fixing this.
