### ISSUE TITLE
[WebView] - Touch not working in some apps

### ISSUE THREAD

**Issue by MartinX3** [bromite/bromite#2060] opened 2022-05-08 20:27 UTC
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

101.0.4951.53

### Device architecture

arm64-v8a

### Android version

11

### Device model

Sony Xperia XZ2

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

Yes

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

WebView

```
05-08 22:11:57.332  1448 12591 I ActivityTaskManager: START u0 {cmp=com.github.android/.activities.IssueOrPullRequestActivity (has extras)} from uid 10275
05-08 22:11:57.346  1448 12591 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (20034973)
05-08 22:11:57.356  1448  1583 I ActivityManager: Killing 29473:com.android.documentsui/u0a91 (adj 985): empty #17
05-08 22:11:57.380   809   809 I Zygote  : Process 29473 exited due to signal 9 (Killed)
05-08 22:11:57.411  1448  1591 I libprocessgroup: Successfully killed process cgroup uid 10091 pid 29473 in 53ms
05-08 22:11:57.430  1448  1588 I ActivityTaskManager: Displayed com.github.android/.activities.IssueOrPullRequestActivity: +97ms
05-08 22:11:57.445  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3182 
05-08 22:11:57.445  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2077 checkRepeatedly = false, unlocked = true
05-08 22:11:57.445  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1885 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.github.android fieldId=-1 fieldName=null extras=null}, false)
05-08 22:11:57.446  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2077 checkRepeatedly = true, unlocked = true
05-08 22:11:58.438 30365 30365 W View    : requestLayout() improperly called by android.widget.LinearLayout{28226bd V.E...... ......ID 154,38-154,116 #7f0a03ac app:id/toolbar_text} during layout: running second layout pass
05-08 22:11:58.565  2681  3300 I BtGatt.ScanManager: msg.what = 6
05-08 22:11:58.571  3674  8908 I FontLog : Received query name=Noto Color Emoji Compat&weight=400&besteffort=false, URI content://com.google.android.gms.fonts [CONTEXT service_id=132 ]
05-08 22:11:58.576  3674  8908 I FontLog : Query [name=Noto Color Emoji Compat&weight=400&besteffort=false] resolved to {Noto Color Emoji Compat, wdth 100.0, wght 400, ital 0.0, bestEffort false} [CONTEXT service_id=132 ]
05-08 22:11:58.589  3674  8908 I FontLog : Fetch {Noto Color Emoji Compat, wdth 100.0, wght 400, ital 0.0, bestEffort false} end status Status{statusCode=SUCCESS, resolution=null} [CONTEXT service_id=132 ]
05-08 22:11:58.593  3674  8908 I FontLog : Pulling font file for id = 275, cache size = 5 [CONTEXT service_id=132 ]
05-08 22:11:58.616 30447 30496 E chromium: [ERROR:tile_manager.cc(833)] WARNING: tile memory limits exceeded, some content may not draw
```

Bromite (`chrome://flags`)

```
05-08 22:24:14.136  1448  9812 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10209; state: DISABLED
05-08 22:24:14.137  1448  1590 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10209; state: ENABLED
05-08 22:24:14.159 32542 32542 W cr_SpanAutocomplete: Did not notify - ignored.
05-08 22:24:14.160 32579 32579 D Zygote  : Forked child process 330
05-08 22:24:14.164  1448  1590 I ActivityManager: Start proc 330:org.bromite.bromite:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:3/u0ai103 for  {org.bromite.bromite/org.chromium.content.app.SandboxedProcessService0:3}
05-08 22:24:14.177 32542 32542 W cr_SpanAutocomplete: Did not notify - no change.
05-08 22:24:14.189 32542 32542 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
05-08 22:24:14.197 32542 32542 W cr_SpanAutocomplete: Did not notify - ignored.
05-08 22:24:14.204  1448  7727 D CompatibilityChangeReporter: Compat change id reported: 136274596; UID 10209; state: ENABLED
05-08 22:24:14.202 32542 32542 W cr_SpanAutocomplete: Did not notify - ignored.
05-08 22:24:14.228 32542 32542 W IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
05-08 22:24:14.231   330   330 I cr_SplitCompatApp: Launched version=101.0.4951.53 minSdkVersion=23 isBundle=false processName=org.bromite.bromite:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:3 isIsolated=true
05-08 22:24:14.232 32542 32542 W IInputConnectionWrapper: getSelectedText on inactive InputConnection
05-08 22:24:14.236   330   330 I cr_ChildProcessService: Creating new ChildProcessService pid=330
05-08 22:24:14.247   330   413 I cr_LibraryLoader: Successfully loaded native library
05-08 22:24:14.248 32542 32542 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
05-08 22:24:14.250  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1885 onStartInput(EditorInfo{inputType=0x11(Uri) imeOptions=0x12000002 privateImeOptions=null actionName=GO actionLabel=null actionId=0 initialSelStart=3 initialSelEnd=3 initialCapsMode=0x0 hintText=Suchbegriff oder Webadresse eingeben label=null packageName=org.bromite.bromite fieldId=2131429357 fieldName=null extras=null}, true)
05-08 22:24:14.251   330   413 I cr_CachingUmaRecorder: Flushed 3 samples from 3 histograms.
05-08 22:24:14.253  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2077 checkRepeatedly = true, unlocked = true
05-08 22:24:14.253  5970  5970 W SessionManager: SessionManager.beginSession():53 Try to begin an already begun session [INPUT_SESSION], end it first
05-08 22:24:14.254  5970  5970 W SessionManager: SessionManager.endSession():96 Child session [INPUT_VIEW_SESSION] is not ended while ending session [{INPUT_SESSION=1652041443000, TRAINING_CACHE_SESSION=1652041443068, INPUT_VIEW_SESSION=1652041443001, IME_SESSION=1652041443068}], ending it now.
05-08 22:24:14.254  5970  5970 W SessionManager: SessionManager.endSession():96 Child session [IME_SESSION] is not ended while ending session [{INPUT_SESSION=1652041443000, TRAINING_CACHE_SESSION=1652041443068, INPUT_VIEW_SESSION=1652041443001, IME_SESSION=1652041443068}], ending it now.
05-08 22:24:14.255  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.onStartInputView():1993 onStartInputView(EditorInfo{inputType=0x11(Uri) imeOptions=0x12000002 privateImeOptions=null actionName=GO actionLabel=null actionId=0 initialSelStart=3 initialSelEnd=3 initialCapsMode=0x0 hintText=Suchbegriff oder Webadresse eingeben label=null packageName=org.bromite.bromite fieldId=2131429357 fieldName=null extras=null}, true)
05-08 22:24:14.255  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2077 checkRepeatedly = true, unlocked = true
05-08 22:24:14.262   330   413 W SystemServiceRegistry: No service published for: uimode
05-08 22:24:14.267 32542 32542 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
05-08 22:24:13.315     0     0 I [schedu][686116224965][22:24:14.294183] wlan: [13736:I:WMA] wma_wlan_bt_activity_evt_handler: 6017: Received BT activity event 5
05-08 22:24:13.315     0     0 I [schedu][686116230482][22:24:14.294470] wlan: [13736:I:WMA] wma_wlan_bt_activity_evt_handler: 6017: Received BT activity event 6
05-08 22:24:14.307 32542 32542 W IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
05-08 22:24:14.310 32542 32542 I cr_tabmodel: Appending tabs being restored to metadata lists, 0, startingNormalCount: 9, startingIncognitoCount: 0
05-08 22:24:14.310 32542 32542 I cr_tabmodel: Serializing tab lists; counts: 9, 0
05-08 22:24:14.310 32542 32542 W IInputConnectionWrapper: getSelectedText on inactive InputConnection
05-08 22:24:14.312  5970  5970 I KeyboardViewUtil: KeyboardViewUtil.getKeyboardHeightRatio():168 systemKeyboardHeightRatio:1.000000; userKeyboardHeightRatio:1.000000.
05-08 22:24:14.315 32542 32542 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
05-08 22:24:14.318  5970  5970 I KeyboardWrapper: KeyboardWrapper.consumeEvent():273 Skip consuming an event as current keyboard is deactivated (state=0, keyboard existence=true)
05-08 22:24:14.318  5970  5970 I VoiceInputManagerWrapper: VoiceInputManagerWrapper.shutdown():77 shutdown()
05-08 22:24:14.322  5970  5970 I AndroidIME: AbstractIme.onDeactivate():207 LatinIme.onDeactivate()
05-08 22:24:14.322  5970  5970 W SessionManager: SessionManager.endSession():88 Try to end a not begun session [IME_SESSION].
05-08 22:24:14.323  5970  5970 I AndroidIME: AbstractIme.onActivate():86 LatinIme.onActivate() : EditorInfo = inputType=URI imeActionName=GO dump=[inputType=0x11 imeOptions=0x12000002 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=3 initialSelEnd=3 initialCapsMode=0x0 hintText=Suchbegriff oder Webadresse eingeben label=null packageName=org.bromite.bromite autofillId=1073741826 fieldId=2131429357 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], IncognitoMode = false, DeviceLocked = false
05-08 22:24:14.323  5970  5970 I Delight5Facilitator: Delight5Facilitator.initializeForIme():779 initializeForIme() : Locale = [en_GB, de], layout = qwertz
05-08 22:24:14.323  5970  5970 I VoiceInputManagerWrapper: VoiceInputManagerWrapper.cancelShutdown():55 cancelShutdown()
05-08 22:24:14.323  5970  5970 I VoiceInputManagerWrapper: VoiceInputManagerWrapper.syncLanguagePacks():67 syncLanguagePacks()
05-08 22:24:14.324  5970 11834 I SpeechFactory: SpeechRecognitionFactory.maybeScheduleAutoPackDownloadForFallback():202 maybeScheduleAutoPackDownloadForFallback()
05-08 22:24:14.324  5970  5970 I LatinIme: LatinIme.updateEnableInlineSuggestionsOnDecoderSideFlags():1276 inline flag updated to:false
05-08 22:24:14.324  5970 11834 I FallbackOnDeviceRecognitionProvider: FallbackOnDeviceRecognitionProvider.maybeScheduleAutoPackDownload():196 maybeScheduleAutoPackDownload() for language tag en-GB
05-08 22:24:14.324  5970 11834 I FallbackOnDeviceRecognitionProvider: FallbackOnDeviceRecognitionProvider.maybeScheduleAutoPackDownload():196 maybeScheduleAutoPackDownload() for language tag de
05-08 22:24:14.331 32542 32542 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
05-08 22:24:14.333  5970  5970 I KeyboardWrapper: KeyboardWrapper.consumeEvent():273 Skip consuming an event as current keyboard is deactivated (state=0, keyboard existence=true)
05-08 22:24:14.348 32542 32542 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
05-08 22:24:14.351  5970  5970 I KeyboardViewUtil: KeyboardViewUtil.calculateMaxKeyboardBodyHeight():44 leave 344 height for app when screen height:2028, header height:121 and isFullscreenMode:false, so the max keyboard body height is:1563
05-08 22:24:14.351  5970  5970 I DeviceModeUtil: DeviceModeUtil.getDeviceMode():126 Get device mode phone by ui mode:1 and smallestScreenWidthDp:392
05-08 22:24:14.351  5970  5970 I DeviceModeUtil: DeviceModeUtil.getDeviceMode():126 Get device mode phone by ui mode:1 and smallestScreenWidthDp:392
05-08 22:24:14.352  5970  5970 I KeyboardViewUtil: KeyboardViewUtil.calculateMaxKeyboardBodyHeight():44 leave 344 height for app when screen height:2028, header height:121 and isFullscreenMode:false, so the max keyboard body height is:1563
05-08 22:24:14.365 32542 32542 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
05-08 22:24:14.366  5970  5970 I NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():111 currentPrimeKeyboardType:SOFT systemPaddingBottom:-1
05-08 22:24:14.367  5970  5970 I NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():111 currentPrimeKeyboardType:SOFT systemPaddingBottom:-1
05-08 22:24:14.369  5970  5970 I VoiceImeExtension: VoiceImeExtension.shouldStartVoiceInputAutomatically():372 No private IME option set to start voice input.
05-08 22:24:14.382 32542 32542 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
05-08 22:24:14.398 32542 32542 W IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
05-08 22:24:14.414 32542 32542 W IInputConnectionWrapper: getSelectedText on inactive InputConnection
05-08 22:24:14.416  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.onFinishInputView():2229 
05-08 22:24:14.418  5970  5970 I KeyboardWrapper: KeyboardWrapper.consumeEvent():273 Skip consuming an event as current keyboard is deactivated (state=0, keyboard existence=true)
05-08 22:24:14.418  5970  5970 I VoiceInputManagerWrapper: VoiceInputManagerWrapper.shutdown():77 shutdown()
05-08 22:24:14.418  5970  5970 I AndroidIME: AbstractIme.onDeactivate():207 LatinIme.onDeactivate()
05-08 22:24:14.420  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3182 
05-08 22:24:14.420  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2077 checkRepeatedly = false, unlocked = true
05-08 22:24:14.420  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1885 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x12000000 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=org.bromite.bromite fieldId=-1 fieldName=null extras=null}, false)
05-08 22:24:14.421  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2077 checkRepeatedly = true, unlocked = true
05-08 22:24:14.422  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.onStartInputView():1993 onStartInputView(EditorInfo{inputType=0x0(NULL) imeOptions=0x12000000 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=org.bromite.bromite fieldId=-1 fieldName=null extras=null}, false)
05-08 22:24:14.422  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2077 checkRepeatedly = true, unlocked = true
05-08 22:24:14.466  5970  5970 I KeyboardViewUtil: KeyboardViewUtil.getKeyboardHeightRatio():168 systemKeyboardHeightRatio:1.000000; userKeyboardHeightRatio:1.000000.
05-08 22:24:14.466  5970  5970 I AndroidIME: AbstractIme.onActivate():86 PasswordIme.onActivate() : EditorInfo = inputType=Text imeActionName=UNSPECIFIED dump=[inputType=0x0 imeOptions=0x12000000 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=org.bromite.bromite autofillId=0 fieldId=-1 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], IncognitoMode = false, DeviceLocked = false
05-08 22:24:14.469  5970  5970 I KeyboardViewHelper: KeyboardViewHelper.getView():166 Get view with height ratio:1.000000
05-08 22:24:14.472 23416 23427 E ocessService0:: failed to create Unix domain socket: Operation not permitted
05-08 22:24:14.483  5970  5970 I KeyboardViewUtil: KeyboardViewUtil.calculateMaxKeyboardBodyHeight():44 leave 344 height for app when screen height:2028, header height:121 and isFullscreenMode:false, so the max keyboard body height is:1563
05-08 22:24:14.484  5970  5970 I DeviceModeUtil: DeviceModeUtil.getDeviceMode():126 Get device mode phone by ui mode:1 and smallestScreenWidthDp:392
05-08 22:24:14.484  5970  5970 I KeyboardViewUtil: KeyboardViewUtil.calculateMaxKeyboardBodyHeight():44 leave 344 height for app when screen height:2028, header height:121 and isFullscreenMode:false, so the max keyboard body height is:1563
05-08 22:24:14.485  5970  5970 I NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():111 currentPrimeKeyboardType:SOFT systemPaddingBottom:-1
05-08 22:24:14.485  5970  5970 I NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():111 currentPrimeKeyboardType:SOFT systemPaddingBottom:-1
05-08 22:24:14.487  5970  5970 I VoiceImeExtension: VoiceImeExtension.shouldStartVoiceInputAutomatically():372 No private IME option set to start voice input.
05-08 22:24:14.491  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.onFinishInputView():2229 
05-08 22:24:14.491  5970  5970 I AndroidIME: AbstractIme.onDeactivate():207 PasswordIme.onDeactivate()
05-08 22:24:14.514  5970  5970 W InputContextProxy: InputContextProxy.applyClientDiffInternal():920 Ignore [FetchSuggestions] diff due to stale request: 10717<10721, inputStateId=87, lastInputStateId=90
05-08 22:24:14.515  5970  5970 W InputContextProxy: InputContextProxy.applyClientDiffInternal():920 Ignore [FetchSuggestions] diff due to stale request: 10719<10721, inputStateId=89, lastInputStateId=90
05-08 22:24:15.155  1448  9812 D ConnectivityService: requestNetwork for uid/pid:10242/32371 NetworkRequest [ TRACK_DEFAULT id=1206, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10242 AdministratorUids: [] RequestorUid: 10242 RequestorPackageName: com.pr0gramm.app] ]
05-08 22:24:15.155  1448  2572 D ConnectivityService: NetReassign [1206 : null → 138]
05-08 22:24:15.156  1448  2628 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=1206, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10242 AdministratorUids: [] RequestorUid: 10242 RequestorPackageName: com.pr0gramm.app] ] with score 60 and providerId 5
05-08 22:24:15.156  1448  2556 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=1206, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10242 AdministratorUids: [] RequestorUid: 10242 RequestorPackageName: com.pr0gramm.app] ] with score 60 and providerId 5
05-08 22:24:15.156  1448  2556 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=1206, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10242 AdministratorUids: [] RequestorUid: 10242 RequestorPackageName: com.pr0gramm.app] ] with score 60 and providerId 5
05-08 22:24:15.156  3147  3147 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=1206, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10242 AdministratorUids: [] RequestorUid: 10242 RequestorPackageName: com.pr0gramm.app] ] with score 60 and providerId 5
05-08 22:24:15.161 32371 32395 I [DefaultDispatcher-worker-1] SyncWorker: Sync worker started (started by Bootup)
05-08 22:24:15.161 32371 32395 I [DefaultDispatcher-worker-1] SyncService: Performing a sync operation now
05-08 22:24:15.161 32371 32398 I [DefaultDispatcher-worker-4] SyncWorker: Scheduling sync-job to run in 1.0000min (append=true)
05-08 22:24:15.162 32371 32395 I [DefaultDispatcher-worker-1] SyncService: Sync with pr0gramm api
05-08 22:24:15.226 32371 32395 I [DefaultDispatcher-worker-1] SiteSettingsService: Got fallbackValues={themeId=5, showAds=false, favUpvote=true, legacyPath=false} and remote values {themeId=5, showAds=0, favUpvote=1, legacyPath=0}
05-08 22:24:15.226 32371 32395 I [DefaultDispatcher-worker-1] SiteSettingsService: Wants to update local settings to SiteSettings(themeId=5, showAds=false, favUpvote=true, secondaryServers=false)
05-08 22:24:15.226 32371 32395 I [DefaultDispatcher-worker-1] SiteSettingsService: Settings have not changed.
05-08 22:24:15.251 32371 32443 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=a2608407-2924-457f-9fdc-98a8a8a8efdc, tags={ com.pr0gramm.app.sync.SyncWorker } ]
05-08 22:24:15.252 32371 32443 I WM-WorkerWrapper: Setting status to enqueued for 897e1795-182b-4cfb-ad7b-f6713aaa02da
05-08 22:24:15.253  1448  2572 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=1206, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10242 AdministratorUids: [] RequestorUid: 10242 RequestorPackageName: com.pr0gramm.app] ] (release request)
05-08 22:24:15.333  1448  1461 W System  : A resource failed to call release. 
05-08 22:24:15.344  1448  1461 I chatty  : uid=1000(system) FinalizerDaemon identical 24 lines
05-08 22:24:15.344  1448  1461 W System  : A resource failed to call release. 
05-08 22:24:15.453  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1885 onStartInput(EditorInfo{inputType=0x8c0a1(WebEditText) imeOptions=0x12000002 privateImeOptions=null actionName=GO actionLabel=null actionId=0 initialSelStart=0 initialSelEnd=0 initialCapsMode=0x0 hintText=null label=null packageName=org.bromite.bromite fieldId=-1 fieldName=null extras=null}, true)
05-08 22:24:15.453  5970  5970 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2077 checkRepeatedly = true, unlocked = true
05-08 22:24:15.453  5970  5970 W SessionManager: SessionManager.beginSession():53 Try to begin an already begun session [INPUT_SESSION], end it first
05-08 22:24:15.809  1040  1040 W Layer   : [Bounds for - org.bromite.bromite/com.google.android.apps.chrome.Main#0] sync point 182 wait timeout 1008514062 for org.bromite.bromite/com.google.android.apps.chrome.Main#0
05-08 22:24:16.823  1040  1040 W Layer   : [Bounds for - org.bromite.bromite/com.google.android.apps.chrome.Main#0] sync point 182 wait timeout 2022374634 for org.bromite.bromite/com.google.android.apps.chrome.Main#0
05-08 22:24:17.836  1040  1040 W Layer   : [Bounds for - org.bromite.bromite/com.google.android.apps.chrome.Main#0] sync point 182 wait timeout 3036163905 for org.bromite.bromite/com.google.android.apps.chrome.Main#0
05-08 22:24:18.850  1040  1040 W Layer   : [Bounds for - org.bromite.bromite/com.google.android.apps.chrome.Main#0] sync point 182 wait timeout 4049994321 for org.bromite.bromite/com.google.android.apps.chrome.Main#0
```

### Describe the bug

Some apps and system settings don't have touch.
They act like frozen, but the navigation gestures do work.
Specific pages in the bromite browser.

Affected are:
- Issues view in the github app
- Bitwarden
- Android standard browser choose screen
- app permission allowing screen
- In bromite browser `chrome://flags`

### Steps to reproduce the bug

1. Start bitwarden
2. Start the github app and open a project issue
3. go to the "standard browser choose"-dialogue
4. Try to answer the app permission request dialogue
5. In the Bromite browser visit `chrome://flags`

### Expected behavior

Working touch

**Comment by csagan5** [comment] 2022-05-13 19:34
> ### Can the bug be reproduced with corresponding Chromium version?
> No

Have you installed the Chromium SystemWebView to make these tests?

> * In bromite browser `chrome://flags`

If this bug is about the SystemWebView, how can you mention here Bromite browser?

**Comment by MartinX3** [comment] 2022-05-13 19:56
> > * In bromite browser `chrome://flags`
> 
> If this bug is about the SystemWebView, how can you mention here Bromite browser?

The bromite browser where it happens uses the bromite systemwebview?

**Comment by csagan5** [comment] 2022-05-13 20:27
The Bromite browser does not use the Bromite SystemWebView.

**Comment by MartinX3** [comment] 2022-05-13 21:48
That's what I'm saying
I got the same bug in the bromite browser flags site.

In Chrome it just stops a short time and then continues to work. Like a short lag or freeze.

In bromite it's frozen forever of if I trigger it with the systemwebview using bromite.

**Comment by csagan5** [comment] 2022-05-14 10:03
Duplicate of #1837

**Closed by csagan5** 2022-05-14 10:03 UTC
Labels: bug, needs-triage

**Comment by MartinX3** [comment] 2022-05-14 10:05
@csagan5 
why it is a duplicate?
I don't have choppy scrolling.
I have no scrolling/a freeze if I trigger this bug.

**Comment by csagan5** [comment] 2022-05-14 10:28
Ok, so it does not resume at all even after some time.

Please open a new bug and make it only about the browser, not the SystemWebView; make sure you report the filtered `adb logcat` output as the bug issue template suggests.

One interesting log line you have is `chromium: [ERROR:tile_manager.cc(833)] WARNING: tile memory limits exceeded, some content may not draw` but I can't understand whether it is about the SystemWebView or the browser.

**Comment by MartinX3** [comment] 2022-05-14 10:44
> Ok, so it does not resume at all even after some time.
> 
> Please open a new bug and make it only about the browser, not the SystemWebView; make sure you report the filtered `adb logcat` output as the bug issue template suggests.
> 
> One interesting log line you have is `chromium: [ERROR:tile_manager.cc(833)] WARNING: tile memory limits exceeded, some content may not draw` but I can't understand whether it is about the SystemWebView or the browser.

I already separated the error messages.
The `tile memory limits exceeded` error is from the SystemWebView as written above the log.

But I already moved back to the standard systemwebview and sadly currently have no time to further experiment with my only phone.

Thank you for your help.
