### ISSUE TITLE
Ability to add exceptions in always-in-incognito mode

### ISSUE THREAD

**Issue by KatoriYuu** [bromite/bromite#1334] opened 2021-08-11 16:12 UTC
### Is your feature request related to privacy? 
It is, but my request also means to improve usability.

### Is there a patch available for this feature somewhere?
I haven't found anything similar.

### Describe the solution you would like
By default I disable javascript and cookies in all sites, except some that I frequently visit. This sometimes might cause some breakages, and the workaround was opening those sites in private tabs and temporarily allowing them to have access to necessary permissions, which needed more time and operations. Therefore I think that always opening sites in incognito mode would be the best solution for this issue; and to save the time used for re-login, there should be an option to exclude frequently visited sites.

### Describe alternatives you have considered
I haven't thought of any.

**Comment by csagan5** [comment] 2021-08-12 07:00
The description is not clear here:
> there should be an option to exclude frequently visited sites.

Exclude them from what?

**Comment by KatoriYuu** [comment] 2021-08-12 08:05
@csagan5 The option would let websites to be opened in normal tabs, which means the sites' data could be retained if the tabs were closed.

**Comment by csagan5** [comment] 2021-08-12 09:50
Duplicate of #864

**Closed by csagan5** 2021-08-12 09:50 UTC
Labels: enhancement, needs-triage
