### ISSUE TITLE
Remote DevTools HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by darylrobert** [bromite/bromite#526] opened 2020-04-16 10:29 UTC
### Bromite version

Version: 81.0.4044.106
Arch: arm64
Android version: 9.0
Device model: ginkgo M1908C3JG

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?

Yes, 81.0.4044.106

### Can the bug be reproduced with corresponding Chromium version?

No, 81.0.4044.106

### Is the bug a crash?

No

### Describe the bug

Remote DevTools in Bromite gives HTTP/1.1 404 Not Found

### Steps to reproduce the bug

open chrome in desktop
> adb connect 192.168.1.100:5555
open desktop devtools > overflow button > more tools > remote device
wait some seconds and inspect open tabs on remote device

### Expected behavior

Remote DevTools is available

### Screenshots
Chromium:
![chromium_arm64_81 0 4044 106_devtools404](https://user-images.githubusercontent.com/61579747/79445876-f4e90c80-800f-11ea-8b73-8f2275ad14f5.png)
Bromite:
![bromite_arm64_81 0 4044 106_devtools404](https://user-images.githubusercontent.com/61579747/79445882-f7e3fd00-800f-11ea-8da8-fc03f84c6111.png)

**Comment by csagan5** [comment] 2020-04-16 12:47
Cannot reproduce, works fine here. Perhaps you have a proxy or similar interception mechanism?

**Comment by darylrobert** [comment] 2020-04-18 04:23
Your guess is as good as mine. I have no idea why. Probably will try test against a freshly wiped Android sometime.

**Comment by csagan5** [comment] 2020-04-18 08:45
That URL is reachable and there is no 404. You might have some malicious certificate installed. Does it happen equally on 4G or wifi?

**Comment by csagan5** [comment] 2020-04-28 22:33
> If I had to guess though, it'd be that the inspector resources were marked as "non-critical" in Android builds and are no longer being bundled into local builds by default.

@nikolowry Chromium moved the devtools resources into a third-party git submodule and indeed there is a DFM for it. Bromite disables it with the `dfmify_dev_ui=false` GN arg, which causes `chrome/dev_ui_resources.pak` to be included in the APK. Perhaps you could try building with that set to `true` (the default) to see if problem persists?

There are no other relevant changes as far as I can recollect, and both Bromite and the corresponding Chromium builds use this flag so they should both be affected (have you checked?)

As I [wrote here](https://github.com/Eloston/ungoogled-chromium/issues/1018#issuecomment-620889587) the address devtools://devtools/remote/serve_rev/@4738de409d42eeb4071c354860aae28c8ab13ce6/inspector.html?remoteVersion=81.0.4044.106 is accessible.

**Comment by csagan5** [comment] 2020-05-12 19:46
Fixed in `83.0.4103.46`.

**Closed by csagan5** 2020-05-12 19:46 UTC
Labels: bug
