### ISSUE TITLE
Need enhanced filtering

### ISSUE THREAD

**Issue by tw-e** [bromite/bromite#328] opened 2019-06-26 15:04 UTC
@csagan5 

**Is your feature request related to privacy?**
No.

**Is there a patch available for this feature somewhere?**
Maybe.

**Describe the solution you'd like**
https://adblockplus.org/en/subscriptions
I hope that you can add to the filter list for the country, 
because some ads are only specific to the nature of the region, 
so I hope you can add it.

**Other**
Because chromium is now the latest version of V77, 
can you please upgrade to that version at one time?

thank you!

**Comment by csagan5** [comment] 2019-06-26 17:53
Duplicate of #2

**Closed by csagan5** 2019-06-26 17:53 UTC
Labels: duplicate
