### ISSUE TITLE
Feature Request: Open custom links in incognito mode

### ISSUE THREAD

**Issue by pixincreate** [bromite/bromite#843] opened 2020-12-08 07:45 UTC
I know that this sounds pretty lame, but whenever you open a link from another app, in my opinion, should open in incognito mode. 

But the thing, that is happening is that, when **OPEN ALWAYS IN INCOGNITO** is selected, you cannot open the normal tab but incognito ONLY w.r.t to the latest update. Also, so the links will now open in incognito along with the app itself.

![IMAGE](https://user-images.githubusercontent.com/69745008/101454347-d8ab2e80-3956-11eb-8446-948f31ec83d5.png)

What I'm asking?
An option or a fix to open **custom links** from **other apps** to open directly in **incognito** rather than making the entire all work only in incognito mode. (For example: Firefox by default had an option to open the links in a custom private tab)

**Comment by csagan5** [comment] 2020-12-08 22:57
Duplicate of #728

**Closed by csagan5** 2020-12-08 22:57 UTC
