### ISSUE TITLE
Crash when opening a new tab shortcut in always-incognito mode

### ISSUE THREAD

**Issue by fitittome** [bromite/bromite#503] opened 2020-03-02 09:21 UTC
### Bromite version

Version: 80.0.3987.118
Arch: arm
Android version: 9, LineageOS 16.0 (self build as of Feb 2020)
Device model: Samsung SM-G900F

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
No
The feature is not available in the Chromium version.

### Is the bug a crash?
Yes
Logcat attached

### Describe the bug
Home screen shortcuts don't work if 'Settings>Privacy>Open links in incognito tabs always' is ticked.

### Steps to reproduce the bug
- Ensure 'Settings>Privacy>Open links in incognito tabs always' is not ticked.
- Open bromite, goto homepage of favorite site (https://www.theguardian.com)
- Tap triple dot and Add to Home Screen
- Verify placement of shortcut icon and tap to ensure that its functional.

:)

- 'Settings>Privacy>Open links in incognito tabs always' and tick because we like private default.
- Quit bromite properly.
- Tap the Home Screen Bromite shortcut icon, nothing happens.
- Tap again and a pop up displays: Bromite keeps stopping.....

### Expected behavior
I would expect the shortcut to open in an incognito tab.

### Logcat
[logcat.txt](https://github.com/bromite/bromite/files/4274488/logcat.txt)

**Comment by csagan5** [comment] 2020-03-02 20:05
The crash is:

```
03-02 08:59:28.613 W/System.err(23811): java.lang.IllegalStateException: Attempting to open tab in wrong model
03-02 08:59:28.614 W/System.err(23811): 	at AA0.b(PG:44)
03-02 08:59:28.614 W/System.err(23811): 	at nA0.b(PG:42)
03-02 08:59:28.614 W/System.err(23811): 	at gA0.a(PG:125)
03-02 08:59:28.614 W/System.err(23811): 	at gA0.a(PG:3)
03-02 08:59:28.614 W/System.err(23811): 	at org.chromium.chrome.browser.ChromeTabbedActivity.a(PG:154)
03-02 08:59:28.614 W/System.err(23811): 	at as.a(PG:77)
03-02 08:59:28.614 W/System.err(23811): 	at zs.a(PG:70)
03-02 08:59:28.614 W/System.err(23811): 	at zs.b(PG:56)
03-02 08:59:28.614 W/System.err(23811): 	at org.chromium.chrome.browser.ChromeTabbedActivity.x(PG:22)
03-02 08:59:28.614 W/System.err(23811): 	at t10.run(PG:2)
03-02 08:59:28.614 W/System.err(23811): 	at j10.run(PG:7)
03-02 08:59:28.614 W/System.err(23811): 	at android.os.MessageQueue.nativePollOnce(Native Method)
03-02 08:59:28.614 W/System.err(23811): 	at android.os.MessageQueue.next(MessageQueue.java:326)
03-02 08:59:28.614 W/System.err(23811): 	at android.os.Looper.loop(Looper.java:160)
03-02 08:59:28.614 W/System.err(23811): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
03-02 08:59:28.614 W/System.err(23811): 	at java.lang.reflect.Method.invoke(Native Method)
03-02 08:59:28.614 W/System.err(23811): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
03-02 08:59:28.614 W/System.err(23811): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
03-02 08:59:28.617 F/chromium(23811): [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
```

**Comment by csagan5** [comment] 2020-03-03 18:06
Same stacktrace as #453

**Comment by csagan5** [comment] 2020-03-04 00:14
Duplicate of #453

**Closed by csagan5** 2020-03-04 00:14 UTC
