### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by 9ma9** [bromite/bromite#504] opened 2020-03-03 11:29 UTC
### Bromite version

Version: `76.0...`
Arch: `arm` or `arm64` or `x86`
Android version: (example: `9.0`)
Device model: (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView?
No

No support for SystemWebView installations is provided.

### Is the bug reproducible with latest version?
Yes
Do not report bugs which are not reproducible with latest version

### Can the bug be reproduced with corresponding Chromium version?
Yes
Please pick the same version of Chromium as Bromite from here: Chromium v80.0.3987.118
If the bug is reproducible then it might be a configuration issue or an upstream bug. Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first.

### Is the bug a crash?
No
If yes then individuate and post the logcat dump (remove privacy sensitive information, if any), otherwise remove this section.

### Describe the bug

Cannot download at all as download dialog box keeps popping up when attempting to, however nothing happens.
.

### Steps to reproduce the bug

1. Go to said file to download
2. Click on download
3. Scroll down to ?

### Expected behavior

Dialog box should pop up, you select destination, then download should start, instead of dialog re-appearing

**Comment by HigH-HawK** [comment] 2020-03-03 16:32
Seems to be related to #485

**Comment by csagan5** [comment] 2020-03-03 18:03
Duplicate of #485

**Closed by csagan5** 2020-03-03 18:03 UTC
