### ISSUE TITLE
Push notifications not working

### ISSUE THREAD

**Issue by asliwinski** [bromite/bromite#699] opened 2020-08-19 14:12 UTC
Bromite version
Version: 84.0.4147.132
Arch: arm64
Android version: (example: 10.0)
Device model: (example: VOG-L29)

Is this bug about the SystemWebView?
No

Is the bug reproducible with the latest version?
Yes, you can reproduce it at https://serviceworke.rs/web-push.html

Can the bug be reproduced with corresponding Chromium version?
NO, IT WORKS CORRECTLY IN CHROMIUM

Is the bug a crash?
No

Describe the bug
Push notifications don't show up. The permission granting procedure seems to work correctly.

Steps to reproduce the bug
Steps to reproduce the bug:

Go to https://serviceworke.rs/push-get-payload_demo.html
Click on 'Request sending a notification'
No notifications shows up
Expected behavior
Notification should show up

**Comment by csagan5** [comment] 2020-08-19 15:03
Duplicate of #698

**Closed by csagan5** 2020-08-19 15:03 UTC

**Comment by csagan5** [comment] 2020-08-19 15:04
It's working as intended; as written in previous issue, see F.A.Q.

**Comment by asliwinski** [comment] 2020-08-19 15:33
@csagan5 why don't you introduce a second type of build which would skip the GCM removal?
The feature has been requested by many users: https://github.com/bromite/bromite/issues/474
https://github.com/bromite/bromite/issues/630

**Comment by csagan5** [comment] 2020-08-19 18:58
@asliwinski first reason is that it would go against the core tenets of the project; including closed-source binaries that communicate with Play Services is not in line with this project. The second reason is that I have limited time and I cannot commit to customized builds, but I publish the patches with an open source license so that anybody can build their own customized version.

**Comment by download13** [comment] 2022-10-29 15:52
Perhaps it's worth moving this to a discussion as a lot of people seems to want to get push working on here.

Given the success of software like microg I suspect it's possible to write an open source connector for google or Mozilla's push providers that would let users enable this feature if they wanted to.

**Comment by csagan5** [comment] 2022-10-30 13:24
@download13 yes, open source connector + configurable push provider would be acceptable here. Feel free to open a discussion. What I would need in such cases is someone that can help with the patch maintenance across major releases as it becomes a small sub-project on its own.
