### ISSUE TITLE
app crash version: 83.0.4103.46

### ISSUE THREAD

**Issue by draxaris1010** [bromite/bromite#568] opened 2020-05-14 09:27 UTC
### Bromite version

Version: `83.0.4103.46`
Arch: `arm64`
Android version: `10`
Device model: `HD1903`
### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
I think so.

### Can the bug be reproduced with corresponding Chromium version?
I don't know.

### Is the bug a crash?
Yes

### logcat
```05-14 11:19:03.642  1548  2259 D OemSceneCallBlock: isCallBlockedWithUidIntent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=org.bromite.bromite cmp=org.bromite.bromite/com.google.android.apps.chrome.Main }, ResolveInfo{427fd6 org.bromite.bromite/com.google.android.apps.chrome.Main m=0x0}, false
05-14 11:19:03.642  1548  2259 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=org.bromite.bromite cmp=org.bromite.bromite/com.google.android.apps.chrome.Main} from uid 1000 pid 30336
05-14 11:19:03.669  1548  1581 D OpRestartProcessManager: updateSelf :  org.bromite.bromite, size : 30
05-14 11:19:03.699  1548  1605 I ActivityManager: Start proc 5041:org.bromite.bromite/u0a313 for activity {org.bromite.bromite/com.google.android.apps.chrome.Main}
05-14 11:19:03.706  5041  5041 E bromite.bromit: Not starting debugger since process cannot load the jdwp agent.
05-14 11:19:03.709  1548  2259 D OnePlusSmartBoostManager: writeHotCount org.bromite.bromite, pid=5041
05-14 11:19:03.713  1548  2259 E ScreenModeService: getAppToken AppWindowToken{a272db0 token=Token{90d3cf3 ActivityRecord{b3ec362 u0 org.bromite.bromite/com.google.android.apps.chrome.Main t3864}}}
05-14 11:19:03.713  1548  2259 E ScreenModeService: setRefreshRate token AppWindowToken{a272db0 token=Token{90d3cf3 ActivityRecord{b3ec362 u0 org.bromite.bromite/com.google.android.apps.chrome.Main t3864}}} rate 0
05-14 11:19:03.713  1548  2259 D OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{a272db0 token=Token{90d3cf3 ActivityRecord{b3ec362 u0 org.bromite.bromite/com.google.android.apps.chrome.Main t3864}}} pkgName org.bromite.bromite
05-14 11:19:03.713  1548  2259 D OpSlaNetlinkHelper: frontPackageChanged: org.bromite.bromite uid:10313 pid:5041 | com.android.settings uid:1000 pid:30336
05-14 11:19:03.714  1144  5068 E ANDR-RAMBOOST_SERVER: ramboost cmd_len = 93 cmd: iop_start -1 org.bromite.bromite /data/app/org.bromite.bromite-kdH-4HnoOjEnM_hKblTBGA== false
05-14 11:19:03.714  1144  5069 E ANDR-RAMBOOST_SERVER: ramboost cmd_len = 95 cmd: iop_start 5041 org.bromite.bromite /data/app/org.bromite.bromite-kdH-4HnoOjEnM_hKblTBGA== false
05-14 11:19:03.715  1548  1581 D Foreground_io: TOP_APP is ProcessRecord{1d88a86 5041:org.bromite.bromite/u0a313} uid is 10313
05-14 11:19:03.731  5041  5041 I bromite.bromit: [GL_OOM] ClampGrowthLimit 268435456
05-14 11:19:03.771  5041  5084 I cr_LibraryLoader: libraryName: /data/app/org.bromite.bromite-kdH-4HnoOjEnM_hKblTBGA==/base.apk!/lib/arm64-v8a/crazy.libchrome.so
05-14 11:19:03.786  5041  5041 E bromite.bromit: No implementation found for boolean J.N.M09VlOh_(java.lang.String) (tried Java_J_N_M09VlOh_1 and Java_J_N_M09VlOh_1__Ljava_lang_String_2)
05-14 11:19:03.787  5041  5041 E AndroidRuntime: Process: org.bromite.bromite, PID: 5041
05-14 11:19:03.787  5041  5041 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.bromite.bromite/org.chromium.chrome.browser.ChromeTabbedActivity}: android.view.InflateException: Binary XML file line #24 in org.bromite.bromite:layout/0_resource_name_obfuscated: Binary XML file line #24 in org.bromite.bromite:layout/0_resource_name_obfuscated: Error inflating class org.chromium.chrome.browser.omnibox.LocationBarPhone
05-14 11:19:03.787  5041  5041 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #24 in org.bromite.bromite:layout/0_resource_name_obfuscated: Binary XML file line #24 in org.bromite.bromite:layout/0_resource_name_obfuscated: Error inflating class org.chromium.chrome.browser.omnibox.LocationBarPhone
05-14 11:19:03.787  5041  5041 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #24 in org.bromite.bromite:layout/0_resource_name_obfuscated: Error inflating class org.chromium.chrome.browser.omnibox.LocationBarPhone
05-14 11:19:03.790  1548  5021 W ActivityTaskManager:   Force finishing activity org.bromite.bromite/com.google.android.apps.chrome.Main
05-14 11:19:03.791  1548  5021 D OpSlaNetlinkHelper: frontPackageChanged: com.android.settings uid:1000 pid:30336 | org.bromite.bromite uid:10313 pid:5041
05-14 11:19:03.791  1548  5088 D FrameworkEventCollector: recordAppIssue PN: org.bromite.bromite
05-14 11:19:03.796  5041  5075 E Perf    : Fail to get file list org.bromite.bromite
05-14 11:19:03.798  1548  1581 D OpRestartProcessManager: Duration is too short, ignore : 124 in org.bromite.bromite
05-14 11:19:03.815  1548  5052 I ActivityManager: Process org.bromite.bromite (pid 5041) has died: vis TOP 
05-14 11:19:03.837 30336 30336 D AppButtonsPrefCtl: Sending broadcast to query restart status for org.bromite.bromite
05-14 11:19:04.002  1548  5033 W AppOps  : Bad call: specified package org.bromite.bromite under uid 99910313 but it is really 10313
05-14 11:19:04.010  1548  5033 W AppOps  : Bad call: specified package org.bromite.bromite under uid 99910313 but it is really 10313
05-14 11:19:04.050  1548  5033 W AppOps  : Bad call: specified package org.bromite.bromite under uid 99910313 but it is really 10313
05-14 11:19:04.062 30336 30336 D AppButtonsPrefCtl: Got broadcast response: Restart status for org.bromite.bromite false
05-14 11:19:04.078 30336 30336 V BatteryUtils: package: org.bromite.bromite
05-14 11:19:04.290  1548  1581 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{b3ec362 u0 org.bromite.bromite/com.google.android.apps.chrome.Main t-1 f}
```

### Describe the bug
When opening the app it crashes immediately.
Probably caused by the memory boost function on 1+ phones. 

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Open Bromite
2. See error

### Expected behavior
The app should work.

**Comment by csagan5** [comment] 2020-05-14 09:28
Duplicate of #565

**Closed by csagan5** 2020-05-14 09:28 UTC
