### ISSUE TITLE
Some websites don't work correctly after logging in and restarting Bromite

### ISSUE THREAD

**Issue by ymcx** [bromite/bromite#1728] opened 2022-01-19 13:48 UTC
### Bromite version

Version: `96.0.4664.54` 
Arch: `arm64` 
Android version: `12.0` 
Device model: `A5000` 

### Flags

These are the flags changed under `chrome://flags`:

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?
No

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?

No

### Describe the bug

After succesfully logging in to Telegram Web (this bug also affects other websites like Facebook, see the link below) and then closing Bromite and reopening it, Telegram stops working correctly. Instead it displays a message that says it's "Waiting for network..."
While this error message is on, the client is unable to display the user any new messages, and the user is unable to send any new messages.
The error message doesn't disappear until the user clears the cookies used by the website.
I was also able to reproduce this bug on my Oneplus One (arm) running android 11.

Someone most likely having the same issue: https://github.com/bromite/bromite/discussions/1674

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to 'web.telegram.org/z'
2. Login
3. Close Bromite
4. Open Bromite
5. See error

### Expected behavior
Telegram should work correctly and display every new message as they come.

**Comment by uazo** [comment] 2022-01-19 14:33
Duplicate of #1693

**Closed** 2022-01-19 14:54 UTC
Labels: bug, needs-triage
