### ISSUE TITLE
Proxy page does not load

### ISSUE THREAD

**Issue by chromer030** [bromite/bromite#890] opened 2021-01-26 07:20 UTC
### Bromite version

Version: `88.0.4324.95`
Arch: `arm64`
Android version: `7.1.2`
Device model: `Lenovo`

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
It's not related to Chromium.

### Is the bug a crash?
No

### Describe the bug
1- Proxy page is broken and it is stuck on Loading... forever.

### Steps to reproduce the bug

Steps to reproduce the bug:
1 -Open chrome://proxy or from settings.

### Screenshots

![Screenshot_20210126-103237](https://user-images.githubusercontent.com/13361552/105812580-a8c9f000-5fc3-11eb-8221-c5a61ff39ef0.png)

**Comment by csagan5** [comment] 2021-01-26 21:25
I cannot reproduce this bug; please follow this documentation and see what errors are reported there in the development console: https://developers.google.com/web/tools/chrome-devtools/remote-debugging

**Comment by uazo** [comment] 2021-01-28 09:49
we need to add this line to `chrome/browser/resources/proxy_config.html`

`<script src="chrome://resources/js/assert.js"></script>`

as show here https://source.chromium.org/chromium/chromium/src/+/e2575bf8c6c0c0360862da29bcb4463f3118fe4f

here https://gist.github.com/uazo/94dde7027a559386d53d4a003548a58e the complete patch, it may be slightly different in some places as mentioned yesterday.

**Comment by csagan5** [comment] 2021-01-31 12:05
Fixed in `88.0.4324.141`.

**Closed by csagan5** 2021-01-31 12:05 UTC
Labels: bug
