### ISSUE TITLE
Tab Groups Not Working Properly , sometimes disappear.

### ISSUE THREAD

**Issue by Paras6408** [bromite/bromite#2227] opened 2022-07-30 03:31 UTC
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.
- [X] This is a bug report about the Bromite browser; not the website nor F-Droid nor anything else.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

Bromite v103.0.5060.140

### Device architecture

arm64-v8a

### Android version

12.1

### Device model

Galaxy A52

### Changed flags

No flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

1. No

### Describe the bug

The group tabs bottom panel disappeas sometimes need to open a new tab in group to be able to view it.

### Steps to reproduce the bug

Steps to reproduce:
Search google (anything)
Open 3 or more tabs in group
Scroll on one of the tabs
The Grouped Tabs bottom panel will disappear

### Expected behavior

It should be there only.

### Screenshots

IDH (I don't have)

**Comment by n-buna404** [comment] 2022-07-30 04:31
Are u depicting the behaviour of bottom panel disappearing when scrolling down? But if u scroll up the panel will appear again. This can be reproduced with corresponding Chromium version since it is a feature to provide more screen space not a bug.

**Comment by AdishSagarawat** [comment] 2022-08-05 10:36
Ok

**Comment by AdishSagarawat** [comment] 2022-08-05 10:37
You can close this...

**Closed** 2022-08-08 00:17 UTC
Labels: bug, needs-triage
