### ISSUE TITLE
Filters download version error

### ISSUE THREAD

**Issue by nerrixDE** [bromite/bromite#458] opened 2020-01-06 12:13 UTC
### Bromite version

Version: `79.0.3945.107`
Arch: `arm`
Android version: `10`
Device model: `GM1913`

### Is this bug about the SystemWebView?
No

No support for SystemWebView installations is provided.

### Is the bug reproducible with latest version?
Yes
Do not report bugs which are not reproducible with latest version

### Can the bug be reproduced with corresponding Chromium version?
No
Please pick the same version of Chromium as Bromite from here: https://github.com/bromite/chromium/releases
If the bug is reproducible then it might be a configuration issue or an upstream bug. Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first.

### Is the bug a crash?
No

### Describe the bug

Simple google ads don't get detected with adblock (+default filters) activated.
I get a half-screen-sized google or outbrain ad displayed.

### Steps to reproduce the bug

1. Go to https://www.heise.de/newsticker/meldung/Alsfelder-Stadtverwaltung-nach-Erpressungsversuch-wieder-am-Netz-4628651.html
or https://www.heise.de/amp/meldung/Alsfelder-Stadtverwaltung-nach-Erpressungsversuch-wieder-am-Netz-4628651.html?__twitter_impression=true
2. See the outbrain or google ad right before the news article text begins.

### Expected behavior
The ads get blocked
### Screenshots

Screenshots:
![](https://i.imgur.com/AVCToMZ.jpg)
![](https://i.imgur.com/4vl71Ff.jpg)

**Comment by csagan5** [comment] 2020-01-06 16:07
Cannot reproduce this issue. Please follow these steps to report more information:

1. close the app (with exit or swiping it away)
2. start `adb logcat | grep chromium`
3. start the app
4. wait about 10 seconds
5. report back here the output

**Comment by nerrixDE** [comment] 2020-01-06 16:29
Here is the relevant logcat output:
```
01-06 17:25:39.831   915 25797 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: startService() is called for serviceorg.bromite.bromite/org.chromium.content.app.SandboxedProcessService8
01-06 17:25:39.862  4679  4696 I cr_Linker: Using linker: org.chromium.base.library_loader.LegacyLinker
01-06 17:25:39.862   915 25797 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: unbindService is called for service : org.bromite.bromite/org.chromium.content.app.SandboxedProcessService8 and for client org.bromite.bromite
01-06 17:25:39.871   915 25797 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: unbindService is called for service : org.bromite.bromite/org.chromium.content.app.SandboxedProcessService7 and for client org.bromite.bromite
01-06 17:25:39.944  4679  4698 I chromium: [INFO:library_loader_hooks.cc(51)] Chromium logging enabled: level = 0, default verbosity = 0
01-06 17:25:40.440   915 25797 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: bindService is called for service : org.bromite.bromite/org.chromium.content.app.SandboxedProcessService4 and for client org.bromite.bromite
01-06 17:25:40.440   915 25797 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: total connections for service : org.bromite.bromite/org.chromium.content.app.SandboxedProcessService4are :1
01-06 17:25:40.487   915 25797 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: unbindService is called for service : org.bromite.bromite/org.chromium.content.app.SandboxedProcessService4 and for client org.bromite.bromite
01-06 17:25:40.488  3982  3982 I chromium: [INFO:adblock_updater_service.cc(86)] AdBlockUpdaterService: starting up. First update attempt will take place in 5 seconds. Next update attempt will take place in 604800 seconds. 
01-06 17:25:45.488  3982  3982 I chromium: [INFO:adblock_updater_service.cc(139)] AdBlockUpdaterService: MostRecentIndexedVersion = 
01-06 17:25:45.488  3982  3982 W chromium: [WARNING:adblock_updater_service.cc(179)] AdBlockUpdaterService: failed to convert version to time.
01-06 17:25:45.669  3982  3982 I chromium: [INFO:download_filters_task.cc(164)] DownloadFiltersTask: fetching URL 'https://www.bromite.org/filters/filters.dat' with method GET
01-06 17:25:45.963  3982  3982 I chromium: [INFO:download_filters_task.cc(189)] DownloadFiltersTask: downloaded 2432612 bytes in 474ms from 'https://www.bromite.org/filters/filters.dat' to '/data/user/0/org.bromite.bromite/cache/.org.chromium.Chromium.rfoEpC' with net_error 0 and error 0
01-06 17:25:45.963  3982  3982 I chromium: [INFO:adblock_updater_service.cc(229)] AdBlockUpdaterService: indexing filters with version 1.0.4.57098
01-06 17:25:45.964  3982  3982 I chromium: [INFO:ruleset_service.cc(448)] RulesetService: valid version: 0
```

**Comment by csagan5** [comment] 2020-01-06 18:45
@nerrixDE thanks for reporting back; I can now see that it's failing to update the filters because of a version error. Will check.

**Comment by csagan5** [comment] 2020-01-06 23:55
This issue is now fixed; close & re-open the app to get the updated filters.

**Closed by csagan5** 2020-01-06 23:55 UTC
Labels: adblock, bug

**Comment by nerrixDE** [comment] 2020-01-07 05:58
Works fine now, awesome!
