### ISSUE TITLE
black 3: orange strikes back

### ISSUE THREAD

**Issue by 314resqi** [bromite/bromite#572] opened 2020-05-14 19:22 UTC
### Bromite version

Version: 83.0.4103.53
Arch: arm64
Android version: 10
Device model: sm-m205fn

### Is this bug about the SystemWebView?
no

### Is the bug reproducible with latest version?
yes

### Can the bug be reproduced with corresponding Chromium version?
83.0.4103.53 idk
83.0.4103.46 no

### Is the bug a crash?
no

### Describe the bug
Black bar is still there, but now its labeled.
When my internets off, its says in my native language "no internet connection".
Then i turn my net on and the bar and status bar turns blue-purple-ish and it says "online again",
after 2 (or so) sec it dissapears

### Screenshots
http://imgur.com/gallery/8JcRIOO

**Comment by csagan5** [comment] 2020-05-15 06:50
Duplicate of #556

**Closed by csagan5** 2020-05-15 06:50 UTC
