### ISSUE TITLE
Clear data on exit button

### ISSUE THREAD

**Issue by Pavbc** [bromite/bromite#530] opened 2020-04-19 17:23 UTC
### Is your feature request related to privacy?
Yes

### Is there a patch available for this feature somewhere?
Sort of, brave browser desktop has a third tab on the "clear history" names "on exit" and that's what's it does, the user sets what data is to be cleaned and every time the exit button is pressed, that data is gone.

### Describe the solution you would like
Maybe the option to set data to be cleaned when exit button is pressed.
I know the "always incognito" and the "keep cookies only until exit" can both do similar, but I think letting the user choose what data will be cleaned and letting the user choose when to press the button is far more useful. Having control over what and when things happen is always good. I can be mistaken, but I don't think it would be a difficult thing to implement.

### Describe alternatives you have considered

Always incognito and clear cookies on exit are already implemented, but they serve a different propous. My ideia, is just a link between 2 already existing buttons: the clear data and the exit buttons.

**Comment by csagan5** [comment] 2020-04-21 07:11
This has already been asked multiple times, you can find the previous closed issues.

**Comment by csagan5** [comment] 2020-04-21 20:23
> It can be done at startup, after ChromeActivity.finishNativeInitialization() adding for example
> 
```
BrowsingDataBridge.getInstance().clearBrowsingData(
        new BrowsingDataBridge.OnClearBrowsingDataListener() {
	   @Override
            public void onBrowsingDataCleared() {
		Context context = ContextUtils.getApplicationContext();
		Toast toast = Toast.makeText(context, "Data cleanup", Toast.LENGTH_SHORT);
		toast.show();
            }
        },
	new int[] {
		BrowsingDataType.CACHE
		,BrowsingDataType.COOKIES
		,BrowsingDataType.FORM_DATA
		//,BrowsingDataType.HISTORY
		//,BrowsingDataType.PASSWORDS
		//,BrowsingDataType.SITE_SETTINGS
	}, TimePeriod.ALL_TIME);
```

@uazo the patch you propose would be better suited for the implementation of this feature here

**Comment by csagan5** [comment] 2020-04-21 20:25
Duplicate of #426

**Closed by csagan5** 2020-04-21 20:25 UTC
