### ISSUE TITLE
Respect #omnibox-ui-hide-steady-state-url-scheme-and-subdomains

### ISSUE THREAD

**Issue by Madis0** [bromite/bromite#97] opened 2018-07-26 09:50 UTC
I think Bromite should respect the state of the flag 
`#omnibox-ui-hide-steady-state-url-scheme-and-subdomains` (which hides `https://`, `www.`, `m.`) to hide both `https://` and `http://` accordingly when enabled.

While I understand your intentions may be address bar accuracy, [Google's marking released in 68](https://www.blog.google/products/chrome/milestone-chrome-security-marking-http-not-secure/), [future plans](https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure) and flag `#enable-mark-http-as` can communicate the security state better on a small screen, while showing the protocol alongside security icon may obscure the full domain or subdomain.

**Comment by csagan5** [comment] 2018-07-26 12:41
My intention is to not replace parts of the URL with browser-specific icons/conventions; users should not be educated to recognize the green padlock across different browsers but to read the URL.

I am sorry about the small screen but I disagree that security state is communicated better; the problem is also that the option disables everything at once, otherwise I would leave it in the preferred state by default.

(For the records, this is a patch taken from ungoogled-chromium).

I will see if it can be fixed by changing a default for the flag rather than hardcoding the flag value; if it is not possible, it will stay in the current state also because it is a feature of Bromite to not hide anything of the URL.

**Comment by Madis0** [comment] 2018-07-26 13:43
> My intention is to not replace parts of the URL with browser-specific icons/conventions; users should not be educated to recognize the green padlock across different browsers but to read the URL.

Don't forget that the URL does not tell the full story, such as whether the HTTPS is mixed or HTTP is in the same computer (localhost). But considering the audience and the usefulness for developers, I can see your point.

My personal preference - and apparently Google's too in the long term - is the nothing-or-red-triangle approach.

**Comment by csagan5** [comment] 2018-08-01 11:05
I checked the experiment feature you mention `omnibox-ui-hide-steady-state-url-scheme-and-subdomains`: it is a placeholder and I expect Chromium devs will notice and drop it already since it is doing nothing.

I also checked the code about the various flags and the patch used in Bromite: the various URL components hiding flags have been disabled permanently because they were not configurable by the user.

The alternative would be to develop flags to toggle these individual hiding options, but - to the lack of any option and rather accepting the upstream setting - I prefer the current defaults, which never lie, and I have no commitment to develop the flags.

> Don't forget that the URL does not tell the full story, such as whether the HTTPS is mixed or HTTP is in the same computer (localhost).

I don't think this works anymore with any modern browser. Mixed content is also disabled by properly written websites.

**Closed by csagan5** 2018-08-01 11:05 UTC
