### ISSUE TITLE
SD card not found / Download to default folder ?

### ISSUE THREAD

**Issue by sainmihai** [bromite/bromite#493] opened 2020-02-18 07:36 UTC
### Bromite version

Version: 80.0.3987.109
Arch: arm64
Android version: 10
Device model: OnePlus 7 GM1903

### Is this bug about the SystemWebView?
No

No support for SystemWebView installations is provided.

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

Please pick the same version of Chromium as Bromite from here: https://github.com/bromite/chromium/releases
If the bug is reproducible then it might be a configuration issue or an upstream bug. Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and do not forget to read [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines) first.

### Is the bug a crash?

No

### Describe the bug

I can't download any file from github or any other site.
Download location is default: **/storage/emulated/0/Download**
I had to install Chrome to download the previous version of Bromite 79.0.3945.139.
With this version I can download any file as expected.

### Steps to reproduce the bug

1. Go to https://github.com/bromite/bromite/releases
2. Click to download any apk file
3. See the pop-up with SD card not found / Download to default folder ?
4. Press Download. Nothing will happen.

### Expected behavior

File is not downloading in default location.

### Screenshots

If applicable, add screenshots to help explain your problem. Otherwise remove this section.
![Screenshot_20200218-094053](https://user-images.githubusercontent.com/61180396/74714349-1063b100-5233-11ea-9db2-a53f3c1be675.jpg)

**Comment by csagan5** [comment] 2020-02-18 22:48
Duplicate of #485

**Closed by csagan5** 2020-02-18 22:48 UTC
