### ISSUE TITLE
Sharing hub: use visible URL instead of canonical URL

### ISSUE THREAD

**Issue by Devocub** [bromite/bromite#2204] opened 2022-07-19 18:05 UTC
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

no

### Describe the solution you would like

Example: go to old.reddit.com and share link using Share feature in 3 dots menu. You'll see shared link is www.reddit.com, I guess it uses html tag link rel="canonical". I don't know if it can be completely different link. I suggest you to change behavior to use actual link from browser url field which is old.reddit.com

### Describe alternatives you have considered

no

**Comment by Devocub** [comment] 2022-07-28 19:50
Found another site which is broken
https://f-droid.org/en/packages/org.alberto97.ouilookup/
sharing this^ actualle shares <link rel="canonical" href="https://f-droid.org/">
just wtf

**Comment by csagan5** [comment] 2022-08-08 01:26
It is not broken, it has always worked like that by design in Chromium; I will change it in Bromite to use the visible URL, although there are some corner cases where that is not desired.

**Comment by csagan5** [comment] 2022-08-14 06:26
Fixed in `104.0.5112.91`.

**Closed by csagan5** 2022-08-14 06:26 UTC
Labels: enhancement
