### ISSUE TITLE
Open Links in Respective App in Always Incognito Mode. 

### ISSUE THREAD

**Issue by blogmangit** [bromite/bromite#2490] opened 2022-12-06 16:13 UTC
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

Don't Know

### Describe the solution you would like

At present in always incognito mode links are always open in bromite instead of their respective app such as reddit, youtube, github, facebook etc. Please introduce a feature so that links will open in external apps even in always incognito mode if possible a toggle option or something like that so that only users interested can avail the feature.

### Describe alternatives you have considered

Nothing Considered.

**Comment by csagan5** [comment] 2022-12-07 00:56
Duplicate of #2380

**Closed as not planned by csagan5** 2022-12-07 00:56 UTC
Labels: invalid
