### ISSUE TITLE
YouTube embedded video playback won't start

### ISSUE THREAD

**Issue by bluebarnacles** [bromite/bromite#467] opened 2020-01-16 13:14 UTC
### Bromite version

Version: 79.0.3945.123
Arch: arm64
Android version:  10
Device model: G011A (Pixel 2)

### Is this bug about the SystemWebView?

No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is the bug a crash?

No

### Describe the bug

When attempting to play a YouTube video embedded in a discourse comment, the video playback won't start. This also happens if you go straight to the YouTube embed URL.

### Steps to reproduce the bug

1. Go to https://bbs.boingboing.net/t/rating-the-30-most-evil-tech-companies/159001/5
2. Click the YouTube embed
3. Click play
4. Get error message "Your browser does not currently recognize any of the video formats available."

Here's the debug info:
{
  "ns": "yt",
  "el": "embedded",
  "cpn": "5M-6MrZA7aZRF251",
  "docid": "xEERq5tLiOY",
  "ver": 2,
  "referrer": "https://www.youtube.com/embed/xEERq5tLiOY?autoplay=1&feature=oembed&wmode=opaque",
  "cmt": "0",
  "ei": "ZWAgXs_-LsOskgbuu4TIBA",
  "fs": "0",
  "rt": "8.467",
  "of": "GC6OCn1lTVgpgJyrp2hYjw",
  "euri": "",
  "lact": 2,
  "cl": "289783401",
  "mos": 0,
  "state": "80",
  "vm": "CAEQABgEKiBKVmpsYXZfam82S0FEVWM4VUZzMThaRHE5dFpoWUdQVg",
  "volume": 100,
  "c": "WEB_EMBEDDED_PLAYER",
  "cver": "20200115",
  "cplayer": "UNIPLAYER",
  "cbr": "Chrome Mobile",
  "cbrver": "79.0.3945.116",
  "cos": "Android",
  "cosver": "9.0.0",
  "autoplay": "1",
  "hl": "en_US",
  "cr": "US",
  "len": "149",
  "fexp": "23735347,23744176,23804281,23819663,23827263,23835027,23837040,23837993,23839597,23842630,23847143,23848795,23855886,23856652,23857949,23859127,23859802,23859863,23861041,23861502,23866808,23868606,23869125,23870093,23871542,23871542,9449243",
  "feature": "oembed",
  "size": "588:412:2.625",
  "inview": "1",
  "conn": "3",
  "vct": "0.000",
  "vd": "NaN",
  "vpl": "",
  "vbu": "",
  "vpa": "1",
  "vsk": "0",
  "ven": "0",
  "vpr": "1",
  "vrs": "0",
  "vns": "0",
  "vec": "null",
  "vvol": "1",
  "vdom": "1",
  "vsrc": "0",
  "debug_error": {
    "errorCode": "fmt.noneavailable",
    "errorMessage": "This video format is not supported.",
    "Sp": "HTML5_NO_AVAILABLE_FORMATS_FALLBACK",
    "kh": "",
    "vA": "buildRej.1;a.1;d.1;f18.1;c18.1;f43.1;c43.1;f133.1;f140.1;c140.1;f242.0;c242.1"
  },
  "ismb": 13440000,
  "relative_loudness": "-17.551",
  "user_qual": "auto",
  "debug_videoId": "xEERq5tLiOY",
  "0sz": false,
  "op": "",
  "yof": false,
  "dis": "",
  "cgr": true,
  "debug_playbackQuality": "unknown",
  "debug_date": "Thu Jan 16 2020 05:09:01 GMT-0800 (Pacific Standard Time)"
}

### Expected behavior

Video playback begins.

**Comment by csagan5** [comment] 2020-01-16 23:25
This might be due to hardware acceleration being disabled for your Android version and architecture, see #445

**Comment by renlord** [comment] 2020-01-17 14:00
Works on the Fixed Version (i.e. *.116)

**Comment by bluebarnacles** [comment] 2020-01-17 16:38
The behavior is slightly different between Bromite 79.0.3945.123 and vanilla Chromium 79.0.3945.123.

On Bromite, the video doesn't start playing, saying that the video formats is unrecognized:

![Screenshot_20200116-041603](https://user-images.githubusercontent.com/5144579/72629048-637cd800-3904-11ea-90af-d0e9d3b34886.png)
![Screenshot_20200117-083328](https://user-images.githubusercontent.com/5144579/72629010-52cc6200-3904-11ea-9339-d2225efda652.png)

On vanilla Chromium a few frames play, then the browser crashes and video playback displays an error occurred:

![Screenshot_20200117-083257](https://user-images.githubusercontent.com/5144579/72629197-ab9bfa80-3904-11ea-8f3f-cb6b0e2fa36f.png)
![Screenshot_20200117-083317](https://user-images.githubusercontent.com/5144579/72629210-b3f43580-3904-11ea-84d4-d327e32b3142.png)

**Comment by bluebarnacles** [comment] 2020-01-17 16:39
Here's a shot of the first moment of the video playing in vanilla Chromium 79.0.3945.123:

![Screenshot_20200117-083249](https://user-images.githubusercontent.com/5144579/72629317-edc53c00-3904-11ea-8a09-f5e48c829f63.png)

**Comment by csagan5** [comment] 2020-01-17 21:30
@bluebarnacles in the Chromium version it crashes the sandboxed process (assumption that can be verified with logcat), that's why in Bromite the hardware acceleration is disabled, see #445

> Works on the Fixed Version (i.e. *.116)

@renlord looks like it doesn't here for @bluebarnacles with Bromite's build of Chromium (`79.0.3945.123`); I assume you tested with your own Chromium build?

**Comment by renlord** [comment] 2020-01-18 00:16
> > Works on the Fixed Version (i.e. *.116)
> 
> @renlord looks like it doesn't here for @bluebarnacles with Bromite's build of Chromium (`79.0.3945.123`); I assume you tested with your own Chromium build?

Yes, my own Vanadium build.

**Comment by csagan5** [comment] 2020-01-19 05:36
@renlord could you please also test Bromite's current build of Chromium?

**Comment by csagan5** [comment] 2020-01-26 16:42
@bluebarnacles can you please check behavior with `79.0.3945.139`?

**Comment by bluebarnacles** [comment] 2020-01-26 18:26
Yes, is fixed in Bromite 79.0.3945.139, now Bromite's behavior matches the upstream behavior of playing about 2 seconds then crashing the sandbox.

**Comment by csagan5** [comment] 2020-01-27 10:06
@bluebarnacles great! Thanks for testing.

Can you please set the `#disable-accelerated-video-decode` flag, verify with `chrome://gpu` that HW acceleration is disabled for video decoding and repeat the test?

**Comment by bluebarnacles** [comment] 2020-01-27 15:01
Ok, with 79.0.3945.139 I set the flag to disable accelerated video decode, and verified that chrome://gpu displays "Video Decode: Software only. Hardware acceleration disabled".

The behavior is back to this bug description: the linked video does not play at all, with the message "Your browser does not currently recognize any of the video formats available." Also, videos on other sites work again.

**Comment by csagan5** [comment] 2020-01-28 09:11
@bluebarnacles then this bug is a duplicate of #445

For some videos hardware acceleration is necessary; you would have to switch to the arm version until upstream fixes it.

**Closed by csagan5** 2020-01-28 09:11 UTC
