### ISSUE TITLE
Add searx as a search engine.

### ISSUE THREAD

**Issue by justworks007** [bromite/bromite#662] opened 2020-07-30 06:19 UTC
### Is your feature request related to privacy?

No.

### Is there a patch available for this feature somewhere?

Not that I know of.

### Describe the solution you would like

Add searx as a search engine with the ability to change instances.

### Describe alternatives you have considered

Setting searx as a home page.

**Comment by csagan5** [comment] 2020-07-30 06:23
Duplicate of #91

**Closed by csagan5** 2020-07-30 06:23 UTC
