### ISSUE TITLE
Webrtc call not working

### ISSUE THREAD

**Issue by gothmog123** [bromite/bromite#127] opened 2018-09-16 10:23 UTC
Video works but I think there's a problem with capturing the microphone. Firefox works on the same service.

Keep up the great work, this is the best browser on android.

**Comment by vashin1** [comment] 2018-09-16 21:45
I had zero problems granting permissions to my camera and microphone on WebRTC, I also confirmed that sound and video capture works just fine on the latest release of Bromite - https://webrtc.github.io/samples/src/content/devices/input-output/

Zero issued on Android 9.0 on my Pixel 2, perhaps it's a system issue on your end but the app is fine. I don't think there is any bugs here.

**Comment by gothmog123** [comment] 2018-09-17 08:52
Thanks, I have 0 clue what could be wrong with my device:(

It's Lineage OS 15 by the way.

**Comment by csagan5** [comment] 2018-09-17 09:09
I cannot reproduce as well, closing.

**Closed by csagan5** 2018-09-17 09:09 UTC
Labels: invalid
