### ISSUE TITLE
Adblock

### ISSUE THREAD

**Issue by Karma2424** [bromite/bromite#427] opened 2019-12-01 10:49 UTC
### Bromite version

Version: 78.0.3904.119
Arch: arm64
Android version: 8.0
Device Name: S7 edge

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?

Feature Not Available in Chromium

### Is the bug a crash?
No

### Describe the bug
Adblock being over protective

### Steps to reproduce the bug

1. Make sure that your ad lock is enabled
2. Go to: https://kissmanga.com/Manga/Solo-Leveling/Chapter-095?id=569993

### Expected behavior
To see the chapter

### Screenshots
Adblock enabled:
![Screenshot_20191201-154929_Bromite](https://user-images.githubusercontent.com/58363516/69912891-01e8d300-1456-11ea-9ff7-96a5be66b8ae.jpg)
Adblock disable:
![Screenshot_20191201-155044_Bromite](https://user-images.githubusercontent.com/58363516/69912900-2cd32700-1456-11ea-970a-dea21ffc9dac.jpg)

**Comment by csagan5** [comment] 2019-12-01 11:45
Duplicate of #423

**Closed by csagan5** 2019-12-01 11:45 UTC
