### ISSUE TITLE
Secure DNS enabled without templates

### ISSUE THREAD

**Issue by ABK4793** [bromite/bromite#761] opened 2020-10-02 22:08 UTC
### Bromite version

Version: `Bromite 86.0.4240.66`
Arch: `arm64` 
Android version: (example: `10.0`) Oxygen OS 10.3.4.GM21AA

Device model: (example: `GM - 1911`)

### Is this bug about the SystemWebView?
Not sure

### Describe the bug
# The latest update thinks the device is offline all the time.

### Steps to reproduce the bug

Steps to reproduce the bug:
2. Click on '...'
3. Scroll down to '...'

**Comment by ABK4793** [comment] 2020-10-02 22:11
https://drive.google.com/file/d/1Mb6BSP3Gr07J1j2wiFBjXq7MX3YMHRSi/view?usp=drivesdk

**Comment by ABK4793** [comment] 2020-10-02 22:12
https://drive.google.com/file/d/1MXtGtL5XIZsL4nEs3nGaDpO15MC7TTIZ/view?usp=drivesdk

**Comment by ABK4793** [comment] 2020-10-02 22:14
https://drive.google.com/file/d/1Mf_4xNqK0wBttL3Rsp0L_bFwlNQi0zKl/view?usp=drivesdk

**Comment by stevenchingch** [comment] 2020-10-03 00:54
Probably caused by this setting
Bromite -> Settings -> Privacy -> Use secure DNS
Changing to automatic or entering your own secure DNS should work

**Comment by creatorofthesky** [comment] 2020-10-03 02:33
Getting the same issue here regardless of secure dns configurations, VPN, using wifi or cellular. Meanwhile other apps are running fine without issue such  i.e. vandium. I am currently using the pixel 3 with graphene os installed on the latest android 11 update. If you wish for me to test anything feel free to ask!

**Comment by stevenchingch** [comment] 2020-10-03 05:48
Interesting. For me, setting the DNS setting to automatic fixed it for me on the latest version, but another problem is that the safe browsing option seems to crash Bromite (reported by other users). I installed an older version of Bromite for now.

**Comment by leophys** [comment] 2020-10-03 08:51
I can confirm on my side that the issue is resolved when the secure DNS is changed from custom to a commercial one (I'm using cloudflare's 1.1.1.1)

**Comment by dsoumen65** [comment] 2020-10-03 08:58
First i changed it to cloudfare still my problem persist then change to google public dns then the issue solved...may be my isp don't support cloudfare

**Comment by ABK4793** [comment] 2020-10-03 08:58
Ya, Changing DNS to Cloudfare.
Seems to solve this issue for now.

**Comment by csagan5** [comment] 2020-10-03 11:08
The workaround until next release is to disable secure DNS, or configure a DoH provider, or set it to automatic.

If it does not work after changing the settings then restart your browser.

**Comment by csagan5** [comment] 2020-10-03 17:02
Fixed in `86.0.4240.70`.

**Closed by csagan5** 2020-10-03 17:02 UTC

**Comment by Sanjibbapu** [comment] 2024-10-16 09:11
> ### Bromite version
> Version: `Bromite 86.0.4240.66` Arch: `arm64` Android version: (example: `10.0`) Oxygen OS 10.3.4.GM21AA
> 
> Device model: (example: `GM - 1911`)
> 
> ### Is this bug about the SystemWebView?
> Not sure
> 
> ### Is the bug reproducible with latest version?
> ### Can the bug be reproduced with corresponding Chromium version? yes
> ### Is the bug a crash?
> ### Describe the bug
> # The latest update thinks the device is offline all the time.
> ## Using Custom DNS / SECURE DNS causes this , switching to commercial (1.1.1.1) solves the problem.
> ### Steps to reproduce the bug
> Steps to reproduce the bug:
> 
> 1. Go to '...'
> 2. Click on '...'
> 3. Scroll down to '...'
> 4. See error
> 
> ### Expected behavior
> ### Screenshots
