### ISSUE TITLE
CAF SWE improvements

### ISSUE THREAD

**Issue by dimqua** [bromite/bromite#5] opened 2017-10-18 22:30 UTC
Would be nice to have [these patches](https://www.codeaurora.org/projects/all-active-projects/chromium-browser-snapdragon) integrated as well. At least some of them, although they may be a bit outdated in general.

**Comment by csagan5** [comment] 2017-10-18 22:38
Are any of them related to privacy? If not I am afraid they have to go the upstream way to Chromium, not on topic for Bromite

**Comment by dimqua** [comment] 2017-10-18 23:02
In particular, yes, that's why they [recommended by EFF](https://www.eff.org/deeplinks/2016/11/delivering-privacy-badger-and-https-everywhere-mobile-users-warp-speed). Although they may [significantly improve](https://www.reddit.com/r/Android/comments/5os3oh/in_my_quest_turned_fixation_to_find_the_best_caf/) performance on Snapdragon-based devices, unfortunable, they are no plans to upstream them AFAIK.

>not on topic for Bromite

I'm asking because I'm just not aware about any open-source and up-to-date Snapdragon-optimized Chromium builds. Most of them are proprietary.

**Comment by csagan5** [comment] 2017-10-18 23:57
WARP browser is not the same thing as CAF patchset. I checked the patches link you posted a couple times, there's nothing related to privacy there. WARP has not related any patches, completely closed source.

I think there's some confusion here; I suggest you submit a a PR with the privacy-related patches for Chromium.

**Comment by dimqua** [comment] 2017-10-19 00:36
If this is true, then I don't know how to explain that this [CAF's Chromium build](https://github.com/bamless/chromium-swe-builds) contain exactly the same features which EFF describe, notably "Web Defender" and "Secure Connect".

**Comment by csagan5** [comment] 2017-10-19 05:48
@dimqua that build contains CAF patches **and** other patches that authors have not published (they have published no patches at all)

**Comment by dimqua** [comment] 2017-10-19 11:07
This is unlikely, IMHO, since there are a lot of CAF Chromium builds and almost all of them contains this features too. This is just one example, others can be found on Play Store, etc.

If Code Aurora patches does not include these features, they may still be present in their git tree, see: https://wiki.codeaurora.org/xwiki/bin/Chromium+for+Snapdragon/Beta+Build+Instructions

But, in this case, this features can't be added to Bromite easly. Or any other custom Chromium build, unfortunable.

FYI, their latest branch [is based on Chromium 60](https://source.codeaurora.org/quic/chrome4sdp/chromium/src/log/?h=m60).

**Comment by csagan5** [comment] 2017-11-08 19:58
@dimqua the actual security/privacy patches might be here: https://portland.source.codeaurora.org/patches/quic/chrome4snapdragon/sba/

But I need someone to submit clean patches about privacy/security. No idea where to pick them there.

**Comment by dimqua** [comment] 2017-11-09 01:21
@csagan5 they are outdated and [always](https://portland.source.codeaurora.org/patches/quic/chrome4snapdragon/README) will be:

>[deprecated] The sba directory contains bundles of information that didn't fit elsewhere.
Basically, they were tarballs of patch sets for experiments or one-offs that we wanted to
share.

**Comment by csagan5** [comment] 2017-11-09 07:16
That's not the problem. The problem is that I can't find any track of privacy or security enhancement.

**Comment by csagan5** [comment] 2017-11-24 21:54
Good news. I have fetched the codeaurora git repo and compared the differences, and could find the commits there.

They do not publish the patches individually, three are like more than 500 commits to be checked. I think I might pick something both for Snapdragon enhancements and privacy-related.

**Comment by csagan5** [comment] 2017-12-03 23:19
A patch I might be able to recover is #18. The rest seems quite messy and outdated compared to current codebase.

**Comment by dimqua** [comment] 2017-12-03 23:34
>quite messy and outdated

```Web Defender``` and ```Secure Connect``` as well?

**Comment by csagan5** [comment] 2018-02-19 19:29
@dimqua they need even more work to be restored.

Closing this as no plans to work on this.

**Closed by csagan5** 2018-02-19 19:29 UTC
