### ISSUE TITLE
Importing Bookmarks requires cam & mic permissions

### ISSUE THREAD

**Issue by bocekm** [bromite/bromite#200] opened 2018-12-13 14:37 UTC
**Bromite version**

Version: `71.0.3578.88`
Arch: `arm64`
Android version: `8.1.0 (LineageOS 15.1)`

**Is the bug reproducible with latest version?**
`Yes`

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No

**Describe the bug**
When trying to import bookmarks, Bromite asks for permission to take pictures, record video and record audio. I haven't given the permission resulting in not being able to import bookmarks. I see no reason to require these permissions for bookmark import.

**To Reproduce**
1. Click on the three dots
2. Click on `Bookmarks`
3. Click on the three dots
4. Click on `Import`
5. See two requests: `Allow Bromite to take pictures and record video?` and `Allow Bromite to record audio?`

**Expected behavior**
To be able to import bookmarks without giving Bromite the in my opinion unrelated permissions.

**Comment by csagan5** [comment] 2018-12-14 08:43
The minimum needed permissions are:
* `READ_EXTERNAL_STORAGE`

Additional permissions that are currently requested:
* `CAMERA`
* `RECORD_AUDIO`

I had already disabled `READ_CONTACTS` in the past so that is no more an issue.

**Comment by csagan5** [comment] 2018-12-14 18:19
Will be fixed in `71.0.3578.98` (not yet released)

**Comment by bocekm** [comment] 2018-12-15 00:14
Thank you for the quick resolution.

**Closed** 2018-12-16 06:30 UTC

**Comment by bocekm** [comment] 2018-12-18 10:54
May I ask for a link to the fix you did in Chromium? I'm just curious how are these things fixed.

**Comment by csagan5** [comment] 2018-12-18 22:56
> Thank you for the quick resolution.

It was incidental, but you're welcome.

@bocekm you can find the [patch in the next tag](https://github.com/bromite/bromite/blob/71.0.3578.101/patches/BRM069_Reduce-permissions-needed-for-bookmarks-import-export.patch), I merged it to a previous patch with similar intent; normally it would be in the tag of its release.

Can you confirm that the issue is solved since `71.0.3578.98`?

**Comment by bocekm** [comment] 2018-12-18 23:00
Thanks, I didn't see changes to the bookmark patch in the commit for `71.0.3578.98` so I thought you fixed it in Chromium and just rebased Bromite.

Yeah, it's solved in `71.0.3578.98`.
