### ISSUE TITLE
chrome://flags is slow to load

### ISSUE THREAD

**Issue by GuyInTheShadows** [bromite/bromite#173] opened 2018-11-04 14:23 UTC
**Bromite version**

Version: `70.0.3538.87`
Arch: `arm64`
Android version: `8.1`

**Is the bug reproducible with latest version?**
Yes.

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
No.

**Is the bug a crash?**
No.

**Describe the bug**
`chrome://flags` page is slow to start and sluggish. See screenshot below.

**To Reproduce**

1. Go to `chrome://flags`.
2. It takes approximately 15 seconds to load up.
3. After that some functions are slow and unresponsive like `Search flags`.

**Expected behavior**
It should load `chrome://flags` page almost instantly, like on previous versions. Also functions should work smoothly. Other `chrome://` pages works correctly.

**Screenshots**
`chrome://flags` when it's loading up:
![flags](https://user-images.githubusercontent.com/44618665/47962861-a1f1e400-e02b-11e8-8a52-fba8f301a70e.png)

**Comment by csagan5** [comment] 2018-11-04 14:49
I also noticed this slowness, however this part is not true:

> Can the bug be reproduced with corresponding Chromium version?
> No.
> 

The issue can be perfectly reproduced with Chromium.

**Comment by csagan5** [comment] 2018-11-05 08:44
This has been fixed in next release `70.0.3538.95` (not yet released).

**Closed by csagan5** 2018-11-05 08:44 UTC

**Comment by koukichi7010** [comment] 2022-06-29 08:02
This has been a problem to me too since v102 until the newest one v102.0.5005.96
