### ISSUE TITLE
bromite crashes immediately on open

### ISSUE THREAD

**Issue by petep0p** [bromite/bromite#712] opened 2020-08-24 07:45 UTC
### Bromite version

Version: 85.0.4183.82
Arch: arm64
Android version: 8.0
Device model: SM-G92A

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
yes

### Can the bug be reproduced with corresponding Chromium version?
no

### Is the bug a crash?
yes

### Describe the bug
bromite will not open. crashes immediately whenever attempting to launch.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. launch app
2. see crash

### Expected behavior
1. launch app
2. fall down various rabbit holes browsing for hours

### Screenshots
n/a

**Comment by csagan5** [comment] 2020-08-24 08:02
Duplicate of #565 

If you can inspect the logcat you could confirm that it's the same crash. There is a workaround there (reinstall without clearing data)

**Closed by csagan5** 2020-08-24 08:02 UTC

**Comment by petep0p** [comment] 2020-08-26 08:21
> Duplicate of #565
> 
> If you can inspect the logcat you could confirm that it's the same crash. There is a workaround there (reinstall without clearing data)

not sure how best to narrow down the logcat output to something usable, but the workaround worked so it's likely the same thing.
