### ISSUE TITLE
Bromite doesn't load anything and crashes upon opening, But has a funtional UI. 

### ISSUE THREAD

**Issue by thanuj10** [bromite/bromite#218] opened 2019-01-07 14:44 UTC
**Bromite version**

Version: `71.0.3578.120`
Arch: ARM
Android version: Nougat 7.1.2

**Is the bug reproducible with latest version?**
Yes.
**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
Yes.

**Is the bug a crash?**
Yes. I'm not able to record the logcat for some reason, every app crashes with ADB and root enabled :(

**Describe the bug**
Opening bromite results in android system throwing app forced closed errors, but the app does not close.
I'm also not able to load any webpages or search anything.

**To Reproduce**
1. Open Bromite
2. App Crashes, android shows error message, but app is still open and the UI is functional.
3. See Error

**Expected behavior**
Bromite opens and must be able to load webpages and load content.

**Comment by csagan5** [comment] 2019-01-07 17:06
Duplicate of #216

**Closed by csagan5** 2019-01-07 17:06 UTC
Labels: duplicate

**Comment by ouzowtf** [comment] 2019-01-07 17:13
I don't have this problem with OOS 5.0.8 on my OP3T.
Everything works fine.
