### ISSUE TITLE
(Request) Uploading compressed archive

### ISSUE THREAD

**Issue by nihalanand697** [bromite/bromite#717] opened 2020-08-26 17:39 UTC
Hi, not necessary for the majority but is it possible and feasible for you to upload the apk compressed for the minority who are low on data? 
I am attaching an image for a rough comparison to show the difference which is gr

**Comment by csagan5** [comment] 2020-08-26 18:57
Duplicate of #718

**Closed by csagan5** 2020-08-26 18:57 UTC
