### ISSUE TITLE
Adding  decentraleyes  or extension support .

### ISSUE THREAD

**Issue by Techguyprivate** [bromite/bromite#287] opened 2019-04-17 14:50 UTC
**Is your feature request related to privacy?** Yes.
Features that are not related to privacy are unlikely to be considered.

**Is there a patch available for this feature somewhere?**
... https://github.com/kiwibrowser/android

https://github.com/kiwibrowser/android/tree/master/extensions

https://github.com/kiwibrowser/privacy_patches/blob/master/Add-support-for-extensions-on-Android.patch

https://www.xda-developers.com/kiwi-browser-google-chrome-extensions-android/

**Describe the solution you'd like** 

I read at xda that Kiwi browser added extension supports.

 Also read that kiwi browser's source  code is available. 

Can we have extension supports for bromite? 

 I know that a lot of extension are actually bad , even harmful for privacy & security. 

But can we have the ability to install some important extensions like ublock origin, decentraleyes, https everywhere, no script without any other extensions . 

Yandex browser is doing it for years . I mean you can't install ublock, adguard or certain extensions in yandex browser, but you can install other extensions.    

It will be good to have extensions like decentraleyes, https everywhere, even ublock origin.

Or can we have extensions like decentraleyes, https everywhere already installed or enabled or installed only letting users to enable it. 

**Describe alternatives you've considered** 

Or can we have extensions like decentraleyes, https everywhere already installed or enabled or installed only letting users to enable it.  Not letting users to install other extensions , but these 3 or 4 extensions only & also getting automatic updates.

**Comment by csagan5** [comment] 2019-04-17 17:01
Duplicate of #191 (searching the issue tracker before creating an issue is a good idea).

Additionally, Kiwi is closed source. The patch you mentioned is broken and quite old, last time I tried it didn't work (because a lot more code is missing).

See also: https://github.com/kiwibrowser/android/issues/12#issuecomment-435690397

**Closed by csagan5** 2019-04-17 17:01 UTC
Labels: duplicate, invalid

**Comment by chocodamo** [comment] 2020-04-22 01:38
> 
> 
> Duplicate of #191 (searching the issue tracker before creating an issue is a good idea).
> 
> Additionally, Kiwi is closed source. The patch you mentioned is broken and quite old, last time I tried it didn't work (because a lot more code is missing).
> 
> See also: [kiwibrowser/android#12 (comment)](https://github.com/kiwibrowser/android/issues/12#issuecomment-435690397)

Well it seems like the main and only develeoper of Kiwi Browser opened up his source code, with the full intention to encourage other developers to integrate the nitty-gritty parts of his based Chromium browser! 

[Kiwi Browser Source Code](https://github.com/kiwibrowser/src)

Everything is under BSD 3-Clause, by the way.

**Comment by madranet** [comment] 2020-10-20 19:37
> Yandex browser is doing it for years . I mean you can't install ublock, adguard or certain extensions in yandex browser, but you can install other extensions.

You _can_ install uBlock Origin [and other extensions] in Yandex Browser, even though the browser tells you they aren't compatible.

* Download the zip file of the extension and unpack it [plenty of sites and extensions will allow you to do this]

* Go to `chrome://extensions` in Yandex and enable `Developer Mode`

* Then `Load Unpacked Extension` and navigate to and select the `manifest.json` file inside the unzipped extension folder. 

As you can see, uBlock installs and works fine on Yandex Browser:

![SS-2020-10-20-at-20 21 02crop](https://user-images.githubusercontent.com/669658/96635187-726d3c80-1313-11eb-85c4-7886f26f694a.png)

![SS-2020-10-20-at-20 26 20crop](https://user-images.githubusercontent.com/669658/96635188-726d3c80-1313-11eb-8f16-29ef219fb2db.png)

_[Sorry for going off-topic. But just wanted to correct that detail, for anyone else who might read the this issue]_
