### ISSUE TITLE
Add my personal search engine

### ISSUE THREAD

**Issue by alexmat** [bromite/bromite#267] opened 2019-03-18 00:30 UTC
**Is your feature request related to privacy?**
Yes

**Is there a patch available for this feature somewhere?**
No

**Describe the solution you'd like**
I run my own search engine instance and would like to be able to use it by default. This works well in Brave.

**Describe alternatives you've considered**
None

**Comment by csagan5** [comment] 2019-03-18 01:03
What search engine instance?

If it works well in Brave you could ask on the Brave forums how that is possible so that the same patch can be used here.

**Comment by csagan5** [comment] 2019-03-18 01:08
Duplicate of #91.

**Closed by csagan5** 2019-03-18 01:08 UTC

**Comment by thestinger** [comment] 2019-08-03 05:57
It's already possible to add custom search engines. You need to visit a compatible search engine and then it will show up as a possibility to add it in the search engine settings.
