### ISSUE TITLE
Time Zone - Web Finger printing

### ISSUE THREAD

**Issue by basimaslamts** [bromite/bromite#633] opened 2020-07-01 12:10 UTC
### Bromite version

Version: `83.0.4103.101
Arch:  `arm64`
Android version: 10
Device model: Doesn't apply

### Is this bug about the SystemWebView?
Yes/No
No

### Is the bug reproducible with latest version?
Yes

### Can the bug be reproduced with corresponding Chromium version?
I think so - Checked with Safari, Kiwi and issue is there (I'm not completely sure)

### Is the bug a crash?
No

### Describe the bug
Browser finger print which shows your exact place eventhough you browse in incognito with VPN
An issue was made by someone  #509 which were closed because of having no template.

### Steps to reproduce the bug

Turn on VPN and incognito mode

Go to the site:
https://panopticlick.eff.org/

Ask for a finger print test. It will show your exact time zone. But you r using a VPN

### Expected behavior
Time Zone of the connected country or other alternatives

### Screenshots
Cant provide that.

**Comment by csagan5** [comment] 2020-07-01 19:19
Duplicate of #331

**Closed by csagan5** 2020-07-01 19:19 UTC
