### ISSUE TITLE
A new challenger appears... in search bar

### ISSUE THREAD

**Issue by mutachre** [bromite/bromite#2170] opened 2022-07-04 23:36 UTC
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

102.0.5005.96

### Device architecture

arm64-v8a

### Android version

12.0

### Device model

OnePlus 8T (KB2003)

### Changed flags

Untouched.

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

A face appears in search bar, everytime start typing.

### Steps to reproduce the bug

Just search on search bar (Google provider).

### Expected behavior

Default search bar, no strange pictures.

### Screenshots

![Screenshot_2022-07-04-16-16-02-45_ed7821ed99ee442dec4ede205e7971d6](https://user-images.githubusercontent.com/62408551/177225500-efd06d0d-4d9d-436a-a185-d678d4664467.jpg)

**Comment by n-buna404** [comment] 2022-07-05 09:11
is this favicon from website u viewed? suspect it is related to https://github.com/bromite/bromite/issues/788

**Comment by csagan5** [comment] 2022-07-09 07:42
Duplicate of #788

**Closed by csagan5** 2022-07-09 07:42 UTC
Labels: bug, needs-triage
