### ISSUE TITLE
Remove the Google login nag

### ISSUE THREAD

**Issue by cdysthe** [bromite/bromite#31] opened 2018-01-27 02:41 UTC
Since we aren't allowed to log in to Google would it be possible to remove the Google nag regarding this from Bromite? No need to be urged to do something they won't let us do anyway.

**Comment by csagan5** [comment] 2018-02-07 18:19
Agree; once again, I did not do this because I could not find it easily in the code.

**Comment by csagan5** [comment] 2018-02-18 18:38
This is fixed, and it was a duplicate of #11 anyway.

**Closed by csagan5** 2018-02-18 18:38 UTC
Labels: bug

**Comment by csagan5** [comment] 2018-03-19 08:18
@cdysthe is this fixed from your testing?
