### ISSUE TITLE
user-installed certificates is still not allowed

### ISSUE THREAD

**Issue by J-khatri** [bromite/bromite#934] opened 2021-02-17 07:11 UTC
### Bromite version

Version: `83.0...`
Arch: `arm` or `arm64` or `x86`
Android version: (example: `9.0`)
Device model: (example: `SM-G960UZKABST`)

### Is this bug about the SystemWebView?
No

### Is the bug a crash?

No

### Describe the bug

In change log it says that user installed certificate patch is dropped , but still I'm not able to use user certificate ( from my adblocker ).
So I think user-installed certificates is not dropped !!

Or has any issue ?

### Steps to reproduce the bug

Steps to reproduce the bug:
2. Click on '...'
3. Scroll down to '...'

### Expected behavior

It should not complaint about certificate

**Comment by csagan5** [comment] 2021-02-17 11:57
Duplicate of #921

**Closed by csagan5** 2021-02-17 11:57 UTC
